export type FingerColor = "red" | "green" | "blue" | "yellow" | "gray";

export const keyFingerMap: Record<string, FingerColor> = {
  "`": "red", "1": "red", "q": "red", "a": "red", "z": "red",
  "~": "red", "!": "red", "Q": "red", "A": "red", "Z": "red",
  "2": "green", "w": "green", "s": "green", "x": "green",
  "@": "green", "W": "green", "S": "green", "X": "green",
  "3": "blue", "e": "blue", "d": "blue", "c": "blue",
  "#": "blue", "E": "blue", "D": "blue", "C": "blue",
  "4": "yellow", "5": "yellow", "r": "yellow", "t": "yellow",
  "f": "yellow", "g": "yellow", "v": "yellow", "b": "yellow",
  "$": "yellow", "%": "yellow", "R": "yellow", "T": "yellow",
  "F": "yellow", "G": "yellow", "V": "yellow", "B": "yellow",
  "6": "yellow", "7": "yellow", "y": "yellow", "u": "yellow",
  "h": "yellow", "j": "yellow", "n": "yellow", "m": "yellow",
  "^": "yellow", "&": "yellow", "Y": "yellow", "U": "yellow",
  "H": "yellow", "J": "yellow", "N": "yellow", "M": "yellow",
  "8": "blue", "i": "blue", "k": "blue", ",": "blue",
  "*": "blue", "I": "blue", "K": "blue", "<": "blue",
  "9": "green", "o": "green", "l": "green", ".": "green",
  "(": "green", "O": "green", "L": "green", ">": "green",
  "0": "red", "-": "red", "=": "red", "p": "red",
  "[": "red", "]": "red", "\\": "red", ";": "red", "'": "red", "/": "red",
  ")": "red", "_": "red", "+": "red", "P": "red",
  "{": "red", "}": "red", "|": "red", ":": "red", '"': "red", "?": "red",
  " ": "gray",
};

export type Lesson = {
  id: number;
  sectionIndex: number;
  lessonIndex: number;
  title: string;
  text: string;
  targetWpm: number;
  targetAccuracy: number;
};

export type Section = {
  index: number;
  title: string;
  subtitle: string;
  newKeys: string[];
  color: string;
  bgColor: string;
  emoji: string;
  lessons: Lesson[];
};

type RawLesson = [string, string, number?];

function buildSection(
  index: number,
  title: string,
  subtitle: string,
  newKeys: string[],
  color: string,
  bgColor: string,
  emoji: string,
  rawLessons: RawLesson[],
): Section {
  const lessons: Lesson[] = rawLessons.map(([t, text, wpm], li) => ({
    id: 0,
    sectionIndex: index,
    lessonIndex: li,
    title: t,
    text,
    targetWpm: wpm ?? 20 + index * 2,
    targetAccuracy: 90,
  }));
  return { index, title, subtitle, newKeys, color, bgColor, emoji, lessons };
}

const rawSections: Section[] = [
  buildSection(0, "Home Row", "الصف الرئيسي: A S D F G H J K L ;", ["f","j","d","k","s","l","a",";","g","h"], "#F59E0B", "rgba(245,158,11,0.12)", "🏠", [
    ["F and J — the anchor keys", "fff jjj fff jjj fjf jfj ffj jjf fjfj jfjf", 15],
    ["F and J pairs", "fj jf ff jj fj jf fj jf ffjj jjff fjf jfj", 15],
    ["F and J rhythm", "fjfj jfjf ffjj jjff fjfj jfjf fff jjj fj", 16],
    ["D and K", "ddd kkk ddd kkk dkd kdk ddk kkd dkdk kdkd", 16],
    ["D and K pairs", "dk kd dd kk dk kd dk kd dkdk kdkd ddk kkd", 16],
    ["F D with J K", "fd jk fd jk df kj fd jk fdjk kjdf df kj", 17],
    ["S and L", "sss lll sss lll sls lsl ssl lls slsl lsls", 17],
    ["S and L pairs", "sl ls ss ll sl ls sl ls slsl lsls ssl lls", 17],
    ["F S D with J L K", "fsd jlk fsd jlk sdf lkj fds jkl sdf lkj", 18],
    ["A and ;", "aaa ;;; aaa ;;; a;a ;a; aa;; ;;aa a;a; ;a;a", 18],
    ["A and ; pairs", "a; ;a aa ;; a; ;a a; ;a a;;a ;aa; aa ;;", 18],
    ["Home row — left hand", "fdsa fdsa asdf asdf dfas sadf fdas asdf", 18],
    ["Home row — right hand", "jkl; ;lkj jkl; ;lkj kl;j j;lk jkl; ;lkj", 18],
    ["G and H — index extends", "ggg hhh ggg hhh ghg hgh ggh hhg ghgh hghg", 19],
    ["G and H reach", "fg gh hj fgh ghj jgh fg gh fgh jhg gfh", 19],
    ["Full home row with G H", "asdfghjkl; ;lkjhgfdsa asdfghjkl; ;lkjhgfdsa", 19],
    ["Home row review A", "fdsa jkl; ghj fds jkl; asdf ;lkj gh fj", 19],
    ["Home row review B", "asdfjkl; ;lkjfdsa asdfjkl; ghj gfh jgh", 20],
    ["Word: lad fad sad", "lad lad fad fad sad sad all all dad dad", 20],
    ["Word: ask lass flask", "ask ask lass lass flask flask dad dads ads", 20],
    ["Word: glad flash half", "glad glad flash flash half half fall falls", 20],
    ["Word: hall flag lash", "hall hall flag flag lash lash gash gash dash", 21],
    ["Word: dash hash glass", "dash dash hash hash glass glass slag slag", 21],
    ["Words mix — home row", "lad fad glad flask half lash flash hall flag", 21],
    ["Sentence: lads and lasses", "a lad falls; all glad; ask a lass; fall", 22],
    ["Sentence: flash a flag", "flash a flag; half a flask; all fall; glad", 22],
    ["Sentence: salad falls", "a salad falls; ask a lass; glad all; fall", 22],
    ["Sentence: sad dads", "sad dads ask; a lash falls; all glad; fall", 22],
    ["Sentence: flags fall", "flash flags fall; glad halls; half a flask", 23],
    ["Speed drill — home row", "all flags fall; glad lads; half a flask; ask", 23],
  ]),

  buildSection(1, "E and I", "الحروف E و I", ["e","i"], "#10B981", "rgba(16,185,129,0.12)", "✌️", [
    ["E — the most common letter", "eee eee ee ee eel eel eel fee fee see see", 22],
    ["E reach drill", "dee fee see led eel heel feel seal deal", 22],
    ["E words", "feel feel heel heel seal seal deal deal feed", 22],
    ["E in phrases", "feel a seal; see the eel; deal ahead; she fled", 23],
    ["I drill", "iii iii ii ii lid lid fig fig did did dig", 23],
    ["I reach drill", "dig dig fig fig kid kid silk silk lid lid", 23],
    ["I words", "idea aide side silk disk kids jade said laid", 23],
    ["I in phrases", "she hid; a kid slid; file a dial; silk isle", 24],
    ["E and I together", "feel like file idea side said fail sail isle", 24],
    ["E and I words", "ideal silk deals files feel slide aside eels", 24],
    ["Words: file dial fail", "file dial fail silk disk kids jade slide idea", 25],
    ["Words: ideas sealed", "ideas sealed filed ailed kidded sailed jailed", 25],
    ["Words: dead lead fled", "dead lead fled shed eel deal ideal head led", 25],
    ["Words: jaded skilled", "jaded skilled sealed failed sided filed ailed", 25],
    ["Sentence: feel silk", "feel a silk; a jade idea; slide aside; ideal", 26],
    ["Sentence: seal a deal", "seal a deal; a kid slides; ideal silk; she fled", 26],
    ["Sentence: side a file", "side a file; feel like silk; idea fails; deal", 26],
    ["Sentence: she died", "she died; a kid said; jaded lads flee; silk isle", 26],
    ["Sentence: silk ideas", "like a silk slide; ideal jade deals; feel side", 27],
    ["Sentence: jade eels", "she flees; feel like jade; silk ideas; she fled", 27],
    ["Sentence: a kid hides", "a kid hides; jade seals; feel like silk; aside", 27],
    ["Challenge: ideal skills", "ideal skills; silk deals fail; jaded ideas flee", 27],
    ["Challenge: jade seal", "feel like a jade seal; kids slide aside; ideal", 28],
    ["Challenge: silk fails", "all silk fails; ideal kids; jade eels; she fled", 28],
    ["Speed: feel silk side", "feel silk side ideal jade disk file dial slide", 28],
    ["Speed: jaded silk", "jaded silk; ideal fails; eel slides; she fled", 29],
    ["Sentence: silk seals", "silk seals; jade deals; feel like an eel; aside", 29],
    ["Sentence: she fled", "she fled; kids slide; jade eels; ideal silk", 29],
    ["Sentence: silk deals", "silk deals fail; feel aside; a jade idea; eels", 30],
    ["Speed challenge", "jaded kids flee; silk fails; ideal seals; slide", 30],
  ]),

  buildSection(2, "R and U", "الحروف R و U", ["r","u"], "#8B5CF6", "rgba(139,92,246,0.12)", "🎯", [
    ["R drill", "rrr rrr rr rr red red rid rid rule rule fur", 28],
    ["R reach drill", "rr rr fur fur far far her her dear dear dark", 28],
    ["R words", "rule rude ruse rush desk risk dark lark fir", 29],
    ["R reach words", "red rid her fire hire dire flair sir fur far", 29],
    ["U drill", "uuu uuu uu uu rug rug fur fur rush rush lure", 29],
    ["U reach drill", "uu uu lure sure dusk rug gush hush rusk rule", 30],
    ["U words", "rule lure sure fuel duel surf flush rusk dusk", 30],
    ["U reach words", "ruse fuse dusk rusk gush hush rush lush flush", 30],
    ["R and U together", "rule ruler rude rush rural ruse sure lure surf", 31],
    ["R and U words", "fuel surf lurk rural lure sure fire hire rule", 31],
    ["Words: fire hire dire", "fire hire dire sir her fur rush rule fuel duel", 31],
    ["Words: dark lark risk", "dark lark risk disk surf rush flush fur lure", 32],
    ["Words: fear dear hear", "fear dear hear gear laser ruler eraser elder", 32],
    ["Words: rural duel fuel", "rural duel fuel feud drill girl furl grill", 32],
    ["Sentence: rule a ruse", "rule a ruse; a dark lark; fear her; sure fire", 33],
    ["Sentence: rush a rule", "rush a rule; sure lads; flush a desk; fuel fire", 33],
    ["Sentence: a dark girl", "a dark girl; rush a ruler; fire aside; sure rule", 33],
    ["Sentence: fear a drill", "fear a drill; fuel a fire; sure lads; dark rule", 34],
    ["Sentence: rural lads", "rural lads flush; rush aside; rule all; sure fire", 34],
    ["Sentence: a dark laser", "a dark laser; sure fire; dear sir; furl a rule", 34],
    ["Challenge: rush rule", "rush rule rural; fuel drills; dark girls; sure", 35],
    ["Challenge: sure fire", "sure fire deal; fear a dark ruler; silk slide", 35],
    ["Challenge: fuel a drill", "fuel a drill; rural girls rush; lure fear; sure", 35],
    ["Speed: rule rude sure", "rule rude sure fire hire dark lark risk flush", 36],
    ["Speed: rush flush", "rush flush gush hush sure lure dear fear dark", 36],
    ["Speed: rural laser", "rural laser ruler eraser dusk rusk surf dark", 36],
    ["Sentence: fire a rule", "fire a rule; silk girls; dear sir rushes; sure", 37],
    ["Speed challenge", "sure dark lads; a rural girl; fuel a fire; rush", 37],
  ]),

  buildSection(3, "T and Y", "الحروف T و Y", ["t","y"], "#EF4444", "rgba(239,68,68,0.12)", "⚡", [
    ["T drill", "ttt ttt tt tt try try try the the test test", 34],
    ["T reach drill", "tt tt get set let hit sit kit get set hit", 34],
    ["T words", "test trail steel start still trust trail the", 35],
    ["T reach words", "third their there three thirty dirty thirty", 35],
    ["Y drill", "yyy yyy yy yy yes yes yet yet sky sky dry", 35],
    ["Y reach drill", "yy yy sky dry try fly yes yet style dusty", 36],
    ["Y words", "style study dirty daily truly dusty rusty", 36],
    ["Y reach words", "rusty tasty thirty dirty style sky fly dry", 36],
    ["T and Y together", "dirty thirty rusty dusty truly style trust", 37],
    ["T and Y words", "thirty tasty daily study trust trail dusty", 37],
    ["Words: try yet yes", "try yet yes sky the get set let hit sit kit", 37],
    ["Words: test trail still", "test trail still skill steel trust start", 38],
    ["Words: third their there", "third their there three dirty thirty style", 38],
    ["Words: style study dusty", "style study dusty rusty truly trail tasty", 38],
    ["Sentence: try the trail", "try the trail; a dirty lad; three girls; style", 39],
    ["Sentence: there are three", "there are three; yet still dark; truly style", 39],
    ["Sentence: their style", "their style is truly dirty; trust skill; try", 39],
    ["Sentence: start the study", "start the study; a trail leads there; thirty", 40],
    ["Sentence: the third girl", "the third girl; trust a dirty ruler; yet there", 40],
    ["Sentence: try yet", "try yet; still their style; three trusts; sky", 40],
    ["Challenge: still their", "yet still their; dirty thirty; trust all; three", 41],
    ["Challenge: third trail", "the third trail; start a study; truly dirty", 41],
    ["Challenge: try their style", "try their style; yet there are thirty; skill", 41],
    ["Speed: try yet yes", "try yet yes sky the get set let hit sit kit", 42],
    ["Speed: trail third their", "trail third their there style study trust", 42],
    ["Speed: dirty thirty", "dirty thirty rusty dusty daily truly style", 42],
    ["Sentence: trail leads there", "the trail leads there; yet trust skill; style", 43],
    ["Speed challenge", "study their style; start a dirty trail; thirty", 43],
  ]),

  buildSection(4, "O and W", "الحروف O و W", ["o","w"], "#06B6D4", "rgba(6,182,212,0.12)", "🌊", [
    ["O drill", "ooo ooo oo oo old old old told told fold fold", 40],
    ["O reach drill", "oo oo fold hold gold sold role sole does goes", 40],
    ["O words", "old told sold fold hold gold role sole does", 41],
    ["O reach words", "your hour four folk yolk wolf flow soul role", 41],
    ["W drill", "www www ww ww was word word will wolf work", 41],
    ["W reach drill", "ww ww wolf flow glow show slow grow throw stow", 42],
    ["W words", "wolf flow glow show slow grow throw word work", 42],
    ["W reach words", "word work wore worry lower older other world", 42],
    ["O and W together", "word world work lower older other order offer", 43],
    ["O and W words", "wolf flow glow show slow grow throw soul wool", 43],
    ["Words: old told fold", "old told fold gold role sole does goes toes woes", 43],
    ["Words: word work worry", "word work worry your hour tour four soul folk", 44],
    ["Words: world story store", "world story store older other order offer floor", 44],
    ["Words: throw glow flow", "throw glow flow show grow slow wolf soul four", 44],
    ["Sentence: the wolf shows", "the wolf shows gold; old folk hold; flow slow", 45],
    ["Sentence: work the story", "work the old story; fold the world; show; grow", 45],
    ["Sentence: lower the gold", "lower the gold; throw a soul; fold here; slow", 45],
    ["Sentence: the world offers", "the world offers other orders; slow flow grows", 46],
    ["Sentence: gold grows", "gold grows; word story; three old worlds; show", 46],
    ["Sentence: throw the wolf", "throw the wolf; she shows old gold; role; grow", 46],
    ["Challenge: world grows", "the world grows; offer others; old story; show", 47],
    ["Challenge: wolf throws", "wolf throws gold; world shows other roles; flow", 47],
    ["Challenge: slow flow grows", "slow flow grows; older world offers store; folk", 47],
    ["Speed: old told fold", "old told fold gold sole does goes word world", 48],
    ["Speed: word work world", "word work world story store throw grow wolf", 48],
    ["Speed: wolf flow glow", "wolf flow glow show slow your hour tour four", 48],
    ["Sentence: work the gold", "work the old gold; show their role; grow world", 49],
    ["Speed challenge", "the wolf grows old; throw a show; world offers", 49],
  ]),

  buildSection(5, "Q and P", "الحروف Q و P", ["q","p"], "#F97316", "rgba(249,115,22,0.12)", "🎪", [
    ["P drill", "ppp ppp pp pp paid pale park part past path", 46],
    ["P reach drill", "pp pp pull pull port post peel peer poet pour", 46],
    ["P words", "paid pale park part past path port post peel", 47],
    ["P reach words", "pour power player prayer spirit spiral pride", 47],
    ["Q drill", "qqq qqq qq qq query quiet quote quest quit", 47],
    ["Q reach drill", "qq qq quite quite quest quest quote queasy", 48],
    ["Q words", "quite quest quote queasy quit quality queries", 48],
    ["Q and P together", "quite a poet; prior quest; pour a spirit; sport", 48],
    ["Words: tip hip lip sip", "tip hip lip sip rip dip flip slip drip strip", 49],
    ["Words: ship whip grip", "ship whip grip strip sport split pulse power", 49],
    ["Words: paid pale park", "paid pale park part past path port post peer", 49],
    ["Words: quite quest quote", "quite quest quote queasy quality spirit split", 50],
    ["Sentence: sport a quest", "sport a prior quest; quite the poet; power", 50],
    ["Sentence: pour a spirit", "pour a spirit; paid the sport; quit all; prior", 50],
    ["Sentence: prior praise", "prior praise; quite a power trip; sport; quest", 51],
    ["Sentence: quite spiritual", "the quest is quite spiritual; sport paid; power", 51],
    ["Sentence: quite guides", "spirit quite guides; prior poetry; sport; quest", 51],
    ["Sentence: quite powerful", "sport is quite powerful; prayer quest; spirit", 52],
    ["Challenge: prior powerful", "prior quite powerful; spirit guides; sport; paid", 52],
    ["Challenge: quest for quality", "quest for quality; sport pride; quite past", 52],
    ["Challenge: spirit prayer", "spirit prayer; quite prior sport; quest; split", 53],
    ["Speed: sport split pulse", "sport split pulse power pride prior pair paid", 53],
    ["Speed: quite quest quote", "quite quest quote queasy quality spirit split", 53],
    ["Sentence: quality sport", "quite a quality sport; prior quest; spirit paid", 54],
    ["Speed challenge", "quite the prior sport; spirit quest; paid power", 54],
    ["Final challenge", "spirit prayer quite prior; sport quality quest", 55],
  ]),

  buildSection(6, "B and N", "الحروف B و N", ["b","n"], "#EC4899", "rgba(236,72,153,0.12)", "🌟", [
    ["N drill", "nnn nnn nn nn need need note note night north", 52],
    ["N reach drill", "nn nn north nurse noble noise noted nerd nose", 52],
    ["N words", "need note night north noble noise nurse nerd", 53],
    ["N reach words", "neither nor into inner enjoy entire never note", 53],
    ["B drill", "bbb bbb bb bb born burn band bond bind bend", 53],
    ["B reach drill", "bb bb blue blur bird bind best bent bull boy", 54],
    ["B words", "born burn band bond bind bend bird blue blur", 54],
    ["B reach words", "best blue blur brown brand brain built blend", 54],
    ["B and N together", "blend blind blood bring born night nurse noble", 55],
    ["B and N words", "brown brand brain noble noted north bend bind", 55],
    ["Words: need note night", "need note night north noble nurse nerd noise", 55],
    ["Words: born burn blue", "born burn blue best blend blind blood bring", 56],
    ["Words: brown brand bring", "brown brand bring bird body bone bore born", 56],
    ["Words: noble night nurse", "noble night neither noise north nurse build", 56],
    ["Sentence: bird burns bright", "the bird burns bright; blend all four; blood", 57],
    ["Sentence: blue bond night", "bring the blue bond; night north birds; born", 57],
    ["Sentence: noble brand", "noble brand; burned bond; blind note night; build", 57],
    ["Sentence: north nurse", "the north nurse; blend a night bird; bond; bring", 58],
    ["Sentence: bright bold birds", "bright bold birds; blend the night; bond born", 58],
    ["Sentence: burn a blue note", "burn a blue note; bring night; bond north; blend", 58],
    ["Challenge: blind night", "blind night; noble bond; bring the north bird", 59],
    ["Challenge: blue blend", "blend blue; bright night; noble birds bond; born", 59],
    ["Challenge: bold blend", "bright and bold; blend the night; bond north", 59],
    ["Speed: born burn blue", "born burn blue best bend bird note night north", 60],
    ["Speed: blend blind", "blend blind blood bring north noble nurse born", 60],
    ["Sentence: night bird brings", "the night bird brings blue; bond; noble brand", 60],
    ["Speed challenge", "the night nurse blends blue; burn noble bond", 61],
  ]),

  buildSection(7, "V and M", "الحروف V و M", ["v","m"], "#6366F1", "rgba(99,102,241,0.12)", "💎", [
    ["M drill", "mmm mmm mm mm men men mind mind more most", 58],
    ["M reach drill", "mm mm make mark meet more most mother memory", 58],
    ["M words", "mind mine milk mild many make mark meet more", 59],
    ["M reach words", "move more most mother memory member major men", 59],
    ["V drill", "vvv vvv vv vv very view void vote live five", 59],
    ["V reach drill", "vv vv live drive five dive give move love video", 60],
    ["V words", "very view void vote live drive give dive five", 60],
    ["V reach words", "video movie valve value volume novel love above", 60],
    ["V and M together", "move mind video movie major member memory novel", 61],
    ["V and M words", "value volume novel memory never seven level given", 61],
    ["Words: men mind mine", "men mind mine milk make mark meet more move", 61],
    ["Words: live drive give", "live drive give dive five love above never ever", 62],
    ["Words: value video movie", "value video movie valve move minor volume", 62],
    ["Words: never seven level", "never seven level given over ever memory minor", 62],
    ["Sentence: move the valve", "move the valve; memory of video; novel; major", 63],
    ["Sentence: drive more miles", "drive more miles; give value; love novel; move", 63],
    ["Sentence: seven members", "seven members; video of a movie; give minor", 63],
    ["Sentence: minor move", "minor move; major novel; value memory; seven", 64],
    ["Sentence: movie drives", "the movie drives seven major moves; value", 64],
    ["Sentence: love the video", "love the video; novel memory; move on; seven", 64],
    ["Challenge: seven minor", "seven minor moves; movie novel; drive value; vim", 65],
    ["Challenge: major video", "major video moves; love the novel; give minor", 65],
    ["Challenge: never move a valve", "never move a valve; major minor memory; seven", 65],
    ["Speed: men mind mine", "men mind mine milk make mark move more major", 66],
    ["Speed: live drive give", "live drive give five love above never seven", 66],
    ["Sentence: give major value", "give major value; movie drives love; seven", 66],
    ["Speed challenge", "seven minor moves; give major value; movie love", 67],
  ]),

  buildSection(8, "C", "الحرف C", ["c"], "#14B8A6", "rgba(20,184,166,0.12)", "🌙", [
    ["C drill", "ccc ccc cc cc can can car car cap cap code", 64],
    ["C reach drill", "cc cc cold cold come come code code core care", 64],
    ["C words", "can car cap care card core cool cord cold come", 65],
    ["C blends: cl, cr, sc", "cl cl cl cr cr cr sc sc ch ch clean crack", 65],
    ["C words: city civil", "cold come code city civil child color cover", 65],
    ["C words: clean clear", "clean clear close cloud count court cycle claim", 66],
    ["C words: black block", "black block clock crack track quick trick stick", 66],
    ["C review", "care code can cold cover count cycle civil", 66],
    ["Sentence: cool car", "cool car; clean code; black cloud; count cycle", 67],
    ["Sentence: civil court", "count the clock; civil court; clear code; clean", 67],
    ["Sentence: cold cover", "cold cover; black car; cycle the track; civil", 67],
    ["Sentence: quick clean", "quick clean code; cold clock; civil court; count", 68],
    ["Sentence: cover the cold", "cover the cold car; count to track; cool core", 68],
    ["Sentence: city code", "city code; clean civil cycle; black core; cloud", 68],
    ["Sentence: count cool cars", "count the cool cars; black cloud; core; cycle", 69],
    ["Challenge: cold clean code", "cold clean code; city civil court; clock count", 69],
    ["Challenge: black block", "black block; cover the core; clock track; civil", 69],
    ["Challenge: quick cycle", "quick cycle; civil court count; cool code; black", 70],
    ["Speed: can car cap care", "can car cap care card cold come code civil", 70],
    ["Speed: clean clear close", "clean clear close cloud black block clock", 70],
    ["Sentence: cool car cycles", "a cool car cycles; cover the black core; count", 71],
    ["Speed challenge", "count civil courts; clean cold code; track cycle", 71],
  ]),

  buildSection(9, "X", "الحرف X", ["x"], "#84CC16", "rgba(132,204,22,0.12)", "✖️", [
    ["X drill", "xxx xxx xx xx exit exit next next text text", 68],
    ["X reach drill", "xx xx fix mix six wax tax max lax flex flux", 68],
    ["X words", "exit next text flex flux fox box hex vex fix", 69],
    ["X words: exact extra", "exact extra exist expect export excel relax", 69],
    ["X words: expert extreme", "expert extreme except expand relax vex six", 69],
    ["X blends: ex, ox, ax", "ex ex ex fox fox box box fix fix mix mix wax", 70],
    ["Sentence: exit next", "exit next; exact text; flex the fox; fix six", 70],
    ["Sentence: mix six wax", "mix six wax; extra flux; vex the expert; relax", 70],
    ["Sentence: excel at next", "excel at the next text; fix exact exit; relax", 71],
    ["Sentence: expert relaxes", "expert relax; except expand; extract six; exit", 71],
    ["Sentence: next expert exits", "next expert exits; exact text; fix extra; flex", 71],
    ["Sentence: extreme flux", "explore the extreme; expand six; fix flux; exact", 72],
    ["Challenge: expert text", "expert text; exact fix; next extra flux; exit", 72],
    ["Challenge: exit expert", "exit expert; extreme relax; excel six; expand", 72],
    ["Challenge: expand exact", "expand exact; six experts exit; flex; extra wax", 73],
    ["Speed: exit next text", "exit next text flex flux fox box fix mix six", 73],
    ["Speed: exact extra exist", "exact extra exist expect export excel relax", 73],
    ["Sentence: fix six exact", "fix six exact texts; next expert exits; relax", 74],
    ["Sentence: extreme flux expert", "extreme flux; expert excel; exact expand; exit", 74],
    ["Speed challenge", "the next export expert is quite flexible; exit", 74],
  ]),

  buildSection(10, "Z", "الحرف Z", ["z"], "#A78BFA", "rgba(167,139,250,0.12)", "⚡", [
    ["Z drill", "zzz zzz zz zz zip zip zero zero zone zone", 72],
    ["Z reach drill", "zz zz zone zoom zeal zap zest fizz buzz jazz", 72],
    ["Z words", "zero zone zoom zeal zip zap zest fizz buzz", 73],
    ["Z words: pizza quiz", "fizz fuzz buzz jazz pizza quiz prize freeze", 73],
    ["Z words: blaze glaze", "freeze graze blaze glaze haze maze gaze daze", 73],
    ["Z words: crazy dozen", "crazy dozen fuzzy dizzy amaze daze raze size", 74],
    ["Z blends: fr, gr, gl, bl", "fr fr fr gr gr gr gl gl bl bl freeze graze", 74],
    ["Sentence: zero zone", "zero zone; buzz jazz; fizz pizza; zoom in; zeal", 74],
    ["Sentence: crazy prize", "zoom in; crazy prize; freeze the daze; blaze", 75],
    ["Sentence: quiz zero", "quiz zero; blaze through; fuzzy dizzy zone; jazz", 75],
    ["Sentence: jazz and pizza", "jazz and pizza; crazy maze; glaze a prize; zero", 75],
    ["Sentence: fizzy pizza", "zero buzz; fizzy pizza; zoom crazy zone; blaze", 76],
    ["Challenge: jazz quiz", "jazz quiz; prize freeze; crazy daze; buzz zone", 76],
    ["Challenge: fuzzy zone", "fuzzy zone; pizza blaze; dozen mazes; zero prize", 76],
    ["Challenge: zero prize", "zero prize; crazy buzz; fizzy dizzy jazz; zoom", 77],
    ["Speed: zero zone zoom", "zero zone zoom zeal zip zap fizz buzz jazz", 77],
    ["Speed: crazy dozen fuzzy", "crazy dozen fuzzy dizzy amaze prize freeze", 77],
    ["Sentence: jazz pizza freezes", "jazz pizza freezes; a crazy fuzzy zone; blaze", 78],
    ["Sentence: dozen prizes", "dozen prizes; zero buzz; fizzy jazz zone; dizzy", 78],
    ["Speed challenge", "zoom the crazy prize; fuzzy jazz pizza; blaze", 78],
  ]),

  buildSection(11, "Numbers", "الأرقام 0-9", ["0","1","2","3","4","5","6","7","8","9"], "#F59E0B", "rgba(245,158,11,0.12)", "🔢", [
    ["1 and 2", "111 222 111 222 12 21 12 21 112 221 12 21", 20],
    ["3 and 4", "333 444 333 444 34 43 34 43 334 443 34 43", 20],
    ["5 and 6", "555 666 555 666 56 65 56 65 556 665 56 65", 20],
    ["7 and 8", "777 888 777 888 78 87 78 87 778 887 78 87", 20],
    ["9 and 0", "999 000 999 000 90 09 90 09 990 009 90 09", 21],
    ["1 through 5", "12345 54321 12345 54321 135 246 135 246", 21],
    ["6 through 0", "67890 09876 67890 09876 680 790 680 790", 21],
    ["All numbers", "1234567890 0987654321 12345 67890 13579 24680", 22],
    ["Number pairs", "11 22 33 44 55 66 77 88 99 00 12 34 56 78 90", 22],
    ["Numbers with letters", "zone 1 code 2 disk 3 file 4 note 5 risk 6", 22],
    ["Phone numbers", "1234 5678 9012 3456 7890 1234 5678 9012", 23],
    ["Years", "2020 2021 2022 2023 2024 2025 2026 2027", 23],
    ["Counts", "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18", 23],
    ["Mixed: room numbers", "room 12 floor 34 unit 56 gate 78 door 90", 24],
    ["Sentence: 5 cats", "the 5 cats drink 10 cups of milk daily at noon", 24],
    ["Sentence: 3 birds fly", "3 birds fly over 7 trees in zone 4 today", 24],
    ["Sentence: 365 days", "2024 is a year of 365 days and 12 months total", 25],
    ["Sentence: score 98", "my score is 98 out of 100 in the final test", 25],
    ["Sentence: buy 3 books", "buy 3 books and 4 pens for 15 students today", 25],
    ["Sentence: code 5872", "the code is 5872; enter room 304; floor 7", 26],
    ["Challenge: 9 numbers", "type 9 numbers now: 12345 and 67890 fast", 26],
    ["Challenge: 1st 2nd 3rd", "write 1st 2nd 3rd 4th 5th 6th 7th 8th results", 26],
    ["Speed: 12 34 56", "12 34 56 78 90 123 456 789 1234 5678 9012", 27],
    ["Speed: all 10 digits", "1234567890 0987654321 11223344 55667788 99", 27],
    ["Challenge: score 97", "a score of 97 in 10 tests gives 970 total points", 27],
    ["Challenge: 5 cats 4 dogs", "5 cats 4 dogs 3 birds 2 fish 1 turtle in zone 6", 28],
    ["Sentence: 8 students", "the 8 students scored 75 80 90 95 and 100 total", 28],
    ["Sentence: zone 4", "zone 4 has 12 streets and 300 buildings today", 28],
    ["Sentence: 50 items", "order 50 items for 25 groups of 8 people by 3", 29],
    ["Speed challenge", "buy 12 of item 456 at $0 for 78 of 90 groups", 29],
  ]),

  buildSection(12, "Shift and Symbols", "Shift والرموز", ["Shift","!","@","#","$","%"], "#EC4899", "rgba(236,72,153,0.12)", "🔡", [
    ["Capital F and J", "FFF JJJ FFF JJJ FfFf JjJj Fff Jjj Fjfj Jfjf", 22],
    ["Capital home row", "Aaa Sss Ddd Fff Jjj Kkk Lll Ggg Hhh Asd", 23],
    ["Capital common words", "The For All And But Nor Yet So Or If As", 24],
    ["Capital names", "Fred Jack Sara Lisa Dave Kate John Jane Bob", 25],
    ["Full capitals", "FAST SLOW STOP GO JUMP RUN FLY SWIM WALK", 25],
    ["Capital sentences", "The Quick Fox Jumps; The Night Is Dark", 26],
    ["! exclamation", "Stop! Go! Run! Jump! Fly! Quick! Yes! No! Wow!", 26],
    ["@ at sign", "user@mail.com send@web.net admin@site.org", 27],
    ["# hash", "note #1 #2 #3 is the #best; #100 top notes", 27],
    ["$ dollar", "buy for $5 $10 $100 $500 and save $25 more", 27],
    ["% percent", "25% off 50% done 75% ready 100% complete", 28],
    ["^ caret", "x^2 y^3 z^4 a^b c^d e^f power^of^2 rise^up", 28],
    ["& ampersand", "fish & chips; salt & pepper; blue & gold; sun & moon", 28],
    ["* asterisk", "5*5=25 10*10=100 a*b c*d rate * time = cost", 29],
    ["( and )", "(1) (2) (abc) (done) (yes or no) (1+2) (test)", 29],
    ["- and _", "first-class to-do self-study user_id first_name", 29],
    ["= and +", "1+1=2 2+2=4 5+5=10 10+90=100 x+y=z a=b+c", 30],
    ["Capital letters review", "The Quick Brown Fox Jumps Over The Lazy Dog!", 30],
    ["! in sentences", "Stop! Go now! Run fast! Jump high! Fly free!", 30],
    ["@ in sentences", "Email me at user@mail.com or send@here.net today", 31],
    ["$ in sentences", "Buy 5 books for $25 each; total is $125 today", 31],
    ["Mixed symbols", "The price is $50; buy 3 at 10% off for $45", 31],
    ["Mixed: note #1", "Note #1: rate is 5% or $0.25 per item; great!", 32],
    ["Challenge: email price", "Email: test@mail.com; Price: $99.99; 50% off!", 32],
    ["Challenge: score time", "Score: 95% Time: 3 Rate: 25 per test; $10 off", 32],
    ["Speed Shift", "The First Best Most Pure Fine Kind Bold Fast", 33],
    ["Speed symbols", "!@#$%^&*(); 50% off $100; user@mail.com; +1", 33],
    ["Sentence: goal 100%", "My goal: score 100% on every test this month!", 33],
    ["Sentence: visit site", "Visit site.com; get $25 off; buy 3 for $75!", 34],
    ["Final: classic sentence", "The Quick Brown Fox Jumps Over The Lazy Dog!", 35],
  ]),

  buildSection(13, "Words and Sentences", "الكلمات والجُمل المتقدمة", [], "#10B981", "rgba(16,185,129,0.12)", "🚀", [
    ["Function words", "the and of to in is it that for on with from as", 40],
    ["Common verbs", "have has do does did will would should could can", 40],
    ["Common nouns", "time year people way day man woman child life world", 41],
    ["Articles and prepositions", "a an the in on at by for with from into over", 41],
    ["Question words", "what who when where why how which whose whom", 41],
    ["Common adjectives", "good great nice bad big small long short high low", 42],
    ["Numbers as words", "one two three four five six seven eight nine ten", 42],
    ["Colors", "red blue green black white yellow orange purple gray", 42],
    ["Common phrases", "thank you how are you good morning good night", 43],
    ["Classic sentence", "the quick brown fox jumps over the lazy dog", 43],
    ["Tongue twister", "she sells sea shells by the seashore at low tide", 43],
    ["Famous quote A", "to be or not to be that is the question of life", 44],
    ["Famous quote B", "all that glitters is not gold in this big world", 44],
    ["Proverb A", "the best things in life are free and worth fighting", 44],
    ["Proverb B", "practice makes perfect every single day you try", 45],
    ["Proverb C", "knowledge is power and power is knowledge of truth", 45],
    ["Proverb D", "the early bird catches the worm every single day", 45],
    ["Sentence: time flies", "time flies when you are having a very good time", 46],
    ["Sentence: life is short", "life is short so make every second in it count", 46],
    ["Sentence: journey begins", "every journey begins with a single step forward", 46],
    ["Challenge: fox and hound", "the fox and the hound; beauty and the beast; great", 47],
    ["Challenge: give is better", "to give is better than to receive good gifts", 47],
    ["Challenge: predict future", "the best way to predict the future is to create it", 47],
    ["Challenge: imagination", "imagination is more important than knowledge alone", 48],
    ["Speed: common words", "the and of to in a is that it he was for on are", 48],
    ["Speed: all words flow", "all words and phrases flow fast with practice now", 48],
    ["Sentence: success", "the path to success requires patience and hard work", 49],
    ["Sentence: comfort zone", "great things never come from inside comfort zones", 49],
    ["Sentence: believe", "believe in yourself and all that you are capable of", 49],
    ["Final speed challenge", "the quick brown fox jumps over the lazy sleeping dog", 50],
  ]),
];

let globalId = 1;
for (const section of rawSections) {
  for (const lesson of section.lessons) {
    lesson.id = globalId++;
  }
}

export const sections: Section[] = rawSections;

export const allLessons: Lesson[] = rawSections.flatMap(s => s.lessons);

export const totalLessons = allLessons.length;

export function getLessonById(id: number): Lesson | undefined {
  return allLessons.find(l => l.id === id);
}

export function getNextLesson(lesson: Lesson): Lesson | undefined {
  const idx = allLessons.findIndex(l => l.id === lesson.id);
  return allLessons[idx + 1];
}

export function computeStars(wpm: number, accuracy: number): 1 | 2 | 3 {
  if (wpm >= 50 && accuracy >= 95) return 3;
  if (wpm >= 30 && accuracy >= 90) return 2;
  return 1;
}
