export type FingerColor = "red" | "green" | "blue" | "yellow" | "gray";

export const keyFingerMap: Record<string, FingerColor> = {
  "`": "red", "1": "red", "q": "red", "a": "red", "z": "red",
  "~": "red", "!": "red", "Q": "red", "A": "red", "Z": "red",
  "2": "green", "w": "green", "s": "green", "x": "green",
  "@": "green", "W": "green", "S": "green", "X": "green",
  "3": "blue", "e": "blue", "d": "blue", "c": "blue",
  "#": "blue", "E": "blue", "D": "blue", "C": "blue",
  "4": "yellow", "5": "yellow", "r": "yellow", "t": "yellow",
  "f": "yellow", "g": "yellow", "v": "yellow", "b": "yellow",
  "$": "yellow", "%": "yellow", "R": "yellow", "T": "yellow",
  "F": "yellow", "G": "yellow", "V": "yellow", "B": "yellow",
  "6": "yellow", "7": "yellow", "y": "yellow", "u": "yellow",
  "h": "yellow", "j": "yellow", "n": "yellow", "m": "yellow",
  "^": "yellow", "&": "yellow", "Y": "yellow", "U": "yellow",
  "H": "yellow", "J": "yellow", "N": "yellow", "M": "yellow",
  "8": "blue", "i": "blue", "k": "blue", ",": "blue",
  "*": "blue", "I": "blue", "K": "blue", "<": "blue",
  "9": "green", "o": "green", "l": "green", ".": "green",
  "(": "green", "O": "green", "L": "green", ">": "green",
  "0": "red", "-": "red", "=": "red", "p": "red",
  "[": "red", "]": "red", "\\": "red", ";": "red", "'": "red", "/": "red",
  ")": "red", "_": "red", "+": "red", "P": "red",
  "{": "red", "}": "red", "|": "red", ":": "red", '"': "red", "?": "red",
  " ": "gray",
};

export type Lesson = {
  id: number;
  sectionIndex: number;
  lessonIndex: number;
  title: string;
  text: string;
  targetWpm: number;
  targetAccuracy: number;
};

export type Section = {
  index: number;
  title: string;
  subtitle: string;
  newKeys: string[];
  color: string;
  bgColor: string;
  emoji: string;
  lessons: Lesson[];
};

type RawLesson = [string, string, number?];

function buildSection(
  index: number,
  title: string,
  subtitle: string,
  newKeys: string[],
  color: string,
  bgColor: string,
  emoji: string,
  rawLessons: RawLesson[],
): Section {
  const lessons: Lesson[] = rawLessons.map(([t, text, wpm], li) => ({
    id: 0,
    sectionIndex: index,
    lessonIndex: li,
    title: t,
    text,
    targetWpm: wpm ?? 20 + index * 2,
    targetAccuracy: 90,
  }));
  return { index, title, subtitle, newKeys, color, bgColor, emoji, lessons };
}

const rawSections: Section[] = [
  buildSection(0, "Home Row", "الصف الرئيسي: A S D F G H J K L ;", ["f","j","d","k","s","l","a",";","g","h"], "#F59E0B", "rgba(245,158,11,0.12)", "🏠", [
    ["F and J — the anchor keys", "fff jjj fff jjj fjf jfj ffj jjf fjfj jfjf", 15],
    ["F and J pairs", "fj jf ff jj fj jf fj jf ffjj jjff fjf jfj", 15],
    ["D and K", "ddd kkk ddd kkk dkd kdk ddk kkd dkdk kdkd", 16],
    ["D and K pairs", "dk kd dd kk dk kd dk kd dkdk kdkd ddk kkd", 16],
    ["F D with J K", "fd jk fd jk df kj fd jk fdjk kjdf df kj", 17],
    ["S and L", "sss lll sss lll sls lsl ssl lls slsl lsls", 17],
    ["S and L pairs", "sl ls ss ll sl ls sl ls slsl lsls ssl lls", 17],
    ["F S D with J L K", "fsd jlk fsd jlk sdf lkj fds jkl sdf lkj", 18],
    ["A and ;", "aaa ;;; aaa ;;; a;a ;a; aa;; ;;aa a;a; ;a;a", 18],
    ["Home row — left hand", "fdsa fdsa asdf asdf dfas sadf fdas asdf", 18],
    ["Home row — right hand", "jkl; ;lkj jkl; ;lkj kl;j j;lk jkl; ;lkj", 18],
    ["G and H — index extends", "ggg hhh ggg hhh ghg hgh ggh hhg ghgh hghg", 19],
    ["G and H reach", "fg gh hj fgh ghj jgh fg gh fgh jhg gfh", 19],
    ["Full home row with G H", "asdfghjkl; ;lkjhgfdsa asdfghjkl; ;lkjhgfdsa", 19],
    ["Home row review A", "fdsa jkl; ghj fds jkl; asdf ;lkj gh fj", 19],
    ["Home row review B", "asdfjkl; ;lkjfdsa asdfjkl; ghj gfh jgh", 20],
    ["Word: lad fad sad", "lad lad fad fad sad sad all all dad dad", 20],
    ["Word: ask lass flask", "ask ask lass lass flask flask dad dads ads", 20],
    ["Word: glad flash half", "glad glad flash flash half half fall falls", 20],
    ["Words mix — home row", "lad fad glad flask half lash flash hall flag", 21],
    ["Speed drill — home row", "all flags fall; glad lads; half a flask; ask", 22],
  ]),

  buildSection(1, "E and I", "الحروف E و I", ["e","i"], "#10B981", "rgba(16,185,129,0.12)", "✌️", [
    ["E — the most common letter", "eee eee ee ee eel eel eel fee fee see see", 22],
    ["E reach drill", "dee fee see led eel heel feel seal deal", 22],
    ["E words", "feel feel heel heel seal seal deal deal feed", 22],
    ["I drill", "iii iii ii ii lid lid fig fig did did dig", 23],
    ["I reach drill", "dig dig fig fig kid kid silk silk lid lid", 23],
    ["I words", "idea aide side silk disk kids jade said laid", 23],
    ["E and I together", "feel like file idea side said fail sail isle", 24],
    ["E and I words", "ideal silk deals files feel slide aside eels", 24],
    ["Words: file dial fail", "file dial fail silk disk kids jade slide idea", 25],
    ["Words: dead lead fled", "dead lead fled shed eel deal ideal head led", 25],
    ["Sentence: feel silk", "feel a silk; a jade idea; slide aside; ideal", 26],
    ["Sentence: seal a deal", "seal a deal; a kid slides; ideal silk; she fled", 26],
    ["Sentence: side a file", "side a file; feel like silk; idea fails; deal", 26],
    ["Sentence: she died", "she died; a kid said; jaded lads flee; silk isle", 27],
    ["Challenge: ideal skills", "ideal skills; silk deals fail; jaded ideas flee", 27],
    ["Speed: feel silk side", "feel silk side ideal jade disk file dial slide", 28],
    ["Speed: jaded silk", "jaded silk; ideal fails; eel slides; she fled", 28],
    ["Sentence: silk seals", "silk seals; jade deals; feel like an eel; aside", 29],
    ["Sentence: she fled", "she fled; kids slide; jade eels; ideal silk", 29],
    ["Sentence: silk deals", "silk deals fail; feel aside; a jade idea; eels", 30],
    ["Speed challenge", "jaded kids flee; silk fails; ideal seals; slide", 30],
  ]),

  buildSection(2, "R and U", "الحروف R و U", ["r","u"], "#8B5CF6", "rgba(139,92,246,0.12)", "🎯", [
    ["R drill", "rrr rrr rr rr red red rid rid rule rule fur", 28],
    ["R reach drill", "rr rr fur fur far far her her dear dear dark", 28],
    ["R words", "rule rude ruse rush desk risk dark lark fir", 29],
    ["U drill", "uuu uuu uu uu rug rug fur fur rush rush lure", 29],
    ["U reach drill", "uu uu lure sure dusk rug gush hush rusk rule", 30],
    ["U words", "rule lure sure fuel duel surf flush rusk dusk", 30],
    ["R and U together", "rule ruler rude rush rural ruse sure lure surf", 31],
    ["Words: fire hire dire", "fire hire dire sir her fur rush rule fuel duel", 31],
    ["Words: fear dear hear", "fear dear hear gear laser ruler eraser elder", 32],
    ["Sentence: rule a ruse", "rule a ruse; a dark lark; fear her; sure fire", 33],
    ["Sentence: rush a rule", "rush a rule; sure lads; flush a desk; fuel fire", 33],
    ["Sentence: a dark girl", "a dark girl; rush a ruler; fire aside; sure rule", 33],
    ["Challenge: rush rule", "rush rule rural; fuel drills; dark girls; sure", 34],
    ["Speed: rule rude sure", "rule rude sure fire hire dark lark risk flush", 35],
    ["Speed: rush flush", "rush flush gush hush sure lure dear fear dark", 35],
    ["Sentence: fire a rule", "fire a rule; silk girls; dear sir rushes; sure", 36],
    ["Speed challenge", "sure dark lads; a rural girl; fuel a fire; rush", 36],
    ["Challenge: rural laser", "rural laser ruler eraser dusk rusk surf dark", 37],
    ["Final drill", "fear dear rural girl; sure fire; rule a lark", 37],
  ]),

  buildSection(3, "T and Y", "الحروف T و Y", ["t","y"], "#EF4444", "rgba(239,68,68,0.12)", "⚡", [
    ["T drill", "ttt ttt tt tt try try try the the test test", 34],
    ["T reach drill", "tt tt get set let hit sit kit get set hit", 34],
    ["T words", "test trail steel start still trust trail the", 35],
    ["Y drill", "yyy yyy yy yy yes yes yet yet sky sky dry", 35],
    ["Y reach drill", "yy yy sky dry try fly yes yet style dusty", 36],
    ["Y words", "style study dirty daily truly dusty rusty", 36],
    ["T and Y together", "dirty thirty rusty dusty truly style trust", 37],
    ["Words: try yet yes", "try yet yes sky the get set let hit sit kit", 37],
    ["Words: third their there", "third their there three dirty thirty style", 38],
    ["Sentence: try the trail", "try the trail; a dirty lad; three girls; style", 39],
    ["Sentence: their style", "their style is truly dirty; trust skill; try", 39],
    ["Sentence: start the study", "start the study; a trail leads there; thirty", 40],
    ["Challenge: still their", "yet still their; dirty thirty; trust all; three", 41],
    ["Speed: try yet yes", "try yet yes sky the get set let hit sit kit", 42],
    ["Speed: dirty thirty", "dirty thirty rusty dusty daily truly style", 42],
    ["Sentence: trail leads there", "the trail leads there; yet trust skill; style", 43],
    ["Speed challenge", "study their style; start a dirty trail; thirty", 43],
    ["Challenge: third trail", "the third trail; start a study; truly dirty", 44],
    ["Final drill", "thirty dirty dusty rusty daily style trail try", 44],
  ]),

  buildSection(4, "O and W", "الحروف O و W", ["o","w"], "#06B6D4", "rgba(6,182,212,0.12)", "🌊", [
    ["O drill", "ooo ooo oo oo old old old told told fold fold", 40],
    ["O reach drill", "oo oo fold hold gold sold role sole does goes", 40],
    ["O words", "old told sold fold hold gold role sole does", 41],
    ["W drill", "www www ww ww was word word will wolf work", 41],
    ["W reach drill", "ww ww wolf flow glow show slow grow throw stow", 42],
    ["W words", "wolf flow glow show slow grow throw word work", 42],
    ["O and W together", "word world work lower older other order offer", 43],
    ["Words: old told fold", "old told fold gold role sole does goes toes woes", 43],
    ["Words: word work worry", "word work worry your hour tour four soul folk", 44],
    ["Sentence: the wolf shows", "the wolf shows gold; old folk hold; flow slow", 45],
    ["Sentence: work the story", "work the old story; fold the world; show; grow", 45],
    ["Challenge: world grows", "the world grows; offer others; old story; show", 47],
    ["Challenge: slow flow grows", "slow flow grows; older world offers store; folk", 47],
    ["Speed: old told fold", "old told fold gold sole does goes word world", 48],
    ["Speed: word work world", "word work world story store throw grow wolf", 48],
    ["Sentence: work the gold", "work the old gold; show their role; grow world", 49],
    ["Speed challenge", "the wolf grows old; throw a show; world offers", 49],
    ["Challenge: throw the wolf", "throw the wolf; she shows old gold; role; grow", 50],
    ["Final drill", "word world show grow flow wolf gold fold old", 50],
  ]),

  buildSection(5, "Q and P", "الحروف Q و P", ["q","p"], "#F97316", "rgba(249,115,22,0.12)", "🎪", [
    ["P drill", "ppp ppp pp pp paid pale park part past path", 46],
    ["P reach drill", "pp pp pull pull port post peel peer poet pour", 46],
    ["P words", "paid pale park part past path port post peel", 47],
    ["Q drill", "qqq qqq qq qq query quiet quote quest quit", 47],
    ["Q words", "quite quest quote queasy quit quality queries", 48],
    ["Q and P together", "quite a poet; prior quest; pour a spirit; sport", 48],
    ["Words: tip hip lip sip", "tip hip lip sip rip dip flip slip drip strip", 49],
    ["Words: quite quest quote", "quite quest quote queasy quality spirit split", 50],
    ["Sentence: sport a quest", "sport a prior quest; quite the poet; power", 50],
    ["Sentence: quite powerful", "sport is quite powerful; prayer quest; spirit", 52],
    ["Challenge: quest for quality", "quest for quality; sport pride; quite past", 52],
    ["Speed: sport split pulse", "sport split pulse power pride prior pair paid", 53],
    ["Sentence: quality sport", "quite a quality sport; prior quest; spirit paid", 54],
    ["Speed challenge", "quite the prior sport; spirit quest; paid power", 54],
    ["Final drill", "quest quite sport paid prior spirit power split", 55],
    ["Challenge: prior quality", "prior quality; quite powerful sport; quest paid", 55],
    ["Final challenge", "spirit prayer quite prior; sport quality quest", 56],
  ]),

  buildSection(6, "B and N", "الحروف B و N", ["b","n"], "#EC4899", "rgba(236,72,153,0.12)", "🌟", [
    ["N drill", "nnn nnn nn nn need need note note night north", 52],
    ["N reach drill", "nn nn north nurse noble noise noted nerd nose", 52],
    ["N words", "need note night north noble noise nurse nerd", 53],
    ["B drill", "bbb bbb bb bb born burn band bond bind bend", 53],
    ["B reach drill", "bb bb blue blur bird bind best bent bull boy", 54],
    ["B words", "born burn band bond bind bend bird blue blur", 54],
    ["B and N together", "blend blind blood bring born night nurse noble", 55],
    ["Words: need note night", "need note night north noble nurse nerd noise", 55],
    ["Words: born burn blue", "born burn blue best blend blind blood bring", 56],
    ["Sentence: bird burns bright", "the bird burns bright; blend all four; blood", 57],
    ["Sentence: blue bond night", "bring the blue bond; night north birds; born", 57],
    ["Challenge: blind night", "blind night; noble bond; bring the north bird", 59],
    ["Speed: born burn blue", "born burn blue best bend bird note night north", 60],
    ["Speed: blend blind", "blend blind blood bring north noble nurse born", 60],
    ["Sentence: night bird brings", "the night bird brings blue; bond; noble brand", 60],
    ["Speed challenge", "the night nurse blends blue; burn noble bond", 61],
    ["Final drill", "noble night north blend blind bond born nurse", 61],
    ["Final challenge", "blend bright noble night; burn blue bond bird", 62],
  ]),

  buildSection(7, "V and M", "الحروف V و M", ["v","m"], "#6366F1", "rgba(99,102,241,0.12)", "💎", [
    ["M drill", "mmm mmm mm mm men men mind mind more most", 58],
    ["M reach drill", "mm mm make mark meet more most mother memory", 58],
    ["M words", "mind mine milk mild many make mark meet more", 59],
    ["V drill", "vvv vvv vv vv very view void vote live five", 59],
    ["V reach drill", "vv vv live drive five dive give move love video", 60],
    ["V words", "very view void vote live drive give dive five", 60],
    ["V and M together", "move mind video movie major member memory novel", 61],
    ["Words: men mind mine", "men mind mine milk make mark meet more move", 61],
    ["Words: live drive give", "live drive give dive five love above never ever", 62],
    ["Sentence: move the valve", "move the valve; memory of video; novel; major", 63],
    ["Sentence: seven members", "seven members; video of a movie; give minor", 63],
    ["Challenge: seven minor", "seven minor moves; movie novel; drive value; vim", 65],
    ["Speed: men mind mine", "men mind mine milk make mark move more major", 66],
    ["Speed: live drive give", "live drive give five love above never seven", 66],
    ["Sentence: give major value", "give major value; movie drives love; seven", 66],
    ["Speed challenge", "seven minor moves; give major value; movie love", 67],
    ["Final drill", "move mind video major memory novel minor seven", 67],
    ["Final challenge", "give major value; movie moves; seven members", 68],
  ]),

  buildSection(8, "C", "الحرف C", ["c"], "#14B8A6", "rgba(20,184,166,0.12)", "🌙", [
    ["C drill", "ccc ccc cc cc can can car car cap cap code", 64],
    ["C reach drill", "cc cc cold cold come come code code core care", 64],
    ["C words", "can car cap care card core cool cord cold come", 65],
    ["C blends: cl, cr", "cl cl cr cr sc sc ch ch clean crack close", 65],
    ["C words: city civil", "cold come code city civil child color cover", 65],
    ["C words: clean clear", "clean clear close cloud count court cycle claim", 66],
    ["C words: black block", "black block clock crack track quick trick stick", 66],
    ["C review drill", "care code can cold cover count cycle civil", 66],
    ["Sentence: cool car", "cool car; clean code; black cloud; count cycle", 67],
    ["Sentence: civil court", "count the clock; civil court; clear code; clean", 67],
    ["Sentence: cold cover", "cold cover; black car; cycle the track; civil", 67],
    ["Sentence: quick clean", "quick clean code; cold clock; civil court; count", 68],
    ["Challenge: cold clean code", "cold clean code; city civil court; clock count", 69],
    ["Challenge: black block", "black block; cover the core; clock track; civil", 69],
    ["Speed challenge", "count civil courts; clean cold code; track cycle", 70],
  ]),

  buildSection(9, "X", "الحرف X", ["x"], "#84CC16", "rgba(132,204,22,0.12)", "✖️", [
    ["X drill", "xxx xxx xx xx exit exit next next text text", 68],
    ["X reach drill", "xx xx fix mix six wax tax max lax flex flux", 68],
    ["X words", "exit next text flex flux fox box hex vex fix", 69],
    ["X words: exact extra", "exact extra exist expect export excel relax", 69],
    ["X words: expert extreme", "expert extreme except expand relax vex six", 69],
    ["X blends: ex, ox, ax", "ex ex ex fox fox box box fix fix mix mix wax", 70],
    ["Sentence: exit next", "exit next; exact text; flex the fox; fix six", 70],
    ["Sentence: excel at next", "excel at the next text; fix exact exit; relax", 71],
    ["Sentence: expert relaxes", "expert relax; except expand; extract six; exit", 71],
    ["Sentence: next expert exits", "next expert exits; exact text; fix extra; flex", 71],
    ["Challenge: expert text", "expert text; exact fix; next extra flux; exit", 72],
    ["Speed: exit next text", "exit next text flex flux fox box fix mix six", 73],
    ["Speed challenge", "the next export expert is quite flexible; exit", 74],
  ]),

  buildSection(10, "Z", "الحرف Z", ["z"], "#A78BFA", "rgba(167,139,250,0.12)", "⚡", [
    ["Z drill", "zzz zzz zz zz zip zip zero zero zone zone", 72],
    ["Z reach drill", "zz zz zone zoom zeal zap zest fizz buzz jazz", 72],
    ["Z words", "zero zone zoom zeal zip zap zest fizz buzz", 73],
    ["Z words: pizza quiz", "fizz fuzz buzz jazz pizza quiz prize freeze", 73],
    ["Z words: blaze glaze", "freeze graze blaze glaze haze maze gaze daze", 74],
    ["Z words: crazy dozen", "crazy dozen fuzzy dizzy amaze daze raze size", 74],
    ["Sentence: zero zone", "zero zone; buzz jazz; fizz pizza; zoom in; zeal", 75],
    ["Sentence: jazz and pizza", "jazz and pizza; crazy maze; glaze a prize; zero", 75],
    ["Challenge: jazz quiz", "jazz quiz; prize freeze; crazy daze; buzz zone", 76],
    ["Speed: zero zone zoom", "zero zone zoom zeal zip zap fizz buzz jazz", 77],
    ["Sentence: jazz pizza freezes", "jazz pizza freezes; a crazy fuzzy zone; blaze", 78],
    ["Speed challenge", "zoom the crazy prize; fuzzy jazz pizza; blaze", 78],
    ["Final drill", "zero zone fizz buzz jazz pizza crazy frozen", 79],
  ]),

  buildSection(11, "Numbers", "الأرقام 0-9", ["0","1","2","3","4","5","6","7","8","9"], "#F59E0B", "rgba(245,158,11,0.12)", "🔢", [
    ["1 and 2", "111 222 111 222 12 21 12 21 112 221 12 21", 20],
    ["3 and 4", "333 444 333 444 34 43 34 43 334 443 34 43", 20],
    ["5 and 6", "555 666 555 666 56 65 56 65 556 665 56 65", 20],
    ["7 and 8", "777 888 777 888 78 87 78 87 778 887 78 87", 20],
    ["9 and 0", "999 000 999 000 90 09 90 09 990 009 90 09", 21],
    ["1 through 5", "12345 54321 12345 54321 135 246 135 246", 21],
    ["6 through 0", "67890 09876 67890 09876 680 790 680 790", 21],
    ["All numbers", "1234567890 0987654321 12345 67890 13579 24680", 22],
    ["Number pairs", "11 22 33 44 55 66 77 88 99 00 12 34 56 78 90", 22],
    ["Numbers with letters", "zone 1 code 2 disk 3 file 4 note 5 risk 6", 22],
    ["Phone numbers", "1234 5678 9012 3456 7890 1234 5678 9012", 23],
    ["Years", "2020 2021 2022 2023 2024 2025 2026 2027", 23],
    ["Counts", "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18", 23],
    ["Mixed: room numbers", "room 12 floor 34 unit 56 gate 78 door 90", 24],
    ["Sentence: 5 cats", "the 5 cats drink 10 cups of milk daily at noon", 24],
    ["Sentence: 3 birds fly", "3 birds fly over 7 trees in zone 4 today", 24],
    ["Sentence: 365 days", "2024 is a year of 365 days and 12 months total", 25],
    ["Sentence: score 98", "my score is 98 out of 100 in the final test", 25],
    ["Sentence: buy 3 books", "buy 3 books and 4 pens for 15 students today", 25],
    ["Sentence: code 5872", "the code is 5872; enter room 304; floor 7", 26],
    ["Challenge: 9 numbers", "type 9 numbers now: 12345 and 67890 fast", 26],
    ["Challenge: 1st 2nd 3rd", "write 1st 2nd 3rd 4th 5th 6th 7th 8th results", 26],
    ["Speed: 12 34 56", "12 34 56 78 90 123 456 789 1234 5678 9012", 27],
    ["Speed: all 10 digits", "1234567890 0987654321 11223344 55667788 99", 27],
    ["Challenge: score 97", "a score of 97 in 10 tests gives 970 total points", 27],
    ["Challenge: 5 cats 4 dogs", "5 cats 4 dogs 3 birds 2 fish 1 turtle in zone 6", 28],
    ["Sentence: 8 students", "the 8 students scored 75 80 90 95 and 100 total", 28],
    ["Sentence: zone 4", "zone 4 has 12 streets and 300 buildings today", 28],
    ["Sentence: 50 items", "order 50 items for 25 groups of 8 people by 3", 29],
    ["Speed challenge", "buy 12 of item 456 at 78 of 90 groups by noon", 29],
    ["Math addition", "3 + 4 = 7; 15 + 25 = 40; 100 + 200 = 300 total", 30],
    ["Math subtraction", "10 - 3 = 7; 50 - 25 = 25; 100 - 37 = 63 today", 30],
    ["Math multiplication", "3 * 4 = 12; 5 * 6 = 30; 7 * 8 = 56; 9 * 9 = 81", 30],
    ["Percentages", "50% of 80 is 40; 25% of 120 is 30; 10% of 50", 31],
    ["Addresses", "12 Main St; 345 Park Ave; 67 East Rd; Unit 8", 31],
    ["Phone formats", "call 555-1234 or 800-555-0199 or 888-777-6655", 31],
    ["ZIP codes", "90210 10001 33139 94102 30301 60601 77001 33140", 32],
    ["File sizes", "the file is 1024 bytes or 2048 KB or 3 MB total", 32],
    ["Temperatures", "32 F is 0 C; 212 F is 100 C; body temp is 98 F", 32],
    ["Fractions", "1/2 of 100 is 50; 1/4 of 80 is 20; 3/4 is 75", 33],
    ["Large numbers", "1000 10000 100000 1000000 ten million people now", 33],
    ["Version numbers", "v1.0 v2.1 v3.14 version 10.2.5 release 4.0 here", 33],
    ["Time 24h", "at 14:30 the train leaves; meet at 09:00 for class", 34],
    ["Scores", "the final score is 3-0 at 45 minutes; game 2-2", 34],
    ["Sentence: room 204", "go to room 204; floor 7; call 555-0100 by 3pm", 34],
    ["Sentence: 2 hours", "the 2 hour 30 minute drive covers 150 miles total", 35],
    ["Challenge: all digits fast", "type 1 2 3 4 5 and then 6 7 8 9 0 quickly now", 35],
    ["Challenge: mixed fast", "code 4872 zone 3 floor 9 gate 5 at 12:30 today", 35],
    ["Challenge: math speed", "5+3=8 then 7-4=3 then 6*2=12 then 10/2=5 now", 36],
    ["Speed: digit pairs", "12 23 34 45 56 67 78 89 90 01 13 24 35 46 57", 36],
    ["Speed: 10 to 100", "10 20 30 40 50 60 70 80 90 100 5 15 25 35 45", 36],
    ["Sentence: 5 years", "after 5 years the score is 10 wins and 3 losses", 37],
    ["Sentence: 365 days full", "2025: 365 days 12 months 52 weeks 8760 hours ok", 37],
    ["Final number speed", "the top 10 scores are 98 95 92 89 86 83 80 77 74", 38],
    ["Speed challenge final", "type 1234567890 fast then 0987654321 twice now", 38],
    ["Mastery: mixed all", "room 204 at floor 7; 3 items at $25 each; 9am", 39],
    ["Number mastery", "order 100 items by day 15 at cost of 50 per unit", 39],
    ["Mastery: coordinates", "point at 40.71 north and 74.00 west is zone 7", 40],
    ["Grand total", "add 123 and 456 to get 579; subtract 100 for 479", 40],
    ["Number speed final", "9876543210 then 1234567890 then 5050505050 go", 41],
    ["Number mastery final", "score 99 in test 4 at 09:30 on floor 12 room 7", 41],
  ]),

  buildSection(12, "Shift and Symbols", "Shift والرموز", ["Shift","!","@","#","$","%"], "#EC4899", "rgba(236,72,153,0.12)", "🔡", [
    ["Capital F and J", "FFF JJJ FFF JJJ FfFf JjJj Fff Jjj Fjfj Jfjf", 22],
    ["Capital home row", "Aaa Sss Ddd Fff Jjj Kkk Lll Ggg Hhh Asd", 23],
    ["Capital common words", "The For All And But Nor Yet So Or If As", 24],
    ["Capital names", "Fred Jack Sara Lisa Dave Kate John Jane Bob", 25],
    ["Full capitals", "FAST SLOW STOP GO JUMP RUN FLY SWIM WALK", 25],
    ["Capital sentences", "The Quick Fox Jumps; The Night Is Dark", 26],
    ["! exclamation", "Stop! Go! Run! Jump! Fly! Quick! Yes! No! Wow!", 26],
    ["@ at sign", "user@mail.com send@web.net admin@site.org", 27],
    ["# hash", "note #1 #2 #3 is the #best; #100 top notes", 27],
    ["$ dollar", "buy for $5 $10 $100 $500 and save $25 more", 27],
    ["% percent", "25% off 50% done 75% ready 100% complete", 28],
    ["^ caret", "x^2 y^3 z^4 a^b c^d e^f power^of^2 rise^up", 28],
    ["& ampersand", "fish & chips; salt & pepper; blue & gold; sun & moon", 28],
    ["* asterisk", "5*5=25 10*10=100 a*b c*d rate * time = cost", 29],
    ["( and )", "(1) (2) (abc) (done) (yes or no) (1+2) (test)", 29],
    ["- and _", "first-class to-do self-study user_id first_name", 29],
    ["= and +", "1+1=2 2+2=4 5+5=10 10+90=100 x+y=z a=b+c", 30],
    ["Capital letters review", "The Quick Brown Fox Jumps Over The Lazy Dog!", 30],
    ["! in sentences", "Stop! Go now! Run fast! Jump high! Fly free!", 30],
    ["@ in sentences", "Email me at user@mail.com or send@here.net today", 31],
    ["$ in sentences", "Buy 5 books for $25 each; total is $125 today", 31],
    ["Mixed symbols", "The price is $50; buy 3 at 10% off for $45", 31],
    ["Mixed: note #1", "Note #1: rate is 5% or $0.25 per item; great!", 32],
    ["Challenge: email price", "Email: test@mail.com; Price: $99.99; 50% off!", 32],
    ["Challenge: score time", "Score: 95% Time: 3 Rate: 25 per test; $10 off", 32],
    ["Speed Shift", "The First Best Most Pure Fine Kind Bold Fast", 33],
    ["Speed symbols", "!@#$%^&*(); 50% off $100; user@mail.com; great", 33],
    ["Sentence: goal 100%", "My goal: score 100% on every test this month!", 33],
    ["Sentence: visit site", "Visit site.com; get $25 off; buy 3 for $75!", 34],
    ["Final: classic sentence", "The Quick Brown Fox Jumps Over The Lazy Dog!", 35],
    ["[ and ] brackets", "type [1] [2] [abc] [done] [a+b] [100] now", 35],
    ["{ and } braces", "code { a = 1; b = 2; } and { x = 5; y = 6; }", 35],
    ["| pipe and \\ backslash", "path | grep text; C:\\Users\\Fred; root | admin", 36],
    [": colon and ; semicolon", "key: value; name: Fred; age: 30; city: here;", 36],
    ["' and \" quotes", "it's a dog; she said \"hello\"; I'm here; 'fine'", 36],
    ["< and > angle brackets", "<html> <body> <div> </div> </body> </html>", 37],
    ["? and / slash", "who/what/where/when/why? how? http://site.com/", 37],
    ["Symbols in code", "if (x > 0) { y = x * 2; } else { y = -1; }", 37],
    ["URL typing", "https://www.example.com/path?id=1&key=abc#top", 38],
    ["Code line", "const x = a + b; let y = c - d; return x * y;", 38],
    ["Code if block", "if (score >= 90) { grade = 'A'; } else { 'B'; }", 38],
    ["Email address drill", "send to: admin@firm.org and info@site.net now", 39],
    ["Password pattern", "Pass@123! Key#456$ Salt*789% Hash^012& done", 39],
    ["Mixed shift drill A", "The $50 item sold for 40% off! Buy 3 for $90!", 39],
    ["Mixed shift drill B", "Score: 98% in Test #4 at 9:30am on 2025-01-15", 40],
    ["Mixed shift drill C", "user@host.net; file_name.txt; rate: $0.25/unit!", 40],
    ["Challenge: full symbols", "!@#$% ^&*() -+=_; [] {} |\\: '\"<>? all symbols!", 40],
    ["Challenge: code line fast", "for (i = 0; i < 10; i++) { total += arr[i]; }", 41],
    ["Challenge: URL fast", "http://api.site.com/v2/data?key=abc&fmt=json", 41],
    ["Speed shift drill", "Quick Brown Fox; Stop! Email: x@y.com; $99 off!", 42],
    ["Speed symbols drill", "if (a > b) return a; else if (a < b) return b;", 42],
    ["All symbols review", "Type: !@#$%^&*()-_=+[]{};:'\"<>?,./|\\` fast now", 43],
    ["Capital + symbols", "Send To: Admin@Firm.Org; Rate: $99.99; 50% Off!", 43],
    ["Final symbol challenge", "The Quick Brown Fox Jumps! Score: 100% at 9am!", 44],
    ["Mastery: code style", "const url = 'https://api.com/' + id + '?k=' + key;", 44],
    ["Mastery: full sentence", "Score 100% by typing: Quick! $50 off @noon!", 45],
    ["Grand symbol speed", "user@site.com; $100; 99%; #top; (done); {end}!", 45],
    ["Symbol mastery final", "mix all: !@#$% and &*() then -_+=[];:'\"<>?/\\", 46],
    ["Full keyboard mastery", "The price is $99.99 (50% off)! Email: go@me.org", 46],
    ["Code full line", "function sum(a, b) { return a + b; } sum(3, 4);", 47],
    ["Speed symbol final", "http://abc.com/v1?x=1&y=2; 50% off! $25 each!", 47],
  ]),

  buildSection(13, "Words and Speed", "الكلمات والجُمل المتقدمة", [], "#10B981", "rgba(16,185,129,0.12)", "🚀", [
    ["Function words", "the and of to in is it that for on with from as", 40],
    ["Common verbs", "have has do does did will would should could can", 40],
    ["Common nouns", "time year people way day man woman child life world", 41],
    ["Articles and prepositions", "a an the in on at by for with from into over", 41],
    ["Question words", "what who when where why how which whose whom", 41],
    ["Common adjectives", "good great nice bad big small long short high low", 42],
    ["Numbers as words", "one two three four five six seven eight nine ten", 42],
    ["Colors", "red blue green black white yellow orange purple gray", 42],
    ["Common phrases", "thank you how are you good morning good night", 43],
    ["Classic sentence", "the quick brown fox jumps over the lazy dog", 43],
    ["Tongue twister", "she sells sea shells by the seashore at low tide", 43],
    ["Famous quote A", "to be or not to be that is the question of life", 44],
    ["Famous quote B", "all that glitters is not gold in this big world", 44],
    ["Proverb A", "the best things in life are free and worth fighting", 44],
    ["Proverb B", "practice makes perfect every single day you try", 45],
    ["Proverb C", "knowledge is power and power is knowledge of truth", 45],
    ["Proverb D", "the early bird catches the worm every single day", 45],
    ["Sentence: time flies", "time flies when you are having a very good time", 46],
    ["Sentence: life is short", "life is short so make every second in it count", 46],
    ["Sentence: journey begins", "every journey begins with a single step forward", 46],
    ["Challenge: fox and hound", "the fox and the hound; beauty and the beast; great", 47],
    ["Challenge: give is better", "to give is better than to receive good gifts", 47],
    ["Challenge: predict future", "the best way to predict the future is to create it", 47],
    ["Challenge: imagination", "imagination is more important than knowledge alone", 48],
    ["Speed: common words", "the and of to in a is that it he was for on are", 48],
    ["Speed: all words flow", "all words and phrases flow fast with practice now", 48],
    ["Sentence: success", "the path to success requires patience and hard work", 49],
    ["Sentence: comfort zone", "great things never come from inside comfort zones", 49],
    ["Sentence: believe", "believe in yourself and all that you are capable of", 49],
    ["Final speed challenge", "the quick brown fox jumps over the lazy sleeping dog", 50],
    ["Speed sentence A", "hard work beats talent when talent does not work", 50],
    ["Speed sentence B", "do one thing every day that scares you and grow", 51],
    ["Speed sentence C", "in the middle of every difficulty lies opportunity", 51],
    ["Speed sentence D", "the only way to do great work is to love what you do", 51],
    ["Tech words A", "server client network database query index table", 52],
    ["Tech words B", "function return variable array object class method", 52],
    ["Tech words C", "loop condition boolean integer string pointer node", 52],
    ["Tech sentence A", "the server returns data from the database as json", 53],
    ["Tech sentence B", "create a function that loops over the array values", 53],
    ["Tech sentence C", "store the user object in local storage for later", 53],
    ["Quote: Edison", "genius is one percent inspiration and ninety nine effort", 54],
    ["Quote: Churchill", "success is not final and failure is not fatal at all", 54],
    ["Quote: Einstein", "a person who never made a mistake never tried anything", 54],
    ["Quote: Lincoln", "in the end it is not the years in your life that count", 55],
    ["Paragraph A", "the sun rises every morning to light a new day for us", 55],
    ["Paragraph B", "rivers flow down to the sea but the sea is never full", 55],
    ["Paragraph C", "a smooth sea never made a skilled sailor in any storm", 56],
    ["Paragraph D", "stars cannot shine without darkness so keep going now", 56],
    ["Speed drill A", "type fast and accurate to master the art of typing now", 56],
    ["Speed drill B", "the more you practice the better your fingers will move", 57],
    ["Speed drill C", "every keystroke brings you closer to the speed you need", 57],
    ["Speed drill D", "focus on accuracy first then speed will follow naturally", 57],
    ["Challenge: long sentence A", "learning to type fast is one of the most valuable skills you can develop", 58],
    ["Challenge: long sentence B", "the keyboard is your instrument and you are the musician who brings it to life", 58],
    ["Challenge: long sentence C", "with enough practice you will type without looking at the keys at all soon", 59],
    ["Challenge: pangrams", "the five boxing wizards jump quickly and the brown fox leaps over the lazy hound", 59],
    ["Final speed A", "type the quick brown fox over and over until you reach sixty words per minute", 60],
    ["Final speed B", "success is the sum of small efforts repeated day in and day out without giving up", 60],
    ["Final speed C", "your fingers know the way when your mind is calm and focused on the text ahead", 61],
    ["Master sentence", "to type well you must train your fingers your eyes and your mind to work as one", 62],
    ["Grand speed test", "the journey of a thousand miles begins with a single step and a single keystroke", 63],
    ["Speed mastery A", "fast accurate typing is the goal; practice every day and you will reach it soon", 63],
    ["Speed mastery B", "the quick brown fox jumps over the lazy dog as fast as your fingers can move now", 64],
    ["Grand finale", "you have mastered the keyboard; now type anything with speed accuracy and pride", 65],
  ]),
];

let globalId = 1;
for (const section of rawSections) {
  for (const lesson of section.lessons) {
    lesson.id = globalId++;
  }
}

export const sections: Section[] = rawSections;

export const allLessons: Lesson[] = rawSections.flatMap(s => s.lessons);

export const totalLessons = allLessons.length;

export function getLessonById(id: number): Lesson | undefined {
  return allLessons.find(l => l.id === id);
}

export function getNextLesson(lesson: Lesson): Lesson | undefined {
  const idx = allLessons.findIndex(l => l.id === lesson.id);
  return allLessons[idx + 1];
}

export function computeStars(wpm: number, accuracy: number): 1 | 2 | 3 {
  if (wpm >= 50 && accuracy >= 95) return 3;
  if (wpm >= 30 && accuracy >= 90) return 2;
  return 1;
}
