export type FingerColor = "red" | "green" | "blue" | "yellow" | "gray";

export const keyFingerMap: Record<string, FingerColor> = {
  "`": "red", "1": "red", "q": "red", "a": "red", "z": "red",
  "~": "red", "!": "red", "Q": "red", "A": "red", "Z": "red",
  "2": "green", "w": "green", "s": "green", "x": "green",
  "@": "green", "W": "green", "S": "green", "X": "green",
  "3": "blue", "e": "blue", "d": "blue", "c": "blue",
  "#": "blue", "E": "blue", "D": "blue", "C": "blue",
  "4": "yellow", "5": "yellow", "r": "yellow", "t": "yellow",
  "f": "yellow", "g": "yellow", "v": "yellow", "b": "yellow",
  "$": "yellow", "%": "yellow", "R": "yellow", "T": "yellow",
  "F": "yellow", "G": "yellow", "V": "yellow", "B": "yellow",
  "6": "yellow", "7": "yellow", "y": "yellow", "u": "yellow",
  "h": "yellow", "j": "yellow", "n": "yellow", "m": "yellow",
  "^": "yellow", "&": "yellow", "Y": "yellow", "U": "yellow",
  "H": "yellow", "J": "yellow", "N": "yellow", "M": "yellow",
  "8": "blue", "i": "blue", "k": "blue", ",": "blue",
  "*": "blue", "I": "blue", "K": "blue", "<": "blue",
  "9": "green", "o": "green", "l": "green", ".": "green",
  "(": "green", "O": "green", "L": "green", ">": "green",
  "0": "red", "-": "red", "=": "red", "p": "red",
  "[": "red", "]": "red", "\\": "red", ";": "red", "'": "red", "/": "red",
  ")": "red", "_": "red", "+": "red", "P": "red",
  "{": "red", "}": "red", "|": "red", ":": "red", '"': "red", "?": "red",
  " ": "gray",
};

export type Lesson = {
  id: number;
  sectionIndex: number;
  lessonIndex: number;
  title: string;
  text: string;
  targetWpm: number;
  targetAccuracy: number;
};

export type Section = {
  index: number;
  title: string;
  subtitle: string;
  newKeys: string[];
  color: string;
  bgColor: string;
  emoji: string;
  lessons: Lesson[];
};

type RawLesson = [string, string, number?];

function buildSection(
  index: number,
  title: string,
  subtitle: string,
  newKeys: string[],
  color: string,
  bgColor: string,
  emoji: string,
  rawLessons: RawLesson[],
): Section {
  const lessons: Lesson[] = rawLessons.map(([t, text, wpm], li) => ({
    id: 0,
    sectionIndex: index,
    lessonIndex: li,
    title: t,
    text,
    targetWpm: wpm ?? 20 + index * 2,
    targetAccuracy: 90,
  }));
  return { index, title, subtitle, newKeys, color, bgColor, emoji, lessons };
}

const rawSections: Section[] = [

  buildSection(0, "Home Row", "الصف الرئيسي: A S D F G H J K L ;", ["f","j","d","k","s","l","a",";","g","h"], "#F59E0B", "rgba(245,158,11,0.12)", "🏠", [
    ["F and J — anchor keys", "fff jjj fff jjj fjf jfj ffj jjf fjfj jfjf", 15],
    ["F and J pairs", "fj jf ff jj fj jf fj jf ffjj jjff fjf jfj", 15],
    ["D and K", "ddd kkk ddd kkk dkd kdk ddk kkd dkdk kdkd", 16],
    ["D and K pairs", "dk kd dd kk dk kd dk kd dkdk kdkd ddk kkd", 16],
    ["F D with J K", "fd jk fd jk df kj fd jk fdjk kjdf df kj", 17],
    ["S and L", "sss lll sss lll sls lsl ssl lls slsl lsls", 17],
    ["S and L pairs", "sl ls ss ll sl ls sl ls slsl lsls ssl lls", 17],
    ["F S D with J L K", "fsd jlk fsd jlk sdf lkj fds jkl sdf lkj", 18],
    ["A and semicolon", "aaa ;;; aaa ;;; a;a ;a; aa;; ;;aa a;a; ;a;a", 18],
    ["Home row left hand", "fdsa fdsa asdf asdf dfas sadf fdas asdf", 18],
    ["Home row right hand", "jkl; ;lkj jkl; ;lkj kl;j j;lk jkl; ;lkj", 18],
    ["G and H index extends", "ggg hhh ggg hhh ghg hgh ggh hhg ghgh hghg", 19],
    ["G and H reach", "fg gh hj fgh ghj jgh fg gh fgh jhg gfh", 19],
    ["Full home row", "asdfghjkl; ;lkjhgfdsa asdfghjkl; ;lkjhgfdsa", 19],
    ["Home row review A", "fdsa jkl; ghj fds jkl; asdf ;lkj gh fj", 19],
    ["Home row review B", "asdfjkl; ;lkjfdsa asdfjkl; ghj gfh jgh", 20],
    ["Word: lad fad sad", "lad lad fad fad sad sad all all dad dad", 20],
    ["Word: ask lass flask", "ask ask lass lass flask flask dad dads ads", 20],
    ["Word: glad flash half", "glad glad flash flash half half fall falls", 20],
    ["Words mix home row", "lad fad glad flask half lash flash hall flag", 21],
    ["Speed drill home row", "all flags fall; glad lads; half a flask; ask", 22],
    ["Home row word drill A", "fall halls lass glass flask shall glad lads", 22],
    ["Home row word drill B", "a glad lad; all falls; half a glass; a sad dad", 22],
    ["Home row sentences A", "ask a lass; a glad lad falls; half a flask", 23],
    ["Home row mastery", "all glad lads fall; half glass flask; sad dads", 23],
  ]),

  buildSection(1, "E and I", "الحروف E و I", ["e","i"], "#10B981", "rgba(16,185,129,0.12)", "✌️", [
    ["E drill", "eee eee ee ee eel eel fee fee see see led", 22],
    ["E words", "feel heel seal deal feed led eel flee knee", 22],
    ["I drill", "iii iii ii ii lid lid fig fig did did dig", 23],
    ["I words", "idea aide side silk disk kids jade said laid", 23],
    ["E and I together", "feel like file idea side said fail sail isle", 24],
    ["E and I words", "ideal silk deals files feel slide aside eels", 24],
    ["Words: file dial fail", "file dial fail silk disk kids jade slide idea", 25],
    ["Sentence: feel silk", "feel a silk; a jade idea; slide aside; ideal", 26],
    ["Sentence: seal a deal", "seal a deal; a kid slides; ideal silk; she fled", 26],
    ["Speed: feel silk side", "feel silk side ideal jade disk file dial slide", 28],
    ["Speed challenge", "jaded kids flee; silk fails; ideal seals; slide", 30],
    ["Final drill", "feel ideal silk; jade aside; file dial; slide", 30],
    ["E words: meet feet greet", "meet feet greet sheet steel sleep fleet sleek", 31],
    ["I words: line mine dine", "line mine dine fine wine sine idle igloo inside", 31],
    ["EI together: diesel geese", "diesel geese field siege piece yield relief", 32],
    ["Sentence: she eels", "she sees eels; the geese flee; ideal diesel ride", 32],
    ["EI mastery A", "feel the silk slide; ideal seals; diesel fields", 33],
    ["EI mastery B", "siege relief yields; the field is ideal and free", 33],
    ["EI speed drill A", "she feels free; eels slide aside; field is ideal", 34],
    ["EI final mastery", "the ideal silk field; diesel siege relief; eels", 34],
  ]),

  buildSection(2, "R and U", "الحروف R و U", ["r","u"], "#8B5CF6", "rgba(139,92,246,0.12)", "🎯", [
    ["R drill", "rrr rrr rr rr red red rid rid rule rule fur", 28],
    ["R words", "rule rude ruse rush dark lark fir fur far her", 29],
    ["U drill", "uuu uuu uu uu rug rug fur fur rush rush lure", 29],
    ["U words", "rule lure sure fuel duel surf flush rusk dusk", 30],
    ["R and U together", "rule ruler rude rush rural ruse sure lure surf", 31],
    ["Words: fire hire dear", "fire hire dear fear her fur rush rule fuel", 32],
    ["Sentence: rule a ruse", "rule a ruse; a dark lark; fear her; sure fire", 33],
    ["Sentence: rush a rule", "rush a rule; sure lads; flush a desk; fuel fire", 33],
    ["Speed challenge", "sure dark lads; a rural girl; fuel a fire; rush", 36],
    ["RU words: rural fury", "rural fury usher ruler rustle hurdle purse hurtle", 37],
    ["RU words: pure cure sure", "pure cure sure lure allure secure endure mature", 37],
    ["RU sentence A", "the rural ruler rushes; pure fuel; secure hurdle", 38],
    ["RU sentence B", "endure the rush; pure rural air; a sure fire cure", 38],
    ["RU mastery A", "secure the rural road; pure fuel rush; sure hurdle", 39],
    ["RU final mastery", "the pure ruler endures; rural fury; a sure lure", 39],
  ]),

  buildSection(3, "T and Y", "الحروف T و Y", ["t","y"], "#EF4444", "rgba(239,68,68,0.12)", "⚡", [
    ["T drill", "ttt ttt tt tt try try try the the test test", 34],
    ["T words", "test trail steel start still trust trail the", 35],
    ["Y drill", "yyy yyy yy yy yes yes yet yet sky sky dry", 35],
    ["Y words", "style study dirty daily truly dusty rusty", 36],
    ["T and Y together", "dirty thirty rusty dusty truly style trust", 37],
    ["Words: try yet third", "try yet yes sky third their there three style", 38],
    ["Sentence: try the trail", "try the trail; a dirty lad; three girls; style", 39],
    ["Speed challenge", "study their style; start a dirty trail; thirty", 43],
    ["TY words: treaty", "treaty tasty thirty dusty thirstyesty liberty", 43],
    ["TY words: pretty thirty", "pretty thirty salty tasty dirty rusty safety", 44],
    ["TY sentence A", "their dusty trail is still pretty; try this style", 44],
    ["TY sentence B", "thirty pretty tasty treats; the dirty rusty trail", 45],
    ["TY mastery A", "study the treaty daily; thirty tasty dusty trials", 45],
    ["TY mastery B", "yet they still try; their rusty safety is pretty", 46],
    ["TY final mastery", "the trusty dirty trail is still pretty; try daily", 46],
  ]),

  buildSection(4, "O and W", "الحروف O و W", ["o","w"], "#06B6D4", "rgba(6,182,212,0.12)", "🌊", [
    ["O drill", "ooo ooo oo oo old old old told told fold fold", 40],
    ["O words", "old told sold fold hold gold role sole does goes", 40],
    ["W drill", "www www ww ww was word word will wolf work", 41],
    ["W words", "wolf flow glow show slow grow throw word work", 42],
    ["O and W together", "word world work lower older other order offer", 43],
    ["Words: old told fold", "old told fold gold role sole does goes word", 43],
    ["Sentence: the wolf shows", "the wolf shows gold; old folk hold; flow slow", 45],
    ["Speed challenge", "the wolf grows old; throw a show; world offers", 49],
    ["OW words: follow hollow", "follow hollow swallow borrow sorrow morrow flow", 49],
    ["OW words: widow window", "widow window endow meadow shadow below elbow", 49],
    ["OW sentence A", "the widow follows the slow hollow road below", 50],
    ["OW sentence B", "throw the elbow; follow the shadow; glow below", 50],
    ["OW mastery A", "the world below glows; follow the hollow shadow", 51],
    ["OW mastery B", "borrow the yellow below; swallow slow and hollow", 51],
    ["OW final mastery", "old folk follow; the world glows; throw and flow", 52],
  ]),

  buildSection(5, "Q and P", "الحروف Q و P", ["q","p"], "#F97316", "rgba(249,115,22,0.12)", "🎪", [
    ["P drill", "ppp ppp pp pp paid pale park part past path", 46],
    ["P words", "paid pale park part past path port post peel", 47],
    ["Q drill", "qqq qqq qq qq query quiet quote quest quit", 47],
    ["Q words", "quite quest quote queasy quit quality queries", 48],
    ["Q and P together", "quite a poet; prior quest; pour spirit; sport", 48],
    ["Words: tip hip lip sip", "tip hip lip sip rip dip flip slip drip strip", 49],
    ["Sentence: sport a quest", "sport a prior quest; quite the poet; power", 50],
    ["Speed challenge", "quite the prior sport; spirit quest; paid power", 54],
    ["QP words: unique pique", "unique pique opaque plaque request sequel quip", 54],
    ["QP words: spare spark", "spare spark spiral spiral spoken spire spring", 55],
    ["QP sentence A", "the opaque plaque is quite unique; pique spirit", 55],
    ["QP sentence B", "spare the spirit; unique spark of prior poetry", 55],
    ["QP mastery A", "a quiet poet quips; spare the opaque plaque; quest", 56],
    ["QP final mastery", "quite the unique spirit; pique the plaque; poetry", 56],
  ]),

  buildSection(6, "B and N", "الحروف B و N", ["b","n"], "#EC4899", "rgba(236,72,153,0.12)", "🌟", [
    ["N drill", "nnn nnn nn nn need need note note night north", 52],
    ["N words", "need note night north noble noise nurse nerd", 53],
    ["B drill", "bbb bbb bb bb born burn band bond bind bend", 53],
    ["B words", "born burn band bond bind bend bird blue blur", 54],
    ["B and N together", "blend blind blood bring born night nurse noble", 55],
    ["Words: born burn blue", "born burn blue best blend blind blood bring", 56],
    ["Sentence: blue bond night", "bring the blue bond; night north birds; born", 57],
    ["Speed challenge", "the night nurse blends blue; burn noble bond", 61],
    ["BN words: barnyard nearby", "barnyard nearby neighbor burden burnish beyond", 61],
    ["BN words: abandon abundant", "abandon abundant ribbon ribbon blanket rubber", 62],
    ["BN sentence A", "the neighbor abandoned the barnyard; beyond blue", 62],
    ["BN sentence B", "abundant rubber bands; nearby burden; blind noble", 62],
    ["BN mastery A", "bring the abundant nearby rubber band; burn blend", 63],
    ["BN mastery B", "the noble night nurse brings rubber bonds nearby", 63],
    ["BN final mastery", "beyond the burnished noble band; nearby abundant", 64],
  ]),

  buildSection(7, "V and M", "الحروف V و M", ["v","m"], "#6366F1", "rgba(99,102,241,0.12)", "💎", [
    ["M drill", "mmm mmm mm mm men men mind mind more most", 58],
    ["M words", "mind mine milk mild many make mark meet more", 59],
    ["V drill", "vvv vvv vv vv very view void vote live five", 59],
    ["V words", "very view void vote live drive give dive five", 60],
    ["V and M together", "move mind video movie major member memory novel", 61],
    ["Words: men mind mine", "men mind mine milk make mark meet more move", 61],
    ["Sentence: move the valve", "move the valve; memory of video; novel; major", 63],
    ["Speed challenge", "seven minor moves; give major value; movie love", 67],
    ["VM words: vivid vitamin", "vivid vitamin venom vomit marvel marvel involve", 67],
    ["VM words: maximum minimum", "maximum minimum medium momentum momentum volume", 68],
    ["VM sentence A", "the vivid movie moves the maximum volume valve", 68],
    ["VM sentence B", "involve the minimum members; vivid vitamin marvel", 68],
    ["VM mastery A", "the maximum volume of vivid movies; minimum moves", 69],
    ["VM final mastery", "a vivid minor movie memory; maximum vitamin volume", 69],
  ]),

  buildSection(8, "C", "الحرف C", ["c"], "#14B8A6", "rgba(20,184,166,0.12)", "🌙", [
    ["C drill", "ccc ccc cc cc can can car car cap cap code", 64],
    ["C words", "can car cap care card core cool cord cold come", 65],
    ["C blends cl cr", "cl cl cr cr clean crack close crown city code", 65],
    ["C words clean clear", "clean clear close cloud count court cycle claim", 66],
    ["Sentence: cool car", "cool car; clean code; black cloud; count cycle", 67],
    ["Challenge: cold clean", "cold clean code; city civil court; clock count", 69],
    ["Speed challenge", "count civil courts; clean cold code; track cycle", 70],
    ["Final drill", "can car cap care cold clean close code civil", 71],
    ["C mastery", "cool code; civil clean court; cold cloud cycle", 72],
    ["C words: conceal concept", "conceal concept circle crucial classic crucial", 72],
    ["C sentence A", "the crucial concept conceals a classic circle", 73],
    ["C sentence B", "cool civil code circles; conceal the crucial car", 73],
    ["C final mastery", "crucial civil concepts; clean cold cycle; conceal", 74],
  ]),

  buildSection(9, "X", "الحرف X", ["x"], "#84CC16", "rgba(132,204,22,0.12)", "✖️", [
    ["X drill", "xxx xxx xx xx exit exit next next text text", 68],
    ["X words", "exit next text flex flux fox box hex vex fix", 69],
    ["X words exact extra", "exact extra exist expect export excel relax", 69],
    ["X blends ex ox ax", "ex ex ex fox fox box box fix fix mix mix wax", 70],
    ["Sentence: exit next", "exit next; exact text; flex the fox; fix six", 70],
    ["Sentence: excel at next", "excel at the next text; fix exact exit; relax", 71],
    ["Speed challenge", "the next export expert is quite flexible; exit", 74],
    ["Final drill", "exit next text expert exact expand relax fox", 75],
    ["X mastery", "six foxes flex next exit; exact wax box hex mix", 76],
    ["X sentence A", "expert excel exports; exact text flex; exit box", 76],
    ["X final mastery", "the exact next export excels; flex the fox; relax", 77],
  ]),

  buildSection(10, "Z", "الحرف Z", ["z"], "#A78BFA", "rgba(167,139,250,0.12)", "⚡", [
    ["Z drill", "zzz zzz zz zz zip zip zero zero zone zone", 72],
    ["Z words", "zero zone zoom zeal zip zap zest fizz buzz", 73],
    ["Z words pizza quiz", "fizz fuzz buzz jazz pizza quiz prize freeze", 73],
    ["Z words blaze glaze", "freeze graze blaze glaze haze maze gaze daze", 74],
    ["Sentence: zero zone", "zero zone; buzz jazz; fizz pizza; zoom in; zeal", 75],
    ["Sentence: jazz and pizza", "jazz and pizza; crazy maze; glaze a prize; zero", 75],
    ["Speed challenge", "zoom the crazy prize; fuzzy jazz pizza; blaze", 78],
    ["Final drill", "zero zone fizz buzz jazz pizza crazy frozen", 79],
    ["Z mastery", "a zesty jazz pizza prize; zoom through the maze", 80],
    ["Z sentence A", "the frozen zealot blazes through the hazy zone", 80],
    ["Z final mastery", "blaze and fizz; zeal in zone zero; a pizza prize", 81],
  ]),

  buildSection(11, "Numbers", "الأرقام 0-9", ["0","1","2","3","4","5","6","7","8","9"], "#F59E0B", "rgba(245,158,11,0.12)", "🔢", [
    ["1 and 2", "111 222 111 222 12 21 12 21 112 221 12 21", 20],
    ["3 and 4", "333 444 333 444 34 43 34 43 334 443 34 43", 20],
    ["5 and 6", "555 666 555 666 56 65 56 65 556 665 56 65", 20],
    ["7 and 8", "777 888 777 888 78 87 78 87 778 887 78 87", 20],
    ["9 and 0", "999 000 999 000 90 09 90 09 990 009 90 09", 21],
    ["Odd digits", "13579 97531 13579 135 246 357 468 579 680 791", 21],
    ["Even digits", "24680 08642 24680 246 357 468 579 680 791 802", 21],
    ["1 through 5", "12345 54321 12345 54321 135 246 135 246 12345", 21],
    ["6 through 0", "67890 09876 67890 09876 680 790 680 790 67890", 21],
    ["All 10 digits", "1234567890 0987654321 12345 67890 13579 24680", 22],
    ["Number pairs", "11 22 33 44 55 66 77 88 99 00 12 34 56 78 90", 22],
    ["Number triples", "111 222 333 444 555 666 777 888 999 000 123", 22],
    ["Mixed alpha-numeric", "abc123 def456 ghi789 jkl012 mno345 pqr678", 23],
    ["Phone numbers", "1234 5678 9012 3456 7890 1234 5678 9012 3456", 23],
    ["Years", "2020 2021 2022 2023 2024 2025 2026 2027 2028", 23],
    ["Dates", "01/15 02/28 03/31 04/30 05/15 06/20 07/04 12/31", 23],
    ["Counts 1-20", "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18", 23],
    ["Counts 20-40", "20 21 22 23 24 25 26 27 28 29 30 31 32 33 34", 24],
    ["Room numbers", "room 12 floor 34 unit 56 gate 78 door 90 bin 3", 24],
    ["Sentence: 5 cats", "the 5 cats drink 10 cups of milk daily at noon", 24],
    ["Sentence: 365 days", "2024 is a year of 365 days and 12 months total", 25],
    ["Sentence: score 98", "my score is 98 out of 100 in the final test now", 25],
    ["Sentence: buy 3 books", "buy 3 books and 4 pens for 15 students today", 25],
    ["Sentence: code 5872", "the code is 5872; enter room 304; floor 7 ok", 26],
    ["Math addition", "3+4=7 15+25=40 100+200=300 50+50=100 9+9=18", 27],
    ["Math subtraction", "10-3=7 50-25=25 100-37=63 99-11=88 8-5=3 ok", 28],
    ["Math multiplication", "3*4=12 5*6=30 7*8=56 9*9=81 10*10=100 6*7=42", 28],
    ["Math division", "10/2=5 12/3=4 20/4=5 15/3=5 100/10=10 8/2=4", 28],
    ["Percentages", "50% of 80=40 25% of 120=30 10% of 50=5 75%", 29],
    ["Addresses", "12 Main St; 345 Park Ave; 67 East Rd; Unit 8", 29],
    ["Phone formats", "555-1234 or 800-555-0199 or 888-777-6655 call", 29],
    ["File sizes", "1024 bytes 2048 KB 3 MB 1 GB 500 KB 256 MB", 30],
    ["Temperatures", "32 F=0 C 212 F=100 C body=98 F boiling=100 C", 30],
    ["Time 24h", "at 14:30 train leaves; meet at 09:00 for class", 32],
    ["Scores", "score 3-0 at 45 min; game 2-2 at 90 min go", 32],
    ["Version numbers", "v1.0 v2.1 v3.14 version 10.2.5 release 4.0 ok", 31],
    ["Binary basics", "0 1 10 11 100 101 110 111 1000 1001 1010 1011", 36],
    ["Hex basics", "0x1A 0x2B 0xFF 0xAB 0xCD 0xEF 0x10 0x20 0x30", 36],
    ["Speed burst A", "12 34 56 78 90 11 22 33 44 55 66 77 88 99 00", 38],
    ["Speed burst B", "9 8 7 6 5 4 3 2 1 0 0 1 2 3 4 5 6 7 8 9 again", 38],
    ["Number speed final A", "1234567890 0987654321 1357924680 2468013579", 40],
    ["Number speed final B", "type 100 digits: 1234 5678 9012 3456 7890 fast", 40],
    ["Mixed drill A", "call 800-555-1234 at 9am; room 702; floor 15", 41],
    ["Mixed drill B", "order 250 units by June 15 at $4.99; save 5%", 41],
    ["Number paragraph A", "in 2024: 12 months 52 weeks 365 days 8760 hours", 42],
    ["Number paragraph B", "team of 8 scored 10 9 8 7 6 5 in 6 games total", 42],
    ["Speed finale A", "100 200 300 400 500 600 700 800 900 1000 done", 43],
    ["Speed mastery A", "9876543210 then 1234567890 then 5050505050 fast", 44],
    ["Number mastery final", "master all digits 0-9 in every combination fast", 45],
    ["Grand number finale", "room 204 floor 7; 3 items at $25 each; 9am done", 46],
    ["Ultimate number speed", "1 2 3 4 5 6 7 8 9 0 back 0 9 8 7 6 5 4 3 2 1", 48],
    ["Numbers complete", "all digits mastered: count measure calculate done", 50],
    ["Statistics A", "average of 10 20 30 40 50 = 30; median = 30 ok", 38],
    ["Statistics B", "25% scored above 90; 50% above 75; 10% below 60", 38],
    ["Coordinates A", "point (3, 4); line from (0,0) to (5,5); origin ok", 39],
    ["Coordinates B", "latitude 25.2N longitude 55.3E; zone 7 grid B3", 39],
    ["Distance A", "5 km = 5000 m; 1 mile = 1.6 km; 100 yd = 91 m", 39],
    ["Distance B", "city A to B is 250 km; drive 4 hrs at 60 km/h", 39],
    ["Weight A", "1 kg = 1000 g; 2.2 lb = 1 kg; 500 g = 0.5 kg", 40],
    ["Volume A", "1 L = 1000 mL; 1 gal = 3.8 L; 250 mL half cup", 40],
    ["Speed A", "60 km/h = 16.7 m/s; 100 mph = 160 km/h; 0.1 c", 40],
    ["Area A", "square 5x5=25; rectangle 4x6=24; circle r=3 area=28", 40],
    ["Fraction A", "1/2 + 1/4 = 3/4; 2/3 + 1/6 = 5/6; 3/8 + 5/8 = 1", 41],
    ["Fraction B", "1/2 * 2/3 = 1/3; 3/4 / 1/2 = 3/2; 5/6 - 1/3 = 1/2", 41],
    ["Decimal A", "0.25 + 0.75 = 1.0; 3.14 * 2 = 6.28; 9.99 - 4.99 = 5", 41],
    ["Decimal B", "0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 easy", 41],
    ["Roman numerals", "I II III IV V VI VII VIII IX X L C D M easy", 42],
    ["Powers A", "2^10=1024 2^8=256 2^4=16 2^2=4 10^2=100 ok", 42],
    ["Square roots", "sqrt(4)=2 sqrt(9)=3 sqrt(16)=4 sqrt(25)=5 ok", 42],
    ["Scientific notation", "1.5e3=1500 2.5e6=2500000 3.0e-2=0.03 ok fast", 42],
    ["Time zones", "UTC+3 is 3h ahead; UTC-5 is 5h behind; UTC+0 = GMT", 43],
    ["Calories A", "apple=95 kcal banana=89 kcal bread=80 kcal per slice", 43],
    ["Interest A", "simple interest: P*R*T/100; P=1000 R=5% T=2 = 100", 43],
    ["Compound interest", "A = P(1+r/n)^nt; 1000 at 5% for 2 yrs = 1102.50", 43],
    ["Tax A", "price $200 + 15% tax = $230; VAT on $50 at 10% = $5", 44],
    ["Discount A", "was $80 now 25% off = $60; save $20 on every item", 44],
    ["Salary A", "monthly salary $3000; annual = $36000; daily = $100", 44],
    ["Speed test A", "12 34 56 78 90 at 45 wpm; next target: 55 wpm fast", 44],
    ["Speed test B", "100 items at $2.50 each = $250; 20% off = $200 final", 44],
    ["Historical dates A", "1776 independence 1789 revolution 1865 civil war end", 45],
    ["Historical dates B", "1903 first flight 1945 WWII end 1969 moon landing ok", 45],
    ["Sports scores A", "final: 3-0 at 90 min; half-time: 1-0; extra: 3-2", 45],
    ["Sports scores B", "team A: 24 pts 8 wins 2 losses; team B: 18 pts 6w", 45],
    ["Population A", "world: 8 billion; china: 1.4B; india: 1.4B; usa: 330M", 45],
    ["Population B", "city pop: NY 8M; LA 4M; Chicago 2.7M; Houston 2.3M", 46],
    ["Budget A", "income $5000; rent $1500; food $600; other $900 ok", 46],
    ["Budget B", "save 20% of $4000 = $800/month; annual savings $9600", 46],
    ["Grades A", "A=90-100 B=80-89 C=70-79 D=60-69 F below 60 ok", 46],
    ["Grades B", "GPA: A=4.0 B=3.0 C=2.0 D=1.0 F=0.0; avg=3.5 ok", 46],
    ["Weather A", "temp 25C humidity 60% wind 15 km/h UV index 6 ok", 47],
    ["Weather B", "max 38C min 22C average 30C rain 5mm pressure 1010", 47],
    ["Recipe A", "2 cups flour 1 cup sugar 3 eggs 0.5 cup butter ok", 47],
    ["Recipe B", "bake at 180C for 35 min; serves 8; 250 kcal each", 47],
    ["Speed: final A", "1 + 2 = 3; 4 * 5 = 20; 100 / 4 = 25; 7 - 3 = 4", 48],
    ["Speed: final B", "pi = 3.14159; e = 2.71828; phi = 1.61803 constants", 48],
    ["Speed: final C", "1000 / 8 = 125; 256 * 4 = 1024; 3^3 = 27; 4^2 = 16", 48],
    ["Speed: final D", "item 1: $12.99 item 2: $8.49 total: $21.48 ok done", 49],
    ["Speed: final E", "rank 1 score 99; rank 2 score 97; rank 3 score 95", 49],
    ["Numbers grand A", "all digits mastered: 0 1 2 3 4 5 6 7 8 9 perfectly", 50],
    ["Numbers grand B", "math science dates and more: numbers are everywhere", 50],
    ["Numbers grand final", "from 0 to infinity: numbers are the language of all", 51],
  ]),

  buildSection(12, "Shift and Symbols", "Shift والرموز", ["Shift","!","@","#","$","%"], "#EC4899", "rgba(236,72,153,0.12)", "🔡", [
    ["Capital F and J", "FFF JJJ FFF JJJ FfFf JjJj Fff Jjj Fjfj Jfjf", 22],
    ["Capital home row", "Aaa Sss Ddd Fff Jjj Kkk Lll Ggg Hhh Asd", 23],
    ["Capital common words", "The For All And But Nor Yet So Or If As", 24],
    ["Capital names", "Fred Jack Sara Lisa Dave Kate John Jane Bob", 25],
    ["Full capitals", "FAST SLOW STOP GO JUMP RUN FLY SWIM WALK", 25],
    ["Shift top row E I", "Eel Isle Idea File Silk Feel Jade Dial Side", 26],
    ["Shift R U words", "Rule Rush Sure Lure Fuel Dark Rural Fire", 26],
    ["Shift T Y words", "Trail Style Trust Study Thirty Dirty Rusty", 27],
    ["Shift O W words", "World Work Wolf Flow Gold Old Show Grow", 27],
    ["Exclamation mark", "Stop! Go! Run! Jump! Fly! Quick! Yes! No! Wow!", 26],
    ["At sign", "user@mail.com send@web.net admin@site.org", 27],
    ["Hash number", "note #1 #2 #3 is the #best; #100 top notes", 27],
    ["Dollar sign", "buy for $5 $10 $100 $500 and save $25 more", 27],
    ["Percent", "25% off 50% done 75% ready 100% complete done", 28],
    ["Caret", "x^2 y^3 z^4 a^b c^d e^f power^of^2 rise^up", 28],
    ["Ampersand", "fish & chips; salt & pepper; blue & gold fast", 28],
    ["Asterisk", "5*5=25 10*10=100 a*b c*d rate*time=cost ok", 29],
    ["Parentheses", "(1) (2) (abc) (done) (yes or no) (1+2) (test)", 29],
    ["Hyphen underscore", "first-class to-do self-study user_id name_key", 29],
    ["Equals plus", "1+1=2 2+2=4 5+5=10 10+90=100 x+y=z a=b+c ok", 30],
    ["Capital sentences A", "The Quick Fox Jumps; The Night Is Dark Now", 30],
    ["Capital sentences B", "Stop! Great! Amazing! Perfect! Well Done! Go!", 30],
    ["At in sentences", "Email me at user@mail.com or send@here.net ok", 31],
    ["Dollar in sentences", "Buy 5 books for $25 each; total is $125 today", 31],
    ["Mixed percent dollar", "The price is $50; buy 3 at 10% off for $45", 31],
    ["Note hash pattern", "Note #1: rate is 5% or $0.25 per item; great!", 32],
    ["Email and price", "Email: test@mail.com; Price: $99.99; 50% off!", 32],
    ["Score and rate", "Score: 95% Time: 3 Rate: 25 per test; $10 off", 32],
    ["Square brackets", "type [1] [2] [abc] [done] [a+b] [100] now ok", 33],
    ["Curly braces", "code { a=1; b=2; } and { x=5; y=6; } done", 33],
    ["Pipe backslash", "path|grep txt; C:\\Users\\Fred; root|admin text", 34],
    ["Colon semicolon", "key: value; name: Fred; age: 30; city: here;", 34],
    ["Single double quotes", "it's a dog; she said \"hello\"; I'm here now", 34],
    ["Angle brackets", "<html> <body> <div> </div> </body> </html>", 35],
    ["Question slash", "who/what/where/when/why? how? http://site.com/", 35],
    ["Code if block", "if (x > 0) { y = x * 2; } else { y = -1; }", 35],
    ["URL pattern", "https://www.example.com/path?id=1&key=abc#top", 36],
    ["Code const", "const x = a + b; let y = c - d; return x * y;", 36],
    ["Code if grade", "if (score >= 90) { grade = 'A'; } else { 'B'; }", 36],
    ["Email address A", "send to: admin@firm.org and info@site.net now", 37],
    ["Password pattern", "Pass@123! Key#456$ Salt*789% Hash^012& done", 37],
    ["Mixed shift A", "The $50 item sold 40% off! Buy 3 for $90 ok!", 37],
    ["Mixed shift B", "Score: 98% Test #4 at 9:30am on 2025-01-15 ok", 38],
    ["Mixed shift C", "user@host.net; file_name.txt; rate: $0.25/unit!", 38],
    ["Code for loop", "for (i = 0; i < 10; i++) { total += arr[i]; }", 38],
    ["URL complex", "http://api.site.com/v2/data?key=abc&fmt=json ok", 39],
    ["Speed shift A", "The First Best Most Pure Fine Kind Bold Fast", 39],
    ["Speed symbols A", "!@#$%^&*(); 50% off $100; user@mail.com; great", 39],
    ["Capital + symbols", "Send To: Admin@Firm.Org; Rate: $99.99; 50% Off!", 40],
    ["My goal sentence", "My goal: score 100% on every test this month!", 40],
    ["Classic capital", "The Quick Brown Fox Jumps Over The Lazy Dog!", 41],
    ["Code function", "function sum(a, b) { return a + b; } sum(3, 4);", 41],
    ["Speed symbols B", "if (a > b) return a; else if (a < b) return b;", 41],
    ["All symbols A", "!@#$%^&*()-_=+[]{};:'\"<>?,./|\\ type all fast", 42],
    ["Mixed email price", "user@site.com; $100; 99%; #top; (done); {end}!", 43],
    ["Symbol mastery A", "mix all: !@#$% and &*() then -_+=[];:'\"<>?/\\", 43],
    ["Full keyboard A", "The price is $99.99 (50% off)! Email: go@me.org", 44],
    ["Full keyboard B", "http://abc.com/v1?x=1&y=2; 50% off! $25 each!", 45],
    ["Shift speed A", "Quick Brown Fox; Stop! Email: x@y.com; $99 off!", 45],
    ["Shift speed B", "It's a $50 deal at 25% off; call: user@here.net!", 46],
    ["Code mastery A", "const arr = [1,2,3]; arr.map(x => x*2); done;", 46],
    ["Code mastery B", "let obj = {a:1, b:2}; Object.keys(obj).length;", 47],
    ["Symbol speed A", "!@#$% ^&*()_+ []{}|\\ :;'\"<>?,./` all symbols", 47],
    ["Symbol speed B", "Email: abc@def.com; Pass: Xyz@123!; 100% done!", 48],
    ["Code mastery C", "for (let i=0; i<arr.length; i++) { sum+=arr[i]; }", 48],
    ["URL mastery", "https://api.example.com/v2/users?id=42&fmt=json", 49],
    ["Code mastery D", "try { fetch(url); } catch (e) { console.log(e); }", 49],
    ["Code mastery E", "class Foo { bar() { return this.x + this.y; } }", 50],
    ["Symbol paragraph A", "buy 3 items at $9.99 (30% off); email: a@b.com!", 50],
    ["Symbol paragraph B", "score: 98% in test #5; goal: 100%; rate: $0.50!", 51],
    ["Symbols speed A", "!@#$%^&*() at user@host.org; $99.99; 50% off", 51],
    ["Symbols mastery grand", "the master typist hits every symbol fast and true", 52],
    ["Symbol burst A", "!!! @@@ ### $$$ %%% ^^^ &&& *** ((( ))) symbols", 52],
    ["Mixed speed A", "user@site.net; pass: Abc@123!; score: 99%; go", 53],
    ["Mixed speed B", "if (a != b && c || d) { return !flag; } done ok", 53],
    ["Code drill A", "const obj = {key: 'val', num: 42, ok: true};", 54],
    ["Code drill B", "arr.filter(x => x > 0).map(x => x*2).join(',');", 54],
    ["Symbol paragraph C", "score: 98% in test #5; goal: 100%; $0.50 each!", 55],
    ["Grand symbol challenge", "The Quick Fox! score=100 at user@test.com today", 55],
    ["Symbol mastery final A", "type: !@#$%^&*()-+=[]{}|;:'\",.<>?/\\ perfectly", 56],
    ["Symbol mastery final B", "The $99 sale (50% off) ends tonight at 11:59pm!", 57],
    ["Ultimate symbol speed", "Send: info@abc.org; Price: $49.99; Rate: 30%;", 57],
    ["Mixed speed C", "https://api.io/v3?x=1&y=2#top at $0.99 each ok", 58],
    ["Mixed speed D", "Score 100% by typing: Quick! $50 off @noon now", 58],
    ["Symbol paragraph D", "user@site.com; $100; 99%; #top; (done); {end}!", 58],
    ["Code drill C", "class Bar extends Foo { get value() { return 0; } }", 59],
    ["Symbol final speed", "master: !@#$%^&*()-_+=[]{}|;:'\",.<>?/\\ all fast", 59],
    ["Grand finale symbols", "Quick Fox! $99 deal: admin@firm.org; 100% speed", 60],
    ["Symbols complete", "all symbols mastered with speed and accuracy done!", 60],
  ]),

  buildSection(13, "Advanced Speed Training", "تدريب السرعة المتقدم — فقرات وجُمل متنوعة", [], "#10B981", "rgba(16,185,129,0.12)", "🚀", [
    ["The Sun", "the sun is a star at the center of our solar system", 40],
    ["The Moon", "the moon orbits the earth every twenty nine days", 40],
    ["The Ocean", "the ocean covers more than two thirds of the earth", 40],
    ["The Mountain", "mountains are formed by the movement of tectonic plates", 40],
    ["The Forest", "forests are home to more than half of all animal species", 41],
    ["The Desert", "deserts receive less than ten inches of rain per year", 41],
    ["The River", "rivers carry fresh water from mountains to the sea", 41],
    ["The Lake", "lakes are bodies of fresh water surrounded by land", 41],
    ["The Sky", "the sky appears blue because of the scattering of light", 42],
    ["The Rain", "rain forms when water vapor cools and falls as drops", 42],
    ["Morning Light", "the first light of morning brings a new chance to start", 42],
    ["Evening Star", "the first star appears as the evening sky grows dark", 42],
    ["Spring Begins", "spring brings warm days and new growth after winter", 42],
    ["Summer Heat", "summer days are long and warm with bright blue skies", 43],
    ["Autumn Leaves", "autumn leaves turn red and gold before they fall down", 43],
    ["Winter Snow", "winter snow covers the ground with a blanket of white", 43],
    ["April Rain", "april showers bring the flowers that bloom in may", 43],
    ["Night Sky", "on clear nights the sky is full of bright shining stars", 44],
    ["Wind and Waves", "wind moves the surface of the sea into rolling waves", 44],
    ["Ice and Snow", "ice forms when water freezes at zero degrees celsius", 44],
    ["Fire and Heat", "fire produces heat and light through rapid oxidation", 44],
    ["Earth and Soil", "soil is made of minerals water air and organic matter", 44],
    ["Fresh Water", "fresh water is one of the most precious gifts on earth", 45],
    ["Clean Air", "clean air is essential for the health of all living things", 45],
    ["The Seasons", "the four seasons are spring summer autumn and winter", 45],
    ["Day and Night", "the earth rotates on its axis creating day and night", 45],
    ["Mountains A", "the highest mountain on earth is mount everest in asia", 45],
    ["Rivers A", "the nile is the longest river in the world in africa", 46],
    ["Oceans A", "the pacific ocean is the largest ocean on our planet", 46],
    ["Continents", "earth has seven continents and five major oceans today", 46],
    ["Animals A", "animals need food water shelter and space to survive well", 46],
    ["Birds A", "birds are the only animals with feathers on their bodies", 47],
    ["Fish A", "fish breathe through gills and use fins to swim in water", 47],
    ["Insects A", "insects have six legs and three body parts at all times", 47],
    ["Trees A", "trees provide oxygen shelter food and beauty for the world", 47],
    ["Flowers A", "flowers attract bees and butterflies with their bright colors", 47],
    ["Grass A", "grass covers more land on earth than any other plant does", 48],
    ["The Sea A", "the sea is full of life from the surface to the deep floor", 48],
    ["Clouds A", "clouds are made of tiny water droplets suspended in the air", 48],
    ["Sand A", "sand is made of tiny grains of rock and mineral particles", 48],
    ["Gold A", "gold is a precious metal that has been valued for thousands of years", 48],
    ["Iron A", "iron is the most abundant metal on earth by total mass", 49],
    ["Wood A", "wood has been used by humans for building and fuel for ages", 49],
    ["Stone A", "stone is one of the oldest building materials known to man", 49],
    ["Glass A", "glass is made by melting sand at very high temperatures now", 49],
    ["Paper A", "paper was invented in china and changed the way we share ideas", 50],
    ["Bread A", "bread is made from flour water and yeast and has fed people", 50],
    ["Milk A", "milk is a rich source of calcium protein and vitamins for us", 50],
    ["Water A", "water is essential for life and covers most of the planet", 50],
    ["The Sun B", "the sun provides the energy that drives all life on earth", 50],
    ["Practice makes perfect", "practice makes perfect every single day you try hard", 50],
    ["The early bird", "the early bird catches the worm so wake up and start now", 51],
    ["A stitch in time", "a stitch in time saves nine and keeps things in good order", 51],
    ["Actions speak louder", "actions speak louder than words in every situation always", 51],
    ["Better late than never", "it is better to arrive late than to never arrive at all", 51],
    ["Every cloud", "every cloud has a silver lining if you look for it well", 51],
    ["Knowledge is power", "knowledge is power and power opens every door in your life", 52],
    ["Time is precious", "time is the most precious thing you have so use it wisely", 52],
    ["Hard work pays", "hard work and dedication always pay off in the end for you", 52],
    ["Patience wins", "patience and persistence will always win over speed alone", 52],
    ["Learn from mistakes", "the best lessons in life come from the mistakes you make", 52],
    ["Think before you speak", "always think before you speak so your words carry real weight", 53],
    ["The pen is mightier", "the pen is mightier than the sword in any age of history", 53],
    ["Do unto others", "do unto others as you would have them do unto you always", 53],
    ["Look before you leap", "always look before you leap or you may regret it later", 53],
    ["Two heads are better", "two heads are better than one when solving hard problems", 53],
    ["Honesty is best", "honesty is always the best policy in all of your affairs", 54],
    ["Fortune favors", "fortune favors the bold and the brave who dare to try", 54],
    ["Slow and steady", "slow and steady wins the race every single time you try", 54],
    ["Rome was not built", "rome was not built in a single day and neither is success", 54],
    ["A journey begins", "every journey of a thousand miles begins with one single step", 54],
    ["Be the change", "be the change that you wish to see in the world around you", 55],
    ["In the beginning", "in the beginning there was nothing and then there was light", 55],
    ["The road not taken", "two roads diverged in a wood and i took the one less traveled", 55],
    ["All that glitters", "all that glitters is not gold as the old saying reminds us", 55],
    ["It was the best of times", "it was the best of times it was the worst of times ever", 55],
    ["To be or not to be", "to be or not to be that is the question in all of our lives", 56],
    ["Call me Ishmael", "some years ago I thought I would sail about and see the world", 56],
    ["It is a truth", "it is a truth universally acknowledged that success takes time", 56],
    ["We hold these truths", "we hold these truths to be self evident and deeply important", 56],
    ["Ask not what", "ask not what your country can do for you but what you can do", 56],
    ["I have a dream", "I have a dream that one day all people will live as equals", 57],
    ["The only thing to fear", "the only thing we have to fear is fear itself not failure", 57],
    ["Give me liberty", "give me liberty or give me death for freedom matters most", 57],
    ["Four score", "four score and seven years ago our fathers set this nation free", 57],
    ["That government", "that government of the people by the people shall not perish", 57],
    ["Science and nature A", "the human body is made of about thirty seven trillion cells now", 58],
    ["Science and nature B", "the speed of light is nearly three hundred thousand km per sec", 58],
    ["Science and nature C", "gravity is the force that pulls all objects toward the earth", 58],
    ["Science and nature D", "plants make their food through the process of photosynthesis", 58],
    ["Science and nature E", "the brain controls all of the functions of the human body", 58],
    ["Chemistry A", "atoms are the smallest unit of matter that has all element traits", 59],
    ["Chemistry B", "water is made of two hydrogen atoms and one oxygen atom bonded", 59],
    ["Chemistry C", "the periodic table lists all of the known chemical elements now", 59],
    ["Biology A", "dna carries the genetic information for all living organisms", 59],
    ["Biology B", "evolution explains how species change and adapt over long time", 59],
    ["Astronomy A", "our solar system has eight planets orbiting around our sun now", 60],
    ["Astronomy B", "the milky way galaxy contains billions of stars like our sun", 60],
    ["Astronomy C", "a light year is the distance light travels in one full year", 60],
    ["Astronomy D", "black holes are regions of space where gravity is so strong", 60],
    ["Physics A", "energy cannot be created or destroyed only transformed to new forms", 60],
    ["Physics B", "for every action there is an equal and opposite reaction always", 61],
    ["Geology A", "the earth is made of four layers the crust mantle and two cores", 61],
    ["Geology B", "volcanoes form where tectonic plates meet and magma pushes up", 61],
    ["Medicine A", "vaccines train the immune system to fight specific infections", 61],
    ["Medicine B", "the heart pumps blood through the body about seventy times per minute", 61],
    ["History A", "ancient egypt was one of the great civilizations of the old world", 62],
    ["History B", "the roman empire at its height covered much of europe and beyond", 62],
    ["History C", "the printing press changed the way knowledge was shared globally", 62],
    ["History D", "the industrial revolution transformed society in the eighteenth century", 62],
    ["History E", "world war two ended in nineteen forty five with allied victory", 62],
    ["Geography A", "the amazon rainforest is the largest tropical forest on earth", 63],
    ["Geography B", "the sahara desert is the largest hot desert in all of africa", 63],
    ["Geography C", "mount everest in the himalayas is the world's highest mountain", 63],
    ["Geography D", "the amazon river in south america carries more water than any other", 63],
    ["Geography E", "the great barrier reef off australia is the largest coral reef", 63],
    ["Technology A", "the internet connects billions of devices and people worldwide", 64],
    ["Technology B", "smartphones have changed the way we communicate work and learn", 64],
    ["Technology C", "artificial intelligence is transforming every field of human work", 64],
    ["Technology D", "electric cars use batteries instead of gasoline to run their motors", 64],
    ["Technology E", "renewable energy from sun and wind is growing faster each year", 64],
    ["Computing A", "a computer processes data using billions of operations per second", 65],
    ["Computing B", "the first electronic computer was built in the nineteen forties era", 65],
    ["Computing C", "software is the set of instructions that tells hardware what to do", 65],
    ["Computing D", "cloud computing allows data to be stored and accessed from anywhere", 65],
    ["Computing E", "cybersecurity protects computers and networks from harmful attacks", 65],
    ["Culture A", "music is a universal language that connects people across all borders", 66],
    ["Culture B", "literature preserves the stories values and dreams of human culture", 66],
    ["Culture C", "art allows people to express ideas and emotions that words cannot", 66],
    ["Culture D", "film tells stories through moving images and has changed our world", 66],
    ["Culture E", "architecture shapes the spaces in which human life is fully lived", 66],
    ["Sports A", "the olympic games bring athletes from every nation together to compete", 67],
    ["Sports B", "football is the most popular sport in almost every part of the world", 67],
    ["Sports C", "swimming is one of the best exercises for the entire human body", 67],
    ["Sports D", "running improves cardiovascular health and builds endurance over time", 67],
    ["Sports E", "team sports teach cooperation trust and communication to all players", 67],
    ["Food A", "the mediterranean diet is widely considered one of the healthiest", 68],
    ["Food B", "cooking at home is healthier and more affordable than eating out often", 68],
    ["Food C", "fruits and vegetables contain vitamins minerals and dietary fiber", 68],
    ["Food D", "protein is essential for building and repairing tissues in the body", 68],
    ["Food E", "staying hydrated by drinking water is vital for all bodily functions", 68],
    ["Business A", "entrepreneurship involves starting and running a business from scratch", 69],
    ["Business B", "innovation drives economic growth by creating new products and services", 69],
    ["Business C", "global trade allows countries to exchange goods and services freely", 69],
    ["Business D", "a budget helps individuals and organizations plan and control spending", 69],
    ["Business E", "investing early allows compound interest to grow wealth over decades", 69],
    ["Education A", "education is the most powerful tool for changing the world for good", 70],
    ["Education B", "reading regularly expands vocabulary knowledge and critical thinking", 70],
    ["Education C", "mathematics teaches logical reasoning and problem solving every day", 70],
    ["Education D", "learning a second language opens new doors and expands your world", 70],
    ["Education E", "curiosity and a love of learning are the foundation of all success", 70],
    ["Health A", "regular exercise reduces the risk of many chronic diseases over time", 71],
    ["Health B", "sleep is essential for memory consolidation and physical recovery", 71],
    ["Health C", "stress management through meditation and exercise improves well-being", 71],
    ["Health D", "a balanced diet combined with exercise is key to long-term health", 71],
    ["Health E", "mental health is just as important as physical health for full life", 71],
    ["Environment A", "climate change is caused by greenhouse gases from human activities", 72],
    ["Environment B", "recycling reduces waste and conserves the resources of our planet", 72],
    ["Environment C", "deforestation threatens biodiversity and accelerates climate change", 72],
    ["Environment D", "protecting the ocean is vital for the health of the entire planet", 72],
    ["Environment E", "renewable energy can replace fossil fuels and reduce pollution fast", 72],
    ["Space A", "astronauts train for years before traveling to the space station", 73],
    ["Space B", "mars is the most likely next destination for human space explorers", 73],
    ["Space C", "satellites orbiting earth help us navigate communicate and forecast", 73],
    ["Space D", "the james webb telescope can see galaxies billions of light years away", 73],
    ["Space E", "space exploration has led to many technologies we use in daily life", 73],
    ["Speed group A1", "type each word clearly and accurately to build your speed over time", 74],
    ["Speed group A2", "focus on accuracy first and your speed will naturally improve soon", 74],
    ["Speed group A3", "keep your eyes on the text and let your fingers find the keys", 74],
    ["Speed group A4", "the more you practice the more comfortable your fingers will feel", 74],
    ["Speed group A5", "typing without looking at the keys is called touch typing always", 74],
    ["Speed group B1", "a skilled typist can type over one hundred words per minute with ease", 75],
    ["Speed group B2", "rhythm and flow are more important than rushing when you type now", 75],
    ["Speed group B3", "every mistake is a chance to learn which finger needs more practice", 75],
    ["Speed group B4", "consistent practice of thirty minutes a day will improve your speed", 75],
    ["Speed group B5", "the keyboard is your instrument and touch typing is your musical skill", 75],
    ["Literature excerpt A", "it is a far far better thing that I do than I have ever done before", 76],
    ["Literature excerpt B", "in my beginning is my end and in my end is my beginning always", 76],
    ["Literature excerpt C", "the sky above the port was the color of television tuned to dead", 76],
    ["Literature excerpt D", "all happy families are alike each unhappy family is unhappy its way", 76],
    ["Literature excerpt E", "we are all just walking each other home through this brief journey", 76],
    ["Nature paragraph A", "the forest is alive with sound; birds call from every branch while the wind moves gently through the leaves above", 77],
    ["Nature paragraph B", "the river runs clear and cold over smooth stones as sunlight dances on the surface and fish dart below", 77],
    ["Nature paragraph C", "at dawn the mountains glow pink and gold in the early light as mist rises from the valleys far below", 77],
    ["Nature paragraph D", "the desert at night is cool and silent under a sky blazing with more stars than you can count or name", 77],
    ["Nature paragraph E", "the ocean waves roll in one after another without pause shaping the sand and polishing the stones on shore", 77],
    ["Science paragraph A", "the universe began about fourteen billion years ago in an event called the big bang and has been expanding ever since that moment", 78],
    ["Science paragraph B", "the human genome contains about three billion base pairs of dna that encode the instructions for building a complete human being", 78],
    ["Science paragraph C", "quantum mechanics describes the behavior of particles at the smallest scales where the rules of everyday physics no longer apply", 78],
    ["Science paragraph D", "climate scientists use computer models to simulate the atmosphere and predict how temperature and precipitation will change in the future", 78],
    ["Science paragraph E", "the theory of evolution by natural selection explains how species adapt to their environments over millions of years of gradual change", 78],
    ["History paragraph A", "the ancient greeks created a democratic system of government that would influence political thought for thousands of years to come", 79],
    ["History paragraph B", "the silk road was a network of trade routes connecting china to the mediterranean world and enabled the exchange of goods and ideas", 79],
    ["History paragraph C", "the renaissance was a period of great artistic and intellectual achievement that began in italy and spread throughout all of europe", 79],
    ["History paragraph D", "the american revolution was inspired by enlightenment ideas about liberty and government and created a new kind of democratic republic", 79],
    ["History paragraph E", "the invention of the internet in the late twentieth century connected the world in ways that transformed every aspect of human life", 79],
    ["Expert speed A", "the greatest glory in living lies not in never falling but in rising every time we fall and moving forward with courage and hope", 80],
    ["Expert speed B", "success is not final failure is not fatal it is the courage to continue that counts in every moment of your life always", 80],
    ["Expert speed C", "in three words I can sum up everything I have learned about life: it goes on and so must you no matter what", 80],
    ["Expert speed D", "the future belongs to those who believe in the beauty of their dreams and work hard every day to make those dreams real", 80],
    ["Expert speed E", "you are never too old to set another goal or to dream a new dream and then to work toward making it come true", 80],
    ["Master paragraph A", "technology is best when it brings people together; the internet has made it possible for anyone anywhere to share knowledge and connect", 81],
    ["Master paragraph B", "reading is to the mind what exercise is to the body; the more you read the stronger your thinking and vocabulary become over time", 81],
    ["Master paragraph C", "learning to type well is one of the most practical skills you can develop; it saves time in every task that involves a computer", 81],
    ["Master paragraph D", "the secret of getting ahead is getting started; once you take the first step everything becomes easier and the path becomes more clear", 81],
    ["Master paragraph E", "with patience persistence and practice any skill can be learned; the key is to show up every day and do the work faithfully", 81],
    ["Grand speed A", "you started this typing course with the home row keys and now you can type anything on the keyboard with skill and confidence", 82],
    ["Grand speed B", "touch typing is a skill that will serve you for the rest of your life in every job class and personal task you face", 82],
    ["Grand speed C", "the keyboard is just the beginning; the real power comes from the ideas and words that flow through your fingers onto the screen", 82],
    ["Grand speed D", "every expert was once a beginner; every professional was once an amateur; every master was once a student just like you are now", 82],
    ["Grand finale A", "you have completed every lesson and mastered the keyboard; now type anything with full speed accuracy and confidence every day", 83],
    ["Grand finale B", "practice daily set new goals and challenge yourself to go faster and more accurately with every session; you are a typist now", 83],
    ["Grand finale C", "congratulations on finishing every lesson; your fingers now know the keyboard by feel and your typing will keep improving with use", 83],
    ["Grand finale D", "the journey from hunting and pecking to touch typing is one you have completed; keep typing and your speed will grow forever", 84],
    ["Grand finale E", "you are now a skilled typist; use your talent to write learn create and communicate; the keyboard is your tool and you are ready", 85],
    ["Ultimate mastery A", "the best investment you can make is in yourself; learning new skills like typing opens doors and creates opportunities throughout life", 85],
    ["Ultimate mastery B", "in a world driven by information and communication the ability to type quickly and accurately is more valuable than ever before", 85],
    ["Ultimate mastery C", "every word you type brings you closer to your goals; whether you are writing an email a report a story or code your speed matters", 86],
    ["Ultimate mastery D", "the foundation you built key by key and lesson by lesson has made you a competent and confident typist ready for any task", 86],
    ["Ultimate mastery E", "keep your fingers on the home row breathe steadily keep your eyes on the text and let your training guide you to perfection", 87],
    ["Perfect typing A", "aim for perfection in every keystroke; accuracy is the root from which speed grows naturally and inevitably with enough practice", 87],
    ["Perfect typing B", "a calm focused mind types faster than a rushed anxious one; find your rhythm slow down slightly and watch your accuracy soar", 87],
    ["Perfect typing C", "the goal is not speed alone but the harmony of speed and accuracy working together smoothly like a well tuned instrument", 88],
    ["Perfect typing D", "every time you sit down to type you are training your muscle memory; make every session count and every practice session matter", 88],
    ["Typing complete", "you have achieved mastery of the keyboard; speed accuracy and confidence are yours; type boldly and never stop improving today", 90],
  ]),
];

let globalId = 1;
for (const section of rawSections) {
  for (const lesson of section.lessons) {
    lesson.id = globalId++;
  }
}

export const sections: Section[] = rawSections;

export const allLessons: Lesson[] = rawSections.flatMap(s => s.lessons);

export const totalLessons = allLessons.length;

export function getLessonById(id: number): Lesson | undefined {
  return allLessons.find(l => l.id === id);
}

export function getNextLesson(lesson: Lesson): Lesson | undefined {
  const idx = allLessons.findIndex(l => l.id === lesson.id);
  return allLessons[idx + 1];
}

export function computeStars(wpm: number, accuracy: number): 1 | 2 | 3 {
  if (wpm >= 50 && accuracy >= 95) return 3;
  if (wpm >= 30 && accuracy >= 90) return 2;
  return 1;
}
