// ─────────────────────────────────────────────────────────────────────────────
// v4-instruction-autofix.ts — one-click "fix EVERYTHING" for instruction files.
//
// The admin uploads a (possibly 70MB+) instruction file generated by the
// scripts; LLM output routinely violates the platform Zod schema + cross-ref
// rules (out-of-range numbers, bad enums, missing required arrays, too-short
// text, duplicate/out-of-range indices, dangling prerequisite refs, invalid
// MCQ banks, malformed slug…). This module deterministically repairs ALL of
// them so the file validates with ZERO errors and publishes cleanly.
//
// Strategy = a structural SUPERSET pass (covers every schema rule by
// construction) followed by a validate→repeat verification loop. Runs purely
// in-memory on the parsed object — no model calls — so it's instant even on a
// full 5×7×9×10 curriculum. Every repair is counted into a human-readable
// Arabic `changes` list; injected placeholders are clearly flagged for review.
//
// Mirrors the client autoFixInstructionFile + the generator's sanitize.jq, but
// is the AUTHORITATIVE fixer: it pads too-short REQUIRED text, coerces the
// slug, repairs MCQ banks, strips index fields (forcing clean positional
// renumbering → no duplicate-code / out-of-range errors), and FK-cleans +
// de-cycles the prerequisite graph — the pieces needed to guarantee publish.
// ─────────────────────────────────────────────────────────────────────────────
import { validateV4InstructionFile, type V4ValidationReport } from "./v4-instruction-validator";

const BLOOM = new Set(["remember", "understand", "apply", "analyze", "evaluate", "create"]);
const SEVERITY = new Set(["minor", "major", "critical"]);
const LAB_KINDS = ["diagnostic", "decision", "application", "analysis", "connection"] as const;

export type AutoFixResult = {
  fixedDoc: any;
  /** Aggregated, human-readable Arabic list of what was repaired. */
  changes: string[];
  /** Validation report of the FIXED doc (should be ok:true). */
  report: V4ValidationReport;
};

// ── primitives ───────────────────────────────────────────────────────────────
const isNum = (x: any): x is number => typeof x === "number" && Number.isFinite(x);
const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, Math.round(v)));
const tlen = (s: any): number => (typeof s === "string" ? s.trim().length : 0);
const isArr = (x: any): x is any[] => Array.isArray(x);

export function autoFixV4InstructionFile(input: any): AutoFixResult {
  const doc = deepClone(input);
  const c = new Counters();

  fixRoot(doc, c);

  // Verify + (defensive) repeat. The structural pass is a superset, so one
  // pass clears everything; we loop up to 3× as a safety net against any rule
  // interaction we didn't foresee, and stop as soon as it's clean.
  let report = validateV4InstructionFile(doc);
  let guard = 0;
  while (!report.ok && guard < 2) {
    fixRoot(doc, c);
    report = validateV4InstructionFile(doc);
    guard++;
  }

  return { fixedDoc: doc, changes: c.list(), report };
}

function deepClone(x: any): any {
  // structuredClone is available on Node 18+; fall back to JSON for safety.
  try { return structuredClone(x); } catch { return JSON.parse(JSON.stringify(x)); }
}

// ── change aggregation ─────────────────────────────────────────────────────
class Counters {
  m = new Map<string, number>();
  bump(k: string, n = 1) { this.m.set(k, (this.m.get(k) ?? 0) + n); }
  list(): string[] {
    const out: string[] = [];
    const push = (k: string, label: string) => { const n = this.m.get(k); if (n) out.push(`${label}: ${n}`); };
    push("num", "قيم رقمية ضُبطت ضمن مداها المسموح");
    push("enum", "قيم خيارات غير صالحة صُحّحت/حُذفت (bloom/severity/الأنواع)");
    push("indexDel", "أرقام ترقيب خارج النطاق حُذفت (يُعاد ترقيمها تلقائياً)");
    push("textPad", "حقول نصّية إجبارية قصيرة جداً عُبّئت بنصّ مؤقّت — تحتاج مراجعة بشرية");
    push("textDrop", "حقول نصّية اختيارية قصيرة جداً حُذفت");
    push("arrFill", "مصفوفات إجبارية فارغة عُبّئت بعنصر مؤقّت — تحتاج مراجعة بشرية");
    push("labKinds", "معامل أُعيد ضبط أسئلتها لتغطّي الأنواع الخمسة بالضبط");
    push("mcqFix", "أسئلة اختيار-من-متعدد غير صالحة حُوِّلت إلى سؤال قصير");
    push("refs", "مراجع متطلّبات معطوبة/ذاتية/حلقية حُذفت");
    push("banks", "بنوك امتحانات تشير لأكواد غير موجودة حُذفت");
    push("slug", "مُعرّف التخصص (slug) صُحِّح ليطابق الصيغة المطلوبة");
    push("schemaVer", "إصدار المخطّط (schema_version) صُحِّح");
    return out;
  }
}

// ── text helpers ───────────────────────────────────────────────────────────
const PAD = "محتوى مؤقّت بحاجة لمراجعة بشرية — يُرجى تعديله";
/** Required text: keep if long enough, else replace with a padded placeholder. */
function reqText(obj: any, key: string, min: number, c: Counters, fallback = PAD) {
  if (tlen(obj?.[key]) >= min) return;
  let v = typeof obj?.[key] === "string" && obj[key].trim() ? obj[key].trim() : fallback;
  while (v.trim().length < min) v = v + " " + fallback;
  obj[key] = v;
  c.bump("textPad");
}
/** Optional text: drop if present-but-too-short (would fail Zod). */
function optText(obj: any, key: string, min: number, c: Counters) {
  if (obj && typeof obj[key] === "string" && tlen(obj[key]) < min) { delete obj[key]; c.bump("textDrop"); }
}
function clampField(obj: any, key: string, lo: number, hi: number, c: Counters) {
  if (obj && isNum(obj[key])) { const v = clamp(obj[key], lo, hi); if (v !== obj[key]) { obj[key] = v; c.bump("num"); } }
}
function delIndexIfBad(obj: any, key: string, lo: number, hi: number, c: Counters) {
  // Strip ALL explicit indices (even valid ones): the validator renumbers
  // positionally (?? idx+1), so dropping them guarantees sequential, unique,
  // in-range codes — killing duplicate-code AND out-of-range-index errors.
  // Only COUNT the genuinely-bad ones so the changes list stays honest.
  if (!obj || !(key in obj)) return;
  const v = obj[key];
  const bad = !isNum(v) || v < lo || v > hi;
  delete obj[key];
  if (bad) c.bump("indexDel");
}

// ── exam meta ────────────────────────────────────────────────────────────────
function fixExamMeta(exam: any, c: Counters) {
  if (!exam || typeof exam !== "object") return;
  // pass_threshold_percent is REQUIRED on an exam-meta object.
  if (!isNum(exam.pass_threshold_percent)) { exam.pass_threshold_percent = 70; c.bump("num"); }
  else clampField(exam, "pass_threshold_percent", 0, 100, c);
  clampField(exam, "points", 1, 1000, c);
  clampField(exam, "time_limit_minutes", 1, 240, c);
  optText(exam, "description", 5, c);
  if (isArr(exam.question_types)) {
    const f = exam.question_types.filter((t: any) => tlen(t) >= 2);
    if (f.length !== exam.question_types.length) { if (f.length) exam.question_types = f; else delete exam.question_types; }
  }
}

function fixLearningObjectives(node: any, c: Counters) {
  if (!node || !isArr(node.learning_objectives)) return;
  node.learning_objectives = node.learning_objectives
    .map((lo: any) => {
      if (lo && typeof lo === "object" && typeof lo.bloom_level === "string" && !BLOOM.has(lo.bloom_level)) { lo.bloom_level = "understand"; c.bump("enum"); }
      return lo;
    })
    .filter((lo: any) => lo && typeof lo === "object" && tlen(lo.statement) >= 8);
  if (node.learning_objectives.length === 0) delete node.learning_objectives;
}

function dropBloomFocus(obj: any, c: Counters) {
  if (obj && typeof obj.bloom_focus === "string" && !BLOOM.has(obj.bloom_focus)) { delete obj.bloom_focus; c.bump("enum"); }
}

// ── concepts / mistakes / labs / lessons ─────────────────────────────────────
function fixConcept(con: any, c: Counters) {
  reqText(con, "name", 2, c);
  reqText(con, "explanation", 10, c);
  reqText(con, "mastery_criterion", 5, c);
  if ("weight" in con) clampField(con, "weight", 1, 5, c);
}

function fixMistake(mk: any, c: Counters) {
  reqText(mk, "mistake", 5, c);
  reqText(mk, "correction", 5, c);
  reqText(mk, "treatment", 5, c);
  if (typeof mk.severity === "string" && !SEVERITY.has(mk.severity)) { delete mk.severity; c.bump("enum"); }
}

function fixLabQuestion(q: any, c: Counters) {
  reqText(q, "prompt", 5, c);
  if ("points" in q) clampField(q, "points", 1, 10, c);
  optText(q, "rubric", 10, c);
  optText(q, "solution_outline", 10, c);
}

function fixLab(lab: any, c: Counters) {
  delIndexIfBad(lab, "lab_index", 1, 5, c);
  reqText(lab, "title", 3, c);
  reqText(lab, "scenario", 20, c);
  reqText(lab, "completion_criterion", 5, c);
  optText(lab, "pedagogical_sequence", 15, c);
  if (isArr(lab.prerequisite_lessons)) lab.prerequisite_lessons = lab.prerequisite_lessons.filter((x: any) => typeof x === "string");

  // Questions must be EXACTLY 5, one of each kind. Rebuild deterministically:
  // map existing questions onto kinds (keeping content), fill gaps by cloning,
  // so we always end with the 5 distinct kinds present once each.
  let qs = isArr(lab.questions) ? lab.questions.filter((q: any) => q && typeof q === "object") : [];
  for (const q of qs) fixLabQuestion(q, c);
  const before = qs.length;
  const byKind = new Map<string, any>();
  for (const q of qs) { const k = String(q.kind ?? ""); if (LAB_KINDS.includes(k as any) && !byKind.has(k)) byKind.set(k, q); }
  const leftovers = qs.filter((q: any) => !LAB_KINDS.includes(String(q.kind) as any) || byKind.get(String(q.kind)) !== q);
  const rebuilt: any[] = [];
  for (const kind of LAB_KINDS) {
    let q = byKind.get(kind);
    if (!q) {
      q = leftovers.shift() ?? qs[0] ?? { prompt: PAD + " " + PAD, rubric: PAD + " " + PAD, solution_outline: PAD + " " + PAD };
      q = deepClone(q);
      q.kind = kind;
      if (tlen(q.prompt) < 5) q.prompt = PAD + " " + PAD;
    }
    rebuilt.push(q);
  }
  lab.questions = rebuilt;
  if (before !== 5 || leftovers.length || rebuilt.some((q, i) => qs[i] !== q)) c.bump("labKinds");
}

function fixLesson(les: any, c: Counters) {
  delIndexIfBad(les, "lesson_index", 1, 10, c);
  reqText(les, "name", 3, c);
  reqText(les, "goal", 10, c);
  reqText(les, "bridge_sentence", 10, c);
  reqText(les, "final_check_question", 5, c);
  reqText(les, "session_complete_criterion", 5, c);
  if ("estimated_gem_cost" in les) clampField(les, "estimated_gem_cost", 0, 100, c);
  if ("expected_duration_minutes" in les) clampField(les, "expected_duration_minutes", 1, 240, c);
  optText(les, "motivation_hook", 15, c);
  optText(les, "solution_outline", 10, c);
  fixLearningObjectives(les, c);

  // concepts ≥1, each valid
  let concepts = isArr(les.concepts) ? les.concepts.filter((x: any) => x && typeof x === "object") : [];
  for (const con of concepts) fixConcept(con, c);
  if (concepts.length === 0) { concepts = [{ name: "مفهوم", explanation: PAD + " " + PAD, mastery_criterion: PAD }]; c.bump("arrFill"); }
  les.concepts = concepts;

  // common_mistakes ≥1, each valid
  let mistakes = isArr(les.common_mistakes) ? les.common_mistakes.filter((x: any) => x && typeof x === "object") : [];
  for (const mk of mistakes) fixMistake(mk, c);
  if (mistakes.length === 0) { mistakes = [{ mistake: "خطأ شائع متوقّع في هذا الدرس", correction: "التصحيح الصحيح المناسب", treatment: "عالج الخطأ بمثال موجَّه وسؤال تحقّق" }]; c.bump("arrFill"); }
  les.common_mistakes = mistakes;

  // yemeni_examples ≥1, each ≥5 chars
  let ye = isArr(les.yemeni_examples) ? les.yemeni_examples.filter((e: any) => tlen(e) >= 5) : [];
  if (ye.length === 0) { ye = ["مثال من واقع الطالب اليمني يقرّب الفكرة"]; c.bump("arrFill"); }
  les.yemeni_examples = ye;
}

function fixUnit(unit: any, c: Counters) {
  delIndexIfBad(unit, "unit_index", 1, 9, c);
  reqText(unit, "name", 3, c);
  reqText(unit, "goal", 10, c);
  fixExamMeta(unit.exam, c);
  optText(unit, "motivation_hook", 15, c);
  fixLearningObjectives(unit, c);
  if (isArr(unit.key_concepts)) { const f = unit.key_concepts.filter((k: any) => tlen(k) >= 2); unit.key_concepts = f; }
  else unit.key_concepts = [];
  if (!isArr(unit.prerequisite_units)) unit.prerequisite_units = [];
  if (!isArr(unit.enables_units)) unit.enables_units = [];

  let labs = isArr(unit.labs) ? unit.labs.filter((x: any) => x && typeof x === "object") : [];
  for (const lab of labs) fixLab(lab, c);
  if (labs.length === 0) {
    labs = [{
      title: "معمل تطبيقي", scenario: PAD + " " + PAD + " " + PAD, completion_criterion: PAD,
      questions: LAB_KINDS.map((k) => ({ kind: k, prompt: PAD + " " + PAD })),
    }];
    c.bump("arrFill");
  } else if (labs.length > 5) { labs = labs.slice(0, 5); }
  unit.labs = labs;

  let lessons = isArr(unit.lessons) ? unit.lessons.filter((x: any) => x && typeof x === "object") : [];
  for (const les of lessons) fixLesson(les, c);
  if (lessons.length === 0) {
    lessons = [{
      name: "درس", goal: PAD + " " + PAD, bridge_sentence: PAD + " " + PAD,
      final_check_question: PAD, session_complete_criterion: PAD,
      concepts: [{ name: "مفهوم", explanation: PAD + " " + PAD, mastery_criterion: PAD }],
      common_mistakes: [{ mistake: "خطأ شائع", correction: "التصحيح", treatment: "العلاج المناسب" }],
      yemeni_examples: ["مثال من واقع الطالب اليمني"],
    }];
    c.bump("arrFill");
  } else if (lessons.length > 10) { lessons = lessons.slice(0, 10); }
  unit.lessons = lessons;
  if (!isArr(unit.prerequisite_units)) unit.prerequisite_units = [];
}

function fixStage(stage: any, c: Counters) {
  delIndexIfBad(stage, "stage_index", 1, 7, c);
  reqText(stage, "name", 3, c);
  reqText(stage, "goal", 10, c);
  fixExamMeta(stage.exam, c);
  dropBloomFocus(stage, c);
  let units = isArr(stage.units) ? stage.units.filter((x: any) => x && typeof x === "object") : [];
  for (const u of units) fixUnit(u, c);
  if (units.length === 0) { units = [makeStubUnit()]; c.bump("arrFill"); }
  else if (units.length > 9) units = units.slice(0, 9);
  stage.units = units;
}

function fixLevel(level: any, c: Counters) {
  delIndexIfBad(level, "level_index", 1, 5, c);
  reqText(level, "name", 3, c);
  reqText(level, "goal", 10, c);
  fixExamMeta(level.exam, c);
  dropBloomFocus(level, c);
  let stages = isArr(level.stages) ? level.stages.filter((x: any) => x && typeof x === "object") : [];
  for (const s of stages) fixStage(s, c);
  if (stages.length === 0) { stages = [makeStubStage()]; c.bump("arrFill"); }
  else if (stages.length > 7) stages = stages.slice(0, 7);
  level.stages = stages;
}

function makeStubUnit(): any {
  return {
    name: "وحدة", goal: PAD + " " + PAD,
    prerequisite_units: [], enables_units: [], key_concepts: [],
    labs: [{ title: "معمل", scenario: PAD + " " + PAD + " " + PAD, completion_criterion: PAD, questions: LAB_KINDS.map((k) => ({ kind: k, prompt: PAD + " " + PAD })) }],
    lessons: [{ name: "درس", goal: PAD + " " + PAD, bridge_sentence: PAD + " " + PAD, final_check_question: PAD, session_complete_criterion: PAD, concepts: [{ name: "مفهوم", explanation: PAD + " " + PAD, mastery_criterion: PAD }], common_mistakes: [{ mistake: "خطأ", correction: "تصحيح صحيح", treatment: "علاج مناسب" }], yemeni_examples: ["مثال يمني"] }],
  };
}
function makeStubStage(): any { return { name: "مرحلة", goal: PAD + " " + PAD, units: [makeStubUnit()] }; }

// ── exam questions (banks + placement) ───────────────────────────────────────
function fixExamQuestion(q: any, c: Counters): void {
  reqText(q, "prompt", 5, c);
  if ("difficulty" in q) clampField(q, "difficulty", 1, 3, c); else q.difficulty = 2;
  if ("points" in q) clampField(q, "points", 1, 10, c);
  if ("time_limit_seconds" in q) clampField(q, "time_limit_seconds", 10, 3600, c);
  optText(q, "rubric", 10, c);
  optText(q, "solution_outline", 10, c);
  optText(q, "explanation", 2, c);
  // MCQ validity: needs ≥2 choices + a valid correct_index. If not, demote to
  // short_answer (guaranteed-valid) and drop the broken MCQ fields.
  if (q.kind === "mcq") {
    const choices = isArr(q.choices) ? q.choices.filter((ch: any) => tlen(ch) >= 1) : [];
    const ci = q.correct_index;
    const ok = choices.length >= 2 && isNum(ci) && ci >= 0 && ci < choices.length;
    if (ok) { q.choices = choices; q.correct_index = clamp(ci, 0, choices.length - 1); }
    else { q.kind = "short_answer"; delete q.choices; delete q.correct_index; c.bump("mcqFix"); }
  } else if (!["practical", "short_answer"].includes(q.kind)) {
    q.kind = "short_answer"; c.bump("enum");
  }
}

// ── root ─────────────────────────────────────────────────────────────────────
function fixRoot(doc: any, c: Counters) {
  if (!doc || typeof doc !== "object") return;

  // schema_version
  if (doc.schema_version !== "v4.0" && doc.schema_version !== "v4.1") { doc.schema_version = "v4.1"; c.bump("schemaVer"); }

  // specialty
  const sp = doc.specialty && typeof doc.specialty === "object" ? doc.specialty : (doc.specialty = {});
  fixSpecialty(sp, c);

  // levels 1..5
  let levels = isArr(doc.levels) ? doc.levels.filter((x: any) => x && typeof x === "object") : [];
  for (const lv of levels) fixLevel(lv, c);
  if (levels.length === 0) { levels = [{ name: "مستوى", goal: PAD + " " + PAD, stages: [makeStubStage()] }]; c.bump("arrFill"); }
  else if (levels.length > 5) levels = levels.slice(0, 5);
  doc.levels = levels;

  // Cross-reference cleanup: compute positional codes (indices were stripped →
  // pure positional) then drop prerequisite/enables refs that point at a
  // missing code or at self. Removing edges also breaks any cycle.
  cleanReferences(doc, c);

  // exam_banks
  if (doc.exam_banks && typeof doc.exam_banks === "object") fixExamBanks(doc, c);

  // placement
  if (isArr(doc.placement_test_questions)) {
    for (const q of doc.placement_test_questions) {
      if (!q || typeof q !== "object") continue;
      if (isNum(q.target_level_index)) clampField(q, "target_level_index", 1, 5, c); else q.target_level_index = 1;
      fixExamQuestion(q, c);
    }
  }

  // publish_notes (optional ≥2)
  optText(doc, "publish_notes", 2, c);
}

function fixSpecialty(sp: any, c: Counters) {
  // slug — must match /^[a-z0-9][a-z0-9_-]*$/, length 2..64.
  let slug = typeof sp.slug === "string" ? sp.slug.trim().toLowerCase() : "";
  let cleaned = slug.replace(/[^a-z0-9_-]/g, "-").replace(/^[^a-z0-9]+/, "");
  if (cleaned.length < 2) cleaned = (cleaned + "specialty").slice(0, 64);
  if (cleaned.length > 64) cleaned = cleaned.slice(0, 64);
  if (cleaned !== sp.slug) { sp.slug = cleaned; c.bump("slug"); }
  reqText(sp, "name", 2, c, "تخصص");
  optText(sp, "description", 10, c);
  optText(sp, "target_persona", 5, c);
  optText(sp, "teacher_tone", 5, c);
  if (typeof sp.icon === "string" && sp.icon.length > 8) { delete sp.icon; c.bump("textDrop"); }
  if (isArr(sp.yemeni_examples)) { const f = sp.yemeni_examples.filter((e: any) => tlen(e) >= 3); if (f.length) sp.yemeni_examples = f; else delete sp.yemeni_examples; }
}

function cleanReferences(doc: any, c: Counters) {
  const unitCodes = new Set<string>();
  const lessonCodes = new Set<string>();
  doc.levels.forEach((lv: any, li: number) => {
    const L = li + 1;
    (lv.stages ?? []).forEach((st: any, si: number) => {
      const S = `${L}.${si + 1}`;
      (st.units ?? []).forEach((u: any, ui: number) => {
        const U = `${S}.${ui + 1}`;
        unitCodes.add(U);
        (u.lessons ?? []).forEach((_les: any, lsi: number) => lessonCodes.add(`${U}.${lsi + 1}`));
      });
    });
  });
  const clean = (arr: any, set: Set<string>, self: string | null): any[] => {
    if (!isArr(arr)) return [];
    const out = arr.filter((x: any) => typeof x === "string" && set.has(x) && x !== self);
    if (out.length !== arr.length) c.bump("refs", arr.length - out.length);
    return out;
  };
  doc.levels.forEach((lv: any, li: number) => {
    const L = li + 1;
    (lv.stages ?? []).forEach((st: any, si: number) => {
      const S = `${L}.${si + 1}`;
      (st.units ?? []).forEach((u: any, ui: number) => {
        const U = `${S}.${ui + 1}`;
        u.prerequisite_units = clean(u.prerequisite_units, unitCodes, U);
        u.enables_units = clean(u.enables_units, unitCodes, U);
        (u.lessons ?? []).forEach((les: any, lsi: number) => {
          const LC = `${U}.${lsi + 1}`;
          les.prerequisite_lessons = clean(les.prerequisite_lessons, lessonCodes, LC);
          les.enables_lessons = clean(les.enables_lessons, lessonCodes, LC);
        });
        (u.labs ?? []).forEach((lab: any) => {
          if (isArr(lab.prerequisite_lessons)) lab.prerequisite_lessons = clean(lab.prerequisite_lessons, lessonCodes, null);
        });
      });
    });
  });
}

function fixExamBanks(doc: any, c: Counters) {
  const banks = doc.exam_banks;
  // Build valid code sets (positional, post-renumber).
  const unitCodes = new Set<string>();
  const stageCodes = new Set<string>();
  const levelIdx = new Set<string>();
  doc.levels.forEach((lv: any, li: number) => {
    const L = li + 1; levelIdx.add(String(L));
    (lv.stages ?? []).forEach((st: any, si: number) => {
      const S = `${L}.${si + 1}`; stageCodes.add(S);
      (st.units ?? []).forEach((_u: any, ui: number) => unitCodes.add(`${S}.${ui + 1}`));
    });
  });
  const fixGroup = (group: any, validCodes: Set<string>) => {
    if (!group || typeof group !== "object") return;
    for (const code of Object.keys(group)) {
      if (!validCodes.has(code)) { delete group[code]; c.bump("banks"); continue; }
      const bank = group[code];
      let variants = isArr(bank?.variants) ? bank.variants : [];
      variants = variants.filter((v: any) => isArr(v)).slice(0, 3);
      for (const v of variants) for (const q of v) if (q && typeof q === "object") fixExamQuestion(q, c);
      // Each variant needs ≥1 question; drop empty variants; drop the bank if none left.
      variants = variants.filter((v: any) => v.length >= 1);
      if (variants.length === 0) { delete group[code]; c.bump("banks"); }
      else bank.variants = variants;
    }
  };
  fixGroup(banks.unit_banks, unitCodes);
  fixGroup(banks.stage_banks, stageCodes);
  fixGroup(banks.level_banks, levelIdx);
}
