#!/usr/bin/env python3
"""uni-cybersecurity — تسلسل منطقي — 5 مستويات كاملة"""
import json; from pathlib import Path; import random
random.seed(42)
def h(s): return sum(ord(c)*(i+1) for i,c in enumerate(str(s)))
OUT = Path("out/uni-cybersecurity"); OUT.mkdir(parents=True, exist_ok=True)
def U(n,*l): return (n,list(l))
def S(n,g,*u): return (n,g,list(u))
def L(n,g,b,*s): return (n,g,b,list(s))

CURRICULUM = [
# ═══════════ LEVEL 1 ═══════════
L("المستوى الأول: أساسيات الأمن السيبراني","فهم التهديدات، مبادئ الأمن، الشبكات الآمنة","remember",
S("مقدمة في الأمن السيبراني","فهم المشهد الأمني والتهديدات الأساسية",
U("ما هو الأمن السيبراني؟","تعريف الأمن السيبراني","أهمية الأمن السيبراني","تاريخ الهجمات الشهيرة","مثلث CIA: السرية والسلامة والتوفر","الفرق بين الأمن والمخاطر","مجالات الأمن السيبراني","المسارات المهنية في الأمن","مشروع: تحليل تهديد"),
U("أنواع التهديدات","البرمجيات الخبيثة Malware","فيروسات الحاسوب","برامج الفدية Ransomware","أحصنة طروادة Trojans","برامج التجسس Spyware","هجمات التصيد Phishing","هجمات حجب الخدمة DDoS","مشروع: تصنيف تهديد"),
U("الجهات الفاعلة في التهديد","القراصنة Hackers","الجهات الحكومية","الموظفون الداخليون","المنظمات الإجرامية","هاكتفيست Hacktivists","Script Kiddies","مستويات التهديد","مشروع: نمذجة تهديد"),
U("مبادئ الدفاع المتعدد","Defense in Depth","الطبقات الأمنية","مبدأ الصلاحيات الدنيا","الفصل بين الواجبات","Fail Secure","عدم الثقة بأي شيء","الأمن بالتصميم","مشروع: تصميم دفاعي"),
U("أخلاقيات الأمن السيبراني","الهاكر الأخلاقي","القوانين والتشريعات","الإبلاغ المسؤول","الخصوصية وحماية البيانات","أخلاقيات اختبار الاختراق","مدونات السلوك المهني","العواقب القانونية","مشروع: دراسة حالة"),
U("المخاطر والثغرات","ما هي الثغرة Vulnerability؟","الفرق بين التهديد والثغرة والمخاطرة","تقييم المخاطر Risk Assessment","تحليل الأثر Business Impact","CVSS: نظام تقييم الثغرات","قواعد بيانات الثغرات CVE","أمثلة واقعية","مشروع: تقييم مخاطر"),
U("الهندسة الاجتماعية","ما هي الهندسة الاجتماعية؟","التصيد Phishing","الذريعة Pretexting","Baiting و USB Drops","Tailgating","التوعية الأمنية","مكافحة الهندسة الاجتماعية","مشروع: حملة توعية"),
U("سياسات الأمن","أهمية السياسات الأمنية","سياسة كلمات المرور","سياسة الاستخدام المقبول","سياسة التصنيف","سياسة الاستجابة للحوادث","تطبيق السياسات","مراجعة السياسات","مشروع: كتابة سياسة"),
U("مشروع: تحليل أمني","تخطيط","جمع معلومات","تحليل تهديدات","تقييم مخاطر","كتابة تقرير","توصيات","عرض"),
),
S("أساسيات الشبكات للأمن","فهم الشبكات للدفاع عنها",
U("نموذج OSI للأمن","الطبقات السبع","ثغرات كل طبقة","الدفاعات لكل طبقة","التطبيق العملي","Wireshark","تحليل حزم","مشروع: تحليل شبكة"),
U("بروتوكولات الشبكة","TCP Three-way Handshake","UDP","ICMP","ARP","DNS","HTTP/HTTPS","SMTP","مشروع: تحليل بروتوكول"),
U("عناوين IP و Subnetting","IPv4","Subnet Mask","CIDR","العناوين الخاصة والعامة","IPv6","تقسيم الشبكات للأمان","مشروع: خطة عناوين"),
U("أجهزة الشبكات","Router","Switch","Firewall","IDS/IPS","Proxy","Load Balancer","Wireless AP","مشروع: تصميم شبكة"),
U("تحليل حركة الشبكة","Wireshark","tcpdump","NetFlow","PCAP Analysis","Baselines","Anomaly Detection","مشروع: مراقبة حركة"),
U("مسح الشبكات","nmap","Port Scanning","Service Detection","OS Fingerprinting","Script Scanning","تفسير النتائج","مشروع: مسح شبكة"),
U("الشبكات اللاسلكية","WiFi Security","WPA2 vs WPA3","802.1X","RADIUS","Evil Twin","WPS Attacks","مشروع: أمن لاسلكي"),
U("أدوات الأمن الأساسية","nmap","Wireshark","netstat","Metasploit","Burp Suite","Nessus","Hydra","مشروع: استخدام أدوات"),
U("مشروع: تدقيق شبكة","تخطيط","مسح","تحليل","ثغرات","تقرير","توصيات","عرض"),
),
S("أنظمة التشغيل للأمن","تأمين Windows و Linux",
U("أمان Windows","حسابات المستخدمين","UAC","BitLocker","Windows Defender","Windows Firewall","Event Viewer","مشروع: تدقيق Windows"),
U("أمان Linux","الصلاحيات","sudo","SELinux/AppArmor","iptables","SSH Hardening","Fail2ban","مشروع: تدقيق Linux"),
U("إدارة المستخدمين والصلاحيات","مبدأ الصلاحيات الدنيا","RBAC","حسابات الخدمة","صلاحيات الملفات","مراجعة الصلاحيات","مشروع: إدارة صلاحيات"),
U("سياسات كلمات المرور","تعقيد كلمة المرور","انتهاء الصلاحية","مدير كلمات المرور","المصادقة الثنائية MFA","Passwordless","مشروع: سياسة كلمات"),
U("تحديثات الأمان","Patch Management","Windows Update","Linux apt/yum update","تحديث البرامج","اختبار التحديثات","مشروع: إدارة تحديثات"),
U("مكافحة الفيروسات","أنواع المضادات","التوقيعات","Heuristic Analysis","Sandboxing","EDR","مشروع: مقارنة مضادات"),
U("تشفير الأقراص","BitLocker","LUKS","FileVault","VeraCrypt","TPM","النسخ الاحتياطي للمفاتيح","مشروع: تشفير"),
U("سجلات النظام والتدقيق","Windows Event Log","Syslog","Auditd","سجلات الأمان","تحليل السجلات","مركزية السجلات","مشروع: تحليل سجلات"),
U("مشروع: تقوية نظام","تخطيط","Windows","Linux","توثيق","اختبار","عرض"),
),
S("التشفير الأساسي","فهم وتطبيق التشفير",
U("مبادئ التشفير","ما هو التشفير؟","Plaintext vs Ciphertext","المفاتيح","خوارزميات التشفير","التشفير في الطبقات","مشروع: تشفير بسيط"),
U("التشفير المتماثل","AES","DES/3DES","Blowfish","أوضاع التشغيل ECB, CBC","تطبيقات","مشروع: AES"),
U("التشفير غير المتماثل","RSA","ECC","Diffie-Hellman","المفتاح العام والخاص","تطبيقات","مشروع: RSA"),
U("دوال التجزئة Hash","SHA-256, SHA-3","MD5 ولماذا هو ضعيف","Salting","تطبيقات التجزئة","Rainbow Tables","مشروع: تجزئة"),
U("التوقيع الرقمي","ما هو التوقيع الرقمي؟","المصادقة وعدم الإنكار","DSA, ECDSA","التطبيقات","مشروع: توقيع"),
U("الشهادات الرقمية و PKI","Certificate Authority","سلسلة الثقة","X.509","CRL و OCSP","تثبيت شهادة","مشروع: PKI"),
U("بروتوكول TLS/SSL","TLS Handshake","الإصدارات","الشهادات","HTTPS","التطبيقات","مشروع: TLS"),
U("تطبيقات التشفير","PGP للبريد","تشفير الملفات","VPN","BitLocker/LUKS","تشفير قاعدة البيانات","مشروع: تطبيق"),
U("مشروع: نظام تشفير","تصميم","تنفيذ","اختبار","توثيق","عرض"),
),
S("أمن الويب الأساسي","فهم وتأمين تطبيقات الويب",
U("كيف تعمل تطبيقات الويب","HTTP Request/Response","Cookies & Sessions","Same-Origin Policy","CORS","المصادقة","مشروع: تحليل طلب"),
U("OWASP Top 10","نظرة عامة","أهم الثغرات","تصنيف المخاطر","أدوات الفحص","مشروع: فحص موقع"),
U("SQL Injection","كيف تعمل؟","أنواع SQLi","اكتشافها","الوقاية: Prepared Statements","WAF","مشروع: SQLi"),
U("Cross-Site Scripting XSS","Stored XSS","Reflected XSS","DOM XSS","الوقاية: Output Encoding","CSP","مشروع: XSS"),
U("Cross-Site Request Forgery CSRF","كيف تعمل؟","الوقاية: CSRF Tokens","SameSite Cookies","مشروع: CSRF"),
U("المصادقة وإدارة الجلسات","Secure Authentication","Session Management","JWT","OAuth 2.0","Session Hijacking","مشروع: مصادقة"),
U("التحقق من المدخلات","Input Validation","Sanitization","Escaping","Allowlists vs Blocklists","مشروع: تحقق"),
U("رؤوس الأمان HTTP","CSP","HSTS","X-Frame-Options","X-Content-Type-Options","Referrer-Policy","مشروع: رؤوس"),
U("مشروع: فحص أمني لموقع","تخطيط","فحص","تحليل","توصيات","تقرير","عرض"),
),
S("التحقيق الرقمي الأساسي","مبادئ التحقيق وجمع الأدلة",
U("مبادئ التحقيق الرقمي","ما هو Digital Forensics؟","سلسلة العهدة Chain of Custody","أدوات التحقيق","أنواع التحقيق","مشروع: سيناريو"),
U("جمع الأدلة","Volatile vs Non-volatile","Order of Volatility","تصوير الأدلة","Hashing الأدلة","توثيق الجمع","مشروع: جمع أدلة"),
U("تحليل نظام الملفات","File System Basics","الملفات المحذوفة","File Carving","Timeline Analysis","مشروع: تحليل"),
U("تحليل الذاكرة RAM","Memory Acquisition","Volatility Framework","العمليات","اتصالات الشبكة","مشروع: Memory Dump"),
U("تحليل السجلات","Windows Event Logs","Linux Syslog","سجلات التطبيقات","سجلات الشبكة","Timeline","مشروع: سجلات"),
U("تحليل البريد الإلكتروني","Headers","SPF, DKIM, DMARC","تتبع مصدر البريد","Phishing Analysis","مشروع: تحليل بريد"),
U("كتابة تقرير التحقيق","هيكل التقرير","النتائج","الاستنتاجات","التوصيات","العرض","مشروع: تقرير"),
U("أخلاقيات التحقيق","الخصوصية","القوانين","القبول القانوني للأدلة","الشهادة أمام المحكمة","مشروع: دراسة"),
U("مشروع: تحقيق كامل","سيناريو","جمع","تحليل","تقرير","عرض"),
),
S("مشروع المستوى: حماية أساسية","تطبيق جميع مهارات المستوى",
U("تقييم الوضع الأمني","جمع المعلومات","تحديد الأصول","تصنيف","أوليات"),
U("فحص الشبكة","مسح المنافذ","اكتشاف الخدمات","تحليل","توثيق"),
U("فحص الأنظمة","تدقيق الإعدادات","الصلاحيات","التحديثات","توثيق"),
U("اختبار تطبيقات الويب","فحص OWASP","نقاط الضعف","توثيق"),
U("تحليل المخاطر","تحديد","تحليل","تقييم","توثيق"),
U("كتابة التوصيات","ترتيب الأولويات","خطة علاج","جدول زمني"),
U("كتابة التقرير النهائي","ملخص تنفيذي","نتائج","توصيات","تنسيق"),
U("العرض النهائي","تحضير","تقديم","تغذية راجعة","تقييم"),
),
),
# ═══════════ LEVEL 2 ═══════════
L("المستوى الثاني: أمن الشبكات والأنظمة","تأمين الشبكات، الأنظمة، التطبيقات","apply",
S("أمن الشبكات المتقدم","جدران الحماية، IDS/IPS، VPN",
U("جدران الحماية بعمق","Stateful Firewall","NGFW","قواعد الفلترة","DMZ","Network Segmentation","مشروع: تكوين جدار"),
U("IDS/IPS","Snort","Suricata","التوقيعات","Anomaly Detection","Tuning","مشروع: IDS"),
U("Network Access Control","802.1X","RADIUS","TACACS+","NAC Policies","مشروع: NAC"),
U("VPN وأمن الاتصالات","IPsec","SSL VPN","WireGuard","Split Tunneling","MFA","مشروع: VPN"),
U("Network Monitoring","NetFlow","sFlow","PRTG","SolarWinds","Baselines","مشروع: مراقبة"),
U("Network Hardening","Disable unused services","Port Security","BPDU Guard","DHCP Snooping","مشروع: Hardening"),
U("Zero Trust Network","المبادئ","Micro-segmentation","Continuous Verification","Implementation","مشروع: Zero Trust"),
U("Cloud Network Security","VPC","Security Groups","NACL","WAF","Cloud Firewall","مشروع: سحابة"),
U("مشروع: شبكة آمنة","تصميم","تنفيذ","اختبار","توثيق","عرض"),
),
S("أمن أنظمة Windows","تأمين Windows Server و Active Directory",
U("Windows Server Hardening","تثبيت آمن","إغلاق الخدمات","تحديثات","Audit Policy","مشروع: Hardening"),
U("Active Directory Security","AD Hardening","Admin Tiering","Protected Users","LAPS","مشروع: AD"),
U("Group Policy Security","Security Baselines","Password Policies","Restricted Groups","AppLocker","مشروع: GPO"),
U("Kerberos Security","Golden Ticket","Silver Ticket","Kerberoasting","Defenses","مشروع: Kerberos"),
U("PowerShell Security","Execution Policy","Logging","JEA","Script Block Logging","مشروع: PowerShell"),
U("Windows Event Forwarding","WEF/WEC","Critical Events","Alerting","SIEM Integration","مشروع: WEF"),
U("Credential Protection","Credential Guard","Remote Credential Guard","LSA Protection","مشروع: Credential"),
U("Windows Defender ATP","Policies","Investigation","Automated Response","Threat Hunting","مشروع: Defender"),
U("مشروع: Windows آمن","تخطيط","تنفيذ","اختبار","توثيق","عرض"),
),
S("أمن أنظمة Linux","تأمين خوادم Linux",
U("Linux Hardening","Minimal Install","Disable Root Login","SSH Keys","Fail2ban","مشروع: Hardening"),
U("SELinux و AppArmor","Mandatory Access Control","Policies","Modes","Troubleshooting","مشروع: SELinux"),
U("Linux Auditing","auditd","aureport","ausearch","Rules","مشروع: تدقيق"),
U("Linux Firewall","iptables","nftables","firewalld","ufw","قواعد","مشروع: جدار"),
U("File Integrity Monitoring","AIDE","Tripwire","Osquery","Alerting","مشروع: FIM"),
U("Linux Logging","rsyslog","journald","Log Rotation","Centralization","مشروع: سجلات"),
U("Container Security","Docker Security","Podman","Image Scanning","Runtime Security","مشروع: حاويات"),
U("Linux Malware Detection","ClamAV","Rootkit Hunter","chkrootkit","Lynis","مشروع: كشف"),
U("مشروع: Linux آمن","تخطيط","تنفيذ","اختبار","توثيق","عرض"),
),
S("أمن التطبيقات","OWASP Top 10 وتأمين الكود",
U("OWASP Top 10 بعمق","A01-A10","التصنيف","الأمثلة","الوقاية","مشروع: OWASP"),
U("Injection Attacks","SQL Injection","Command Injection","LDAP Injection","NoSQL Injection","مشروع: Injection"),
U("Broken Authentication","Session Fixation","Credential Stuffing","Password Reset","Multi-Factor","مشروع: Authentication"),
U("Sensitive Data Exposure","Encryption at Rest","Encryption in Transit","Data Masking","Tokenization","مشروع: Data"),
U("XXE و Insecure Deserialization","XML External Entities","Deserialization Attacks","Type Safety","مشروع: XXE"),
U("Security Misconfiguration","Default Accounts","Verbose Errors","Unnecessary Features","مشروع: Misconfig"),
U("Secure SDLC","Threat Modeling","SAST","DAST","Code Review","مشروع: SDLC"),
U("API Security","REST Security","GraphQL Security","Rate Limiting","API Gateway","مشروع: API"),
U("مشروع: تدقيق تطبيق","فحص","تحليل","توصيات","تقرير","عرض"),
),
S("اختبار الاختراق Penetration Testing","منهجية وتطبيق",
U("منهجية اختبار الاختراق","Planning","Reconnaissance","Scanning","Exploitation","Reporting","مشروع: خطة"),
U("جمع المعلومات Recon","Passive Recon","Active Recon","OSINT","Google Dorking","Shodan","مشروع: Recon"),
U("فحص الثغرات Scanning","Port Scanning","Service Enumeration","Vulnerability Scanning","False Positives","مشروع: فحص"),
U("الاستغلال Exploitation","Metasploit","SearchSploit","Manual Exploitation","Payloads","مشروع: استغلال"),
U("Post-Exploitation","Privilege Escalation","Lateral Movement","Persistence","Data Exfiltration","مشروع: Post"),
U("اختبار تطبيقات الويب","Burp Suite","OWASP ZAP","SQLMap","DirBuster","Nikto","مشروع: ويب"),
U("اختبار الشبكات اللاسلكية","Aircrack-ng","Reaver","Wifite","Evil Twin","مشروع: لاسلكي"),
U("كتابة تقرير الاختراق","Executive Summary","Technical Findings","Risk Rating","Remediation","مشروع: تقرير"),
U("مشروع: Pentest كامل","تخطيط","تنفيذ","استغلال","تقرير","عرض"),
),
S("إدارة الثغرات Vulnerability Management","اكتشاف ومعالجة الثغرات",
U("برنامج إدارة الثغرات","Asset Inventory","Scanning Schedule","Prioritization","Remediation","مشروع: برنامج"),
U("أدوات فحص الثغرات","Nessus","OpenVAS","Qualys","Nexpose","Agent-based","مشروع: أدوات"),
U("تصنيف الثغرات","CVSS Calculator","Environmental Score","Temporal Score","Risk Acceptance","مشروع: تصنيف"),
U("معالجة الثغرات","Patching","Compensating Controls","Risk Acceptance","Verification","مشروع: معالجة"),
U("Continuous Monitoring","Agent vs Agentless","Scan Frequency","False Positive Management","مشروع: مراقبة"),
U("Threat Intelligence","Sources","IOCs","TTPs","MITRE ATT&CK","مشروع: TI"),
U("Patch Management","WSUS","SCCM","Linux Patching","Third-party Apps","مشروع: Patches"),
U("Compliance Scanning","CIS Benchmarks","DISA STIGs","PCI-DSS","Reports","مشروع: Compliance"),
U("مشروع: إدارة ثغرات","تخطيط","تنفيذ","معالجة","تقارير","عرض"),
),
S("مشروع المستوى: تقييم أمني شامل","تطبيق مهارات المستوى",
U("تخطيط التقييم","نطاق","منهجية","أدوات","جدول"),
U("فحص الشبكة","External","Internal","Wireless","تحليل"),
U("فحص الأنظمة","Windows","Linux","Databases","تحليل"),
U("فحص التطبيقات","Web","Mobile","API","تحليل"),
U("اختبار الاختراق","External","Internal","Web","Wireless"),
U("تحليل النتائج","تصنيف","أولوية","تحليل جذري","توصيات"),
U("كتابة التقرير","تنفيذي","تقني","علاجي","عرضي"),
U("العرض النهائي","تحضير","تقديم","توصيات","تقييم"),
),
),
# ═══════════ LEVEL 3 ═══════════
L("المستوى الثالث: اختبار الاختراق المتقدم","Exploitation, Post-Exploitation, Reporting","apply",
S("اختبار الاختراق المتقدم","تقنيات متقدمة في الاستغلال",
U("تجاوز الحماية","AV Evasion","AMSI Bypass","AppLocker Bypass","EDR Evasion","مشروع: Evasion"),
U("استغلال Windows","PowerShell Empire","Covenant","Silver","Mimikatz","Kerberos Attacks","مشروع: Windows"),
U("استغلال Linux","SUID Exploitation","Capabilities","Cron Jobs","Wildcard Injection","Library Hijacking","مشروع: Linux"),
U("استغلال الويب المتقدم","SSRF","XXE","Deserialization","Template Injection","WebSockets","مشروع: Web"),
U("هندسة اجتماعية متقدمة","Spear Phishing","Vishing","Physical Penetration","USB Drops","Reporting","مشروع: Social"),
U("Password Attacks","Brute Force","Password Spraying","Hash Cracking","John/Hashcat","Rainbow Tables","مشروع: Passwords"),
U("Pivoting و Lateral Movement","SSH Tunneling","Port Forwarding","PSExec","WMI","DCOM","مشروع: Pivot"),
U("Data Exfiltration","DNS Tunneling","ICMP Tunneling","HTTP/HTTPS Exfil","Detection Evasion","مشروع: Exfil"),
U("مشروع: APT Simulation","تخطيط","تنفيذ","توثيق","عرض"),
),
S("أمن الشبكات المتقدم","Network Attacks and Defenses",
U("ARP Attacks","ARP Spoofing","ARP Poisoning","Detection","Defenses","مشروع: ARP"),
U("DNS Attacks","DNS Spoofing","DNS Cache Poisoning","DNSSEC","DNS over HTTPS","مشروع: DNS"),
U("Man-in-the-Middle","ARP MitM","DHCP Spoofing","SSL Strip","Detection","مشروع: MitM"),
U("DDoS Attacks","Volumetric","Protocol","Application Layer","Mitigation","مشروع: DDoS"),
U("Network Sniffing","Passive","Active","SSL/TLS Decryption","Detection","مشروع: Sniffing"),
U("VLAN Hopping","Switch Spoofing","Double Tagging","Defenses","مشروع: VLAN"),
U("Wireless Attacks","Deauth","WPA3 Attacks","Rogue AP","Bluetooth","مشروع: Wireless"),
U("Network Forensics","PCAP Analysis","NetworkMiner","Bro/Zeek","Timeline","مشروع: Forensics"),
U("مشروع: محاكاة هجوم","تخطيط","تنفيذ","كشف","تقرير","عرض"),
),
S("استغلال التطبيقات","Web, Mobile, API Exploitation",
U("Web Application Attacks","SSTI","SSRF","Cache Poisoning","HTTP Smuggling","مشروع: Web"),
U("API Attacks","REST Abuse","GraphQL Introspection","Mass Assignment","JWT Attacks","مشروع: API"),
U("Mobile App Testing","Android","iOS","Reverse Engineering","Runtime Manipulation","مشروع: Mobile"),
U("Cloud Security Testing","AWS","Azure","GCP","Serverless Attacks","مشروع: Cloud"),
U("Database Attacks","MSSQL","MySQL","PostgreSQL","Oracle Attacks","NoSQL Injection","مشروع: DB"),
U("Active Directory Attacks","DCSync","DCShadow","AS-REP Roasting","Constrained Delegation","مشروع: AD"),
U("Container Attacks","Docker Escape","K8s API","Image Vulnerabilities","مشروع: Containers"),
U("IoT/OT Attacks","Protocol Analysis","Firmware Analysis","Hardware Hacking","مشروع: IoT"),
U("مشروع: اختبار شامل","تخطيط","هجوم","تقرير","عرض"),
),
S("برمجة أدوات الأمن","Python for Security",
U("Python Basics for Security","المتغيرات","الدوال","القوائم","القواميس","مشروع: أساسيات"),
U("Network Programming","socket","scapy","Packet Crafting","Sniffing","مشروع: شبكة"),
U("Web Automation","requests","BeautifulSoup","Selenium","Burp Extensions","مشروع: ويب"),
U("Password Tools","Hash Generation","Brute Force Script","Dictionary Attack","مشروع: Passwords"),
U("Malware Analysis Basics","Static Analysis","strings","PE Analysis","مشروع: تحليل"),
U("Log Analysis","Regex","Parsing","Correlation","Visualization","مشروع: سجلات"),
U("API Integration","VirusTotal","Shodan","HaveIBeenPwned","AlienVault OTX","مشروع: APIs"),
U("Building Security Tools","Port Scanner","Directory Bruter","Keylogger Detector","مشروع: أداة"),
U("مشروع: أداة أمنية","تصميم","تطوير","اختبار","توثيق","عرض"),
),
S("تحليل البرمجيات الخبيثة","Malware Analysis Fundamentals",
U("أنواع البرمجيات الخبيثة","Virus, Worm, Trojan","Ransomware","Spyware, Adware","Rootkit, Bootkit","Fileless","مشروع: تصنيف"),
U("Static Analysis","Hashing","Strings","PE Headers","Imports/Exports","Capabilities","مشروع: Static"),
U("Dynamic Analysis","Sandbox","Process Monitor","Registry Changes","Network Activity","مشروع: Dynamic"),
U("Code Analysis","Disassembly","Decompilation","x86/x64 Basics","Debugging","مشروع: Code"),
U("Packing and Obfuscation","Packers","Cryptors","Unpacking","Deobfuscation","مشروع: Unpacking"),
U("Reverse Engineering","IDA Pro","Ghidra","x64dbg","Radare2","مشروع: RE"),
U("Ransomware Analysis","Encryption Methods","Payment Systems","Decryption","Prevention","مشروع: Ransomware"),
U("YARA Rules","Rule Writing","Testing","Sharing","Automation","مشروع: YARA"),
U("مشروع: تحليل عينة","Static","Dynamic","Report","IOCs","عرض"),
),
S("الاستجابة للحوادث Incident Response","منهجية واحترافية",
U("IR Frameworks","NIST SP 800-61","SANS PICERL","Preparation","Playbooks","مشروع: Framework"),
U("Detection and Analysis","SIEM Alerts","EDR Alerts","User Reports","Triage","مشروع: Detection"),
U("Containment","Short-term","Long-term","Network Isolation","System Isolation","مشروع: Containment"),
U("Eradication","Root Cause","Malware Removal","Patch","Rebuild","مشروع: Eradication"),
U("Recovery","System Restoration","Monitoring","Verification","Return to Operations","مشروع: Recovery"),
U("Post-Incident","Lessons Learned","Report","Metrics","Process Improvement","مشروع: Post"),
U("IR Tools","TheHive","Cortex","MISP","Velociraptor","مشروع: أدوات"),
U("Tabletop Exercises","Scenario Design","Facilitation","Assessment","Improvement","مشروع: Tabletop"),
U("مشروع: IR Plan","Assessment","Design","Document","Test","عرض"),
),
S("مشروع المستوى:Red Team","محاكاة هجوم شامل",
U("تخطيط العملية","Objectives","Rules of Engagement","Team","Timeline"),
U("Reconnaissance","OSINT","Network","Social","Physical"),
U("Initial Access","Phishing","Exploitation","Credentials","Physical"),
U("Post-Exploitation","Persistence","Privilege Escalation","Lateral Movement","Data Access"),
U("Achieve Objectives","Data Exfil","Impact","Cover Tracks","Exit"),
U("Detection Analysis","What was caught?","What was missed?","Why?","Gaps"),
U("كتابة التقرير","Executive","Technical","Purple Team","Recommendations"),
U("عرض","Findings","Demos","Lessons","Roadmap"),
),
),
# ═══════════ LEVEL 4 ═══════════
L("المستوى الرابع: الدفاع والحماية","SOC, SIEM, Threat Hunting, Digital Forensics","analyze",
S("مركز العمليات الأمنية SOC","بناء وإدارة SOC",
U("SOC Fundamentals","Mission","Tiers","Metrics","Shift Management","مشروع: SOC"),
U("SIEM","Splunk","ELK","QRadar","Use Cases","Correlation Rules","مشروع: SIEM"),
U("SOAR","Playbooks","Automation","Phantom","Demisto","مشروع: SOAR"),
U("Alert Triage","Prioritization","False Positive Analysis","Escalation","SLA","مشروع: Triage"),
U("Threat Detection","Sigma Rules","Detection Engineering","MITRE ATT&CK Mapping","مشروع: Detection"),
U("Incident Handling in SOC","Classification","Investigation","Closure","Handover","مشروع: Handling"),
U("SOC Metrics","MTTD","MTTR","Alert Volume","Coverage","Reporting","مشروع: Metrics"),
U("Purple Teaming","Red vs Blue","Adversary Emulation","Detection Validation","مشروع: Purple"),
U("مشروع: بناء SOC","تخطيط","أدوات","عمليات","مقاييس","عرض"),
),
S("Threat Hunting","البحث الاستباقي عن التهديدات",
U("Threat Hunting Fundamentals","Hypothesis-driven","Intel-driven","Data-driven","Methodology","مشروع: أساسيات"),
U("Hunt Platforms","Splunk","ELK","Kibana","Jupyter","مشروع: منصة"),
U("Endpoint Hunting","Process Trees","Registry","Scheduled Tasks","WMI","مشروع: Endpoint"),
U("Network Hunting","Flow Analysis","DNS Analysis","Proxy Logs","VPN Logs","مشروع: Network"),
U("MITRE ATT&CK in Hunting","Tactics","Techniques","Sub-techniques","Coverage","مشروع: ATT&CK"),
U("Developing Hunt Hypotheses","Intelligence","TTPs","Environment","Automation","مشروع: Hypotheses"),
U("Data Analysis for Hunters","SQL","Python","Visualization","Statistics","مشروع: Analysis"),
U("Hunt Reporting","Findings","Remediation","Detection Gaps","Improvement","مشروع: Report"),
U("مشروع: Hunt عملية","فرضية","بحث","تحليل","نتائج","عرض"),
),
S("Digital Forensics متقدم","تحقيق متقدم",
U("Disk Forensics","FTK Imager","EnCase","Autopsy","Sleuth Kit","مشروع: Disk"),
U("Memory Forensics","Volatility","Rekall","Process Analysis","Network Connections","مشروع: Memory"),
U("Mobile Forensics","iOS","Android","Cellebrite","Oxygen","مشروع: Mobile"),
U("Network Forensics","PCAP Deep Dive","Protocol Analysis","Session Reconstruction","مشروع: Network"),
U("Cloud Forensics","AWS","Azure","GCP","Log Collection","مشروع: Cloud"),
U("Malware Forensics","Behavioral Analysis","C2 Communication","Persistence Mechanisms","مشروع: Malware"),
U("Timeline Analysis","Super Timelines","Plaso","Log2Timeline","Correlation","مشروع: Timeline"),
U("Expert Witness","Court Preparation","Evidence Presentation","Cross-Examination","مشروع: Expert"),
U("مشروع: تحقيق شامل","سيناريو","جمع","تحليل","تقرير","عرض"),
),
S("هندسة الأمن Security Architecture","تصميم أنظمة آمنة",
U("Security Architecture Principles","Defense in Depth","Least Privilege","Separation of Duties","Fail Secure","مشروع: Principles"),
U("Identity and Access Management","IAM Architecture","SSO","Federation","PAM","IGA","مشروع: IAM"),
U("Network Security Architecture","Segmentation","Micro-segmentation","SDA","SASE","مشروع: Network"),
U("Cloud Security Architecture","Shared Responsibility","CASB","CSPM","CWPP","مشروع: Cloud"),
U("Application Security Architecture","Threat Modeling","Security Patterns","API Gateway","WAF","مشروع: App"),
U("Data Security Architecture","Classification","DLP","Encryption","Key Management","مشروع: Data"),
U("Endpoint Security Architecture","EDR","XDR","MDM","BYOD","مشروع: Endpoint"),
U("Security Review Process","Architecture Review","Threat Model","Risk Assessment","Recommendations","مشروع: Review"),
U("مشروع: تصميم معماري","Requirements","Design","Review","Document","عرض"),
),
S("إدارة المخاطر والامتثال","Risk Management and Compliance",
U("Enterprise Risk Management","ISO 31000","NIST RMF","FAIR","Risk Register","مشروع: ERM"),
U("Information Security Risk","Asset-based","Threat-based","Vulnerability-based","Quantitative","مشروع: ISRM"),
U("ISO 27001","ISMS","Annex A","Controls","Certification","مشروع: ISO"),
U("PCI-DSS","Requirements","SAQ","ROC","Compliance","مشروع: PCI"),
U("GDPR","Principles","Data Subject Rights","DPIA","Breach Notification","مشروع: GDPR"),
U("SOC 2","Trust Services Criteria","Type I vs II","Audit","مشروع: SOC2"),
U("Audit Management","Internal Audit","External Audit","Evidence Collection","Findings","مشروع: Audit"),
U("Third-Party Risk","Vendor Assessment","Due Diligence","Continuous Monitoring","مشروع: TPRM"),
U("مشروع: تقييم امتثال","Scope","Assessment","Findings","Report","عرض"),
),
S("برمجة أدوات الأمن المتقدمة","Advanced Security Tool Development",
U("C2 Frameworks","Architecture","Custom Agents","Encryption","Evasion","مشروع: C2"),
U("Automation Frameworks","Ansible Security","Terraform Security","Python Automation","CI/CD","مشروع: Automation"),
U("Browser Extensions","Chrome","Firefox","Security Features","Development","مشروع: Extension"),
U("Sysinternals Suite","Process Explorer","Autoruns","Procmon","TCPView","مشروع: Sysinternals"),
U("EDR Development","Kernel Callbacks","ETW","Minifilter","User-mode Hooking","مشروع: EDR"),
U("Network Tool Development","Packet Crafting","Protocol Fuzzing","Scanner Development","مشروع: Network"),
U("API Development","Flask/FastAPI","Authentication","Rate Limiting","Logging","مشروع: API"),
U("Testing and Deployment","Unit Tests","Integration Tests","CI/CD","Documentation","مشروع: Testing"),
U("مشروع: أداة أمنية","تصميم","تطوير","اختبار","نشر","عرض"),
),
S("مشروع المستوى: برنامج أمني","بناء برنامج أمني متكامل",
U("Assessment","Current State","Gap Analysis","Maturity","Priorities"),
U("Strategy","Vision","Mission","Roadmap","KPIs"),
U("Governance","Policies","Standards","Procedures","Roles"),
U("Technology","Tool Selection","Architecture","Integration","Automation"),
U("Operations","SOC","IR","VM","TI"),
U("Awareness","Training","Phishing","Culture","Metrics"),
U("Budget","Cost Estimation","ROI","Vendor Management"),
U("Presentation","Board","Stakeholders","Roadmap","Q&A"),
),
),
# ═══════════ LEVEL 5 ═══════════
L("المستوى الخامس: القيادة والتخصص","Security Leadership, Strategy, Advanced Topics","create",
S("قيادة الأمن السيبراني","CISO, Strategy, Communication",
U("CISO Role","Responsibilities","Board Communication","Strategy","مشروع: CISO"),
U("Security Strategy","Business Alignment","Risk Appetite","Roadmap","KPIs","مشروع: Strategy"),
U("Budget and Resources","Budget Planning","ROI","Headcount","Outsourcing","مشروع: Budget"),
U("Board Communication","Reporting","Metrics","Business Language","مشروع: Board"),
U("Team Building","Hiring","Development","Retention","Culture","مشروع: Team"),
U("Vendor Management","Selection","Contract","SLA","Performance","مشروع: Vendor"),
U("Mergers and Acquisitions","Due Diligence","Integration","Divestiture","مشروع: M&A"),
U("Crisis Management","Crisis Team","Communication","Decision Making","Recovery","مشروع: Crisis"),
U("مشروع: خطة استراتيجية","Assessment","Strategy","Roadmap","Metrics","عرض"),
),
S("استخبارات التهديدات Threat Intelligence","CTI, Analysis, Sharing",
U("CTI Fundamentals","Strategic","Operational","Tactical","Technical","مشروع: CTI"),
U("CTI Collection","OSINT","Dark Web","HUMINT","Commercial Feeds","مشروع: Collection"),
U("CTI Analysis","Diamond Model","Kill Chain","MITRE ATT&CK","Campaign Tracking","مشروع: Analysis"),
U("CTI Production","Reports","Feeds","IOCs","TTPs","مشروع: Production"),
U("CTI Dissemination","Tactical","Operational","Strategic","Automated","مشروع: Dissemination"),
U("Threat Intelligence Platforms","MISP","OpenCTI","Anomali","ThreatConnect","مشروع: TIP"),
U("CTI in SOC","Alert Enrichment","Hunt Hypotheses","Detection Engineering","مشروع: SOC"),
U("Information Sharing","ISACs","CERTs","Trust Groups","Legal","مشروع: Sharing"),
U("مشروع: CTI Program","Design","Collection","Analysis","Production","عرض"),
),
S("هندسة الأمن المتقدمة","Zero Trust, SASE, Cloud Native",
U("Zero Trust Architecture","NIST SP 800-207","ZTA Pillars","Implementation","مشروع: ZTA"),
U("SASE","SD-WAN","SWG","CASB","ZTNA","FWaaS","مشروع: SASE"),
U("Cloud Native Security","Kubernetes Security","Service Mesh","Serverless Security","IaC Scanning","مشروع: CloudNative"),
U("DevSecOps","Shift Left","SAST/DAST in CI/CD","Container Scanning","Infra Scanning","مشروع: DevSecOps"),
U("Identity as Perimeter","Passwordless","FIDO2","Continuous Authentication","Risk-based","مشروع: Identity"),
U("Data-Centric Security","Classification","DLP","IRM","CASB","مشروع: Data"),
U("AI in Security","ML for Detection","UEBA","SOAR ML","Adversarial AI","مشروع: AI"),
U("OT/ICS Security","Purdue Model","ISA/IEC 62443","Safety","Segmentation","مشروع: OT"),
U("مشروع: تصميم ZTA","Assessment","Design","Pilot","Roadmap","عرض"),
),
S("التحقيق الرقمي المتقدم","Advanced Forensics and eDiscovery",
U("Enterprise Forensics","Enterprise Tools","Collection at Scale","Automation","مشروع: Enterprise"),
U("eDiscovery","EDRM","Legal Hold","Collection","Review","Production","مشروع: eDiscovery"),
U("Database Forensics","MSSQL","Oracle","MySQL","Transaction Logs","مشروع: DB"),
U("Cloud Forensics Deep Dive","AWS Forensics","Azure Forensics","GCP Forensics","SaaS","مشروع: Cloud"),
U("Memory Forensics Deep Dive","Volatility Plugins","Rekall Scripts","Custom Analysis","مشروع: Memory"),
U("Anti-Forensics","Timestomping","Log Wiping","Encryption","Steganography","Countermeasures","مشروع: Anti"),
U("Forensic Readiness","Planning","Logging","Evidence Handling","Testing","مشروع: Readiness"),
U("Expert Witness Advanced","Report Writing","Deposition","Testimony","Qualification","مشروع: Expert"),
U("مشروع: تحقيق مؤسسي","Scenario","Collection","Analysis","Report","Testimony"),
),
S("إدارة الأزمات والاستمرارية","BCP, DR, Crisis Management",
U("Business Continuity","BIA","Strategy","Plan","Testing","مشروع: BCP"),
U("Disaster Recovery","RTO","RPO","Failover","Failback","Testing","مشروع: DR"),
U("Crisis Management Plan","Crisis Team","Communication","Command Center","مشروع: CMP"),
U("Cyber Insurance","Coverage","Assessment","Claims","Underwriting","مشروع: Insurance"),
U("Tabletop Exercises","Scenario Design","Facilitation","After Action","Improvement","مشروع: TTX"),
U("Ransomware Response","Preparation","Detection","Containment","Recovery","Negotiation","مشروع: Ransomware"),
U("Supply Chain Attacks","SolarWinds Case","Dependency Analysis","Vendor Assessment","مشروع: Supply Chain"),
U("Lessons Learned","Post-Incident Review","Root Cause","Process Improvement","مشروع: Lessons"),
U("مشروع: BCP/DR Plan","Assessment","Strategy","Document","Test","عرض"),
),
S("أخلاقيات وقانون الأمن السيبراني","Ethics, Law, Privacy",
U("Computer Crime Laws","CFAA","Computer Misuse Act","Local Laws","Jurisdiction","مشروع: Laws"),
U("Privacy Regulations","GDPR","CCPA","HIPAA","Cross-border","مشروع: Privacy"),
U("Ethical Hacking Ethics","Scope","Authorization","Responsible Disclosure","Bug Bounty","مشروع: Ethics"),
U("Intellectual Property","Trade Secrets","Copyright","Patents","DMCA","مشروع: IP"),
U("Evidence and Courts","Admissibility","Chain of Custody","Expert Testimony","Rules of Evidence","مشروع: Evidence"),
U("Surveillance and Privacy","Government Surveillance","Workplace Monitoring","Encryption Debate","مشروع: Surveillance"),
U("AI Ethics in Security","Bias in AI","Explainability","Autonomous Decisions","Accountability","مشروع: AI Ethics"),
U("Professional Ethics","Codes of Conduct","Whistleblowing","Conflicts","Continuous Learning","مشروع: Professional"),
U("مشروع: Ethics Review","Case Study","Analysis","Recommendations","Presentation","عرض"),
),
S("المشروع الختامي","برنامج أمني متكامل",
U("Assessment","Current State","Maturity","Threat Landscape","Priorities"),
U("Strategy","Vision","Mission","Objectives","KPIs"),
U("Architecture","People","Process","Technology","Roadmap"),
U("Implementation Plan","Quick Wins","Projects","Timeline","Resources"),
U("Policies","Review","Gap Analysis","Creation","Approval"),
U("Training Plan","Awareness","Technical","Executives","Metrics"),
U("Metrics and Reporting","Board Dashboard","Operational Metrics","Improvement","Budget"),
U("Final Presentation","Executive Summary","Roadmap","Q&A","Approval"),
),
),
]

MISTAKES = [
("Data Leakage","Scaler قبل التقسيم = اختبار يتسرب = دقة وهمية.","اقسم أولاً. scaler.fit(X_train). scaler.transform(X_test).","Pipeline يمنع Data Leakage تلقائياً.","critical"),
("Overfitting","دقة تدريب 99%، اختبار 65%. النموذج حفظ ولم يتعلم.","تبسيط، Regularization، CV، EarlyStopping.","افحص الفجوة بين train و test.","critical"),
("إهمال التحديثات","ثغرة معروفة غير مصححة = باب مفتوح للمخترق.","جدول تحديثات منتظم. اختبار التحديثات قبل النشر.","معظم الاختراقات تستغل ثغرات معروفة تم إصدار تحديث لها.","critical"),
("كلمات مرور ضعيفة","password123 = اختراق في ثوان.","12+ حرف، أحرف كبيرة وصغيرة، أرقام، رموز. مدير كلمات مرور.","لا تكرر كلمة المرور بين الحسابات. MFA دائماً.","critical"),
("إهمال النسخ الاحتياطي","Ransomware = كل شيء يضيع.","قاعدة 3-2-1: ثلاث نسخ، وسيطين، نسخة خارج الموقع.","اختبر استعادة البيانات شهرياً.","critical"),
("عدم استخدام MFA","كلمة مرور مسربة = حساب مخترق.","فعل MFA على كل الحسابات المهمة.","MFA يمنع 99% من هجمات الحسابات.","major"),
("صلاحيات زائدة","مستخدم بصلاحيات مدير = كارثة محتملة.","مبدأ الصلاحيات الدنيا. مراجعة دورية للصلاحيات.","اعطِ كل مستخدم فقط ما يحتاجه.","major"),
("تجاهل السجلات","اختراق يحدث ولا أحد يعلم.","فعل logging. راجع السجلات دورياً.","السجلات هي عيونك على النظام.","major"),
]

def mb(p,c):return[f"الآن أتقنتَ {p}، نرتقي إلى {c}.",f"في الدرس السابق فككنا {p}. اليوم نبني عليه بـ {c}.",f"بعد {p}، {c} يسد الفجوة التالية.",f"{p} كان الأساس. {c} هو الطابق التالي.",][h(p+c)%4]

def gl(uc,lt,sn):
 ls=[];pv="المفاهيم الأساسية"
 for li,t in enumerate(lt,1):
  nm=2+(h(f"{uc}_{li}")%2);lm=[{"mistake":f"{m[0]}\n{m[1]}","correction":m[2],"treatment":m[3],"severity":m[4]} for m in [MISTAKES[(h(f"{uc}_{li}_{mi}"))%len(MISTAKES)] for mi in range(nm)]]
  ls.append({"lesson_index":li,"name":t,"goal":f"فهم وتطبيق {t}","bridge_sentence":mb(pv,t),"prerequisite_lessons":[] if li==1 else [f"{uc}.{li-1}"],"enables_lessons":[] if li==len(lt) else [f"{uc}.{li+1}"],"final_check_question":f"اشرح {t} بكلماتك. خطوات تطبيقه؟ أشهر خطأ؟","session_complete_criterion":f"يشرح {t} ويطبقه عملياً","yemeni_examples":[f"تطبيق عملي: {t}."],"expected_duration_minutes":30,"estimated_gem_cost":90,"solution_outline":f"خطوات {t}:\n1. فهم الأساس\n2. تطبيق عملي\n3. التجربة\n4. تحليل النتائج\n5. توثيق","motivation_hook":f"{t} — مهارة أساسية في الأمن السيبراني.","learning_objectives":[{"statement":f"يفهم {t}","bloom_level":"understand"},{"statement":f"يطبق {t}","bloom_level":"apply"}],"glossary":[],"concepts":[{"name":t,"explanation":f"شرح وتطبيق عملي لـ {t} في سياق {sn}.","mastery_criterion":f"يشرح {t} ويطبقه","weight":1}],"common_mistakes":lm});pv=t
 return ls

def glab(uc,un,nl):
 return[{"lab_index":li,"title":f"معمل {un}: {'التشخيص' if li==1 else 'التطبيق'}","scenario":f"مشكلة في {un}. حللها.","completion_criterion":f"تحليل وحل","pedagogical_sequence":"diagnostic -> decision -> application -> analysis -> connection","prerequisite_lessons":[f"{uc}.{max(1, nl//2)}"],"allowed_tools":["text","code"],"questions":[{"kind":"diagnostic","prompt":f"خطوات تشخيص مشكلة في {un}؟","rubric":"ذكر 4 خطوات منطقية مع شرح","solution_outline":"جمع وتحليل وتحديد واقتراح","points":1},{"kind":"decision","prompt":f"خياران لحل في {un}. معاييرك؟","rubric":"ذكر معيارين مع تبرير","solution_outline":"الدقة والسرعة والتعقيد","points":1},{"kind":"application","prompt":f"اكتب كوداً يطبق {un}.","rubric":"كود صحيح يعمل","solution_outline":"استيراد وتطبيق","points":2},{"kind":"analysis","prompt":f"كود لـ {un} فيه 3 أخطاء.","rubric":"3 أخطاء مع تصحيح","solution_outline":"تحليل وتصحيح","points":1},{"kind":"connection","prompt":f"اربط {un} بمهارات سابقة.","rubric":"رابطان مع فكرة","solution_outline":"الربط وخطة","points":1}]} for li in range(1,3)]

def ge(c,s,n=10):
 q=[("مثلث CIA:",["السرية والسلامة والتوفر","تشفير فقط","جدار حماية","نسخ احتياطي"],0,1,"الركائز الثلاث للأمن."),("جدار الحماية:",["يراقب ويتحكم بالحركة","يسرع الإنترنت","يخزن البيانات","يشفر"],0,1,"حاجز بين الشبكة الداخلية والخارجية."),("Phishing:",["هجوم تصيد","فيروس","جدار حماية","تشفير"],0,1,"خداع المستخدمين للحصول على بيانات."),("نظام IDS:",["يكتشف التسلل","يمنع التسلل","يشفر","يسرع"],0,1,"Intrusion Detection System."),("SQL Injection:",["حقن استعلامات","تشفير","نسخ احتياطي","جدار"],0,1,"ثغرة في تطبيقات الويب."),("شبكة VPN:",["شبكة افتراضية آمنة","فيروس","متصفح","بروتوكول"],0,1,"نفق مشفر للاتصال."),("Ransomware:",["برنامج فدية","جدار","مضاد","شهادة"],0,1,"يشفر الملفات ويطلب فدية."),("تقنية MFA:",["مصادقة متعددة العوامل","جدار","فيروس","تشفير"],0,1,"طبقة حماية إضافية.")]
 vv=[]
 for v in range(3):vv.append([{"question_index":qi+1,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {ch}" for ci,ch in enumerate(c)],"correct_index":ci,"explanation":e,"difficulty":d,"points":1,"time_limit_seconds":60+d*30} for qi,(p,c,ci,d,e) in enumerate([q[(h(f"{s}_{v}_{qi}"))%len(q)] for qi in range(n)])])
 return{"code":s,"scope":c,"variants":vv}

def gp():
 q=[(1,"مثلث CIA:",["السرية والسلامة والتوفر","تشفير","جدار","نسخ"],0,1),(2,"SQL Injection:",["حقن استعلامات","تشفير","نسخ","جدار"],0,2),(3,"شبكة VPN:",["شبكة آمنة","فيروس","متصفح","بروتوكول"],0,2),(4,"مركز SOC:",["مركز عمليات أمنية","مضاد","جدار","بروتوكول"],0,2),(5,"Zero Trust:",["لا تثق بأحد","جدار","فيروس","تشفير"],0,3)]
 return[{"target_level_index":l,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {c}" for ci,c in enumerate(c)],"correct_index":ci,"difficulty":d,"explanation":f"مستوى {l}"} for l,p,c,ci,d in q]*2  # 10 questions by duplicating

def main():
 print(f"\n{'='*60}\n  uni-cybersecurity — الأمن السيبراني\n{'='*60}\n")
 mt={"slug":"uni-cybersecurity","name":"أمن سيبراني","icon":"🛡️","desc":"منهج متكامل: من أساسيات الأمن إلى القيادة والاستراتيجية.","scope":"professional_track","language":"ar","region":"YE","target_persona":"طالب يريد احتراف الأمن السيبراني.","teacher_tone":"يقظة وتحليلية.","viz":["flowchart","network_diagram","architecture_diagram","attack_tree"],"tools":["text","code","image"],"glossary":[{"term":"CIA Triad","definition":"السرية والسلامة والتوفر"}]}
 rl=[];au=[];asc=[]
 for li,(ln,lg,lb,ss) in enumerate(CURRICULUM):
  lv=li+1;rs=[]
  for si,(sn,sg,us) in enumerate(ss):
   sv=si+1;sc=f"{lv}.{sv}";asc.append(sc);ru=[]
   for ui,(un,lt) in enumerate(us):
    lt=[t for t in lt if t and len(t)>=3];uv=ui+1;uc=f"{sc}.{uv}";au.append(uc)
    ls=gl(uc,lt,sn);la=glab(uc,un,len(ls))
    pr=[f"{sc}.{ui}"] if ui>0 else[];en=[f"{sc}.{ui+2}"] if ui<len(us)-1 else[]
    g=f"إتقان {un}";g=g if len(g)>=10 else f"إتقان {un} بشكل متقن"
    ru.append({"unit_index":uv,"name":un,"goal":g,"prerequisite_units":pr,"enables_units":en,"key_concepts":[lt[0][:20]],"motivation_hook":f"وحدة {un} — خطوتك نحو الاحتراف.","learning_objectives":[{"statement":f"يتقن {un}","bloom_level":"apply"}],"lessons":ls,"labs":la,"exam":{"pass_threshold_percent":60,"points":10,"time_limit_minutes":30}})
    print(f"  {uc}: {un[:50]} ({len(lt)} دروس)")
   rs.append({"stage_index":sv,"name":sn,"goal":sg,"bloom_focus":lb,"units":ru,"exam":{"pass_threshold_percent":60,"points":20,"time_limit_minutes":45}})
  rl.append({"level_index":lv,"name":ln,"goal":lg,"bloom_focus":lb,"stages":rs,"exam":{"pass_threshold_percent":60,"points":50,"time_limit_minutes":90}})
 print("\n  بنوك الامتحانات...")
 ub={c:ge(c,"unit",10) for c in au}
 sb={c:ge(c,"stage",15) for c in asc}
 lb={str(i):ge(str(i),"level",20) for i in range(1,len(rl)+1)}
 fn={"schema_version":"v4.1","specialty":{**mt,"yemeni_examples":["تطبيق عملي"]},"levels":rl,"exam_banks":{"unit_banks":ub,"stage_banks":sb,"level_banks":lb},"placement_test_questions":gp(),"publish_notes":"uni-cybersecurity — تسلسل منطقي"}
 fp=OUT/"final.json"
 with open(fp,'w',encoding='utf-8') as f:json.dump(fn,f,ensure_ascii=False,indent=2)
 sz=fp.stat().st_size/(1024*1024);tl=sum(1 for l in rl for s in l['stages'] for u in s['units'] for _ in u['lessons'])
 print(f"\n  ✅ {sz:.1f} MB | {len(rl)} مستويات | {tl} درس\n")
if __name__=="__main__":main()
