#!/usr/bin/env python3
"""uni-it - تقنية المعلومات - تسلسل منطقي - مستوى 1"""
import json; from pathlib import Path; import random
random.seed(42)
def h(s): return sum(ord(c)*(i+1) for i,c in enumerate(str(s)))
OUT = Path("out/uni-it"); OUT.mkdir(parents=True, exist_ok=True)
def U(n,*l): return (n,list(l))
def S(n,g,*u): return (n,g,list(u))
def L(n,g,b,*s): return (n,g,b,list(s))

CURRICULUM = [
L("المستوى الأول: أساسيات الحاسوب وتقنية المعلومات","فهم مكونات الحاسوب، أنظمة التشغيل، الشبكات، الإنترنت، البرمجيات","understand",
S("مكونات الحاسوب ووظائفها","التعرف على كل مكون مادي وفهم وظيفته",
U("اللوحة الأم والمعالج CPU",
"ما هي اللوحة الأم؟ اللوحة التي تربط كل شيء","مكونات اللوحة الأم: المقابس والفتحات والمنافذ","شرائح اللوحة: Northbridge و Southbridge","ما هو المعالج CPU؟ عقل الحاسوب","مكونات المعالج: ALU, CU, Registers","سرعة المعالج: GHz وماذا تعني","أنوية المعالج: Single, Dual, Multi-core","ذاكرة التخزين المؤقت Cache: L1, L2, L3","كيف تختار اللوحة الأم والمعالج المناسبين","مشروع: خطط لترقية حاسوب"),
U("الذاكرة: RAM و ROM",
"ما هي الذاكرة؟ التخزين المؤقت فائق السرعة","RAM: ذاكرة الوصول العشوائي","أنواع RAM: DDR3, DDR4, DDR5","سعة الذاكرة: GB ومعناها العملي","سرعة الذاكرة: MHz وتأثيرها على الأداء","ROM و BIOS: الذاكرة الدائمة للتعليمات","الذاكرة الافتراضية Virtual Memory","كيف تختار الذاكرة المناسبة لجهازك","أعراض نقص الذاكرة وكيف تشخصها","مشروع: ترقية RAM لجهازك"),
U("التخزين: HDD, SSD, NVMe",
"ما هو التخزين؟ الذاكرة الدائمة للبيانات","HDD: القرص الصلب التقليدي","SSD: قرص الحالة الصلبة","NVMe: الجيل الأسرع من SSD","مقارنة HDD vs SSD vs NVMe","سعة التخزين: GB, TB","سرعة القراءة والكتابة","كيف تختار قرص التخزين المناسب","تنظيم وتقسيم القرص الصلب Partitions","مشروع: ترقية تخزين جهازك"),
U("بطاقة الشاشة وأنواعها",
"ما هي بطاقة الشاشة GPU؟","بطاقة مدمجة Integrated vs منفصلة Dedicated","ذاكرة الفيديو VRAM","دقة العرض: HD, Full HD, 4K","معدل الإطارات FPS","منافذ الفيديو: HDMI, DisplayPort, VGA","بطاقات NVIDIA vs AMD","كيف تختار بطاقة الشاشة المناسبة","تثبيت وتحديث تعريفات بطاقة الشاشة","مشروع: ترقية بطاقة الشاشة"),
U("وحدات الإدخال والإخراج",
"ما هي وحدات الإدخال؟","لوحة المفاتيح: أنواعها وميزاتها","الفأرة: أنواعها ودقتها","الشاشة: أنواعها وتقنياتها","الطابعة: أنواعها وطرق عملها","الماسح الضوئي Scanner","الميكروفون والسماعات وكاميرا الويب","أجهزة الإدخال المتخصصة","كيف تختار وحدات الإدخال المناسبة","مشروع: جهز محطة عمل كاملة"),
U("المنافذ والتوصيلات",
"ما هي المنافذ؟ نقاط اتصال الأجهزة","USB: الأنواع والإصدارات","USB-C: المنفذ الموحد الحديث","HDMI و DisplayPort","Ethernet RJ45","مقبس الصوت 3.5mm","Thunderbolt","Bluetooth و WiFi: اتصال لاسلكي","كيف تتعرف على المنافذ في جهازك","مشروع: خريطة منافذ جهازك"),
U("تجميع حاسوب مكتبي خطوة بخطوة",
"الأدوات المطلوبة للتجميع","خطوة 1: تركيب المعالج على اللوحة الأم","خطوة 2: تركيب نظام التبريد","خطوة 3: تركيب الذاكرة RAM","خطوة 4: تركيب اللوحة الأم في الصندوق","خطوة 5: تركيب القرص الصلب","خطوة 6: تركيب بطاقة الشاشة","خطوة 7: تركيب مزود الطاقة","خطوة 8: توصيل الكيبلات والكابلات","التشغيل الأول واختبار BIOS"),
U("صيانة الحاسوب واستكشاف الأعطال",
"أساسيات الصيانة الوقائية","تنظيف الحاسوب من الغبار","مراقبة درجات الحرارة","تحديث BIOS و UEFI","تشخيص مشاكل الذاكرة","تشخيص مشاكل القرص الصلب","تشخيص مشاكل الشاشة","تشخيص مشاكل الطاقة","أدوات فحص الأعطال","مشروع: صيانة دورية كاملة"),
U("مشروع: خطط وجهز جهازاً مثالياً",
"تحديد الاحتياجات: ماذا ستستخدم الجهاز له؟","تحديد الميزانية","اختيار المعالج المناسب","اختيار اللوحة الأم المتوافقة","اختيار الذاكرة والتخزين","اختيار بطاقة الشاشة","اختيار مزود الطاقة والصندوق","تجميع الجهاز واختباره","تثبيت نظام التشغيل والبرامج","تقييم المشروع"),
),
S("أنظمة التشغيل","فهم وإتقان Windows و Linux",
U("ما هو نظام التشغيل؟",
"تعريف نظام التشغيل OS","الوظائف الأساسية لنظام التشغيل","أنواع أنظمة التشغيل","Windows: التاريخ والمميزات","Linux: المصدر المفتوح والتوزيعات","macOS: نظام Apple","أنظمة التشغيل للجوال","أي نظام تختار؟","تثبيت نظام التشغيل","مشروع: اكتشف نظامك"),
U("Windows: تثبيت وإدارة",
"متطلبات تثبيت Windows","خطوات التثبيت خطوة بخطوة","سطح المكتب وقائمة ابدأ","لوحة التحكم والإعدادات","تحديث Windows","إدارة البرامج في Windows","إدارة حسابات المستخدمين","استعادة النظام","مشروع: إعادة تثبيت Windows"),
U("Linux: الأوامر الأساسية",
"ما هو Linux؟","توزيعات Linux: Ubuntu, Debian, Fedora","تثبيت Ubuntu","سطر الأوامر Terminal","أوامر الملفات: ls, cd, mkdir, rm","أوامر النظام: ps, top, kill","إدارة الحزم: apt, apt-get","الصلاحيات: chmod, chown","مشروع: إعداد خادم Linux"),
U("إدارة الملفات والمجلدات",
"هيكل نظام الملفات","إنشاء وتنظيم المجلدات","نسخ ونقل وحذف الملفات","البحث عن الملفات","ضغط وفك ضغط الملفات","مشاركة الملفات","النسخ الاحتياطي","استعادة الملفات المحذوفة","مشروع: تنظيم ملفاتك"),
U("تثبيت وإزالة البرامج",
"أنواع البرامج وتنسيقاتها","تحميل البرامج بأمان","تثبيت البرامج على Windows","تثبيت البرامج على Linux","إزالة البرامج بشكل نظيف","تحديث البرامج","البرامج المحمولة Portable","البرامج مفتوحة المصدر","مشروع: جهز مجموعة برامجك"),
U("إدارة حسابات المستخدمين",
"أنواع الحسابات: مدير، مستخدم، ضيف","إنشاء حسابات جديدة","كلمات المرور الآمنة","الصلاحيات والتحكم بالوصول","الرقابة الأبوية","حذف وتعطيل الحسابات","سياسات كلمات المرور","المصادقة الثنائية","مشروع: إدارة حسابات عائلية"),
U("مدير المهام ومراقبة الأداء",
"Task Manager في Windows","System Monitor في Linux","مراقبة استخدام CPU","مراقبة استخدام RAM","مراقبة القرص الصلب","مراقبة الشبكة","البرامج التي تبدأ مع النظام","إنهاء البرامج المتجمدة","مشروع: حل مشكلة بطء الجهاز"),
U("استكشاف الأعطال وإصلاحها",
"منهجية استكشاف الأعطال","الجهاز لا يعمل: ماذا تفعل؟","الشاشة الزرقاء Blue Screen","توقف البرامج عن الاستجابة","مشاكل الاتصال بالإنترنت","مشاكل الصوت","مشاكل الطباعة","استخدام Safe Mode","مشروع: تشخيص وإصلاح"),
U("مشروع: جهز بيئة عمل احترافية",
"تخطيط بيئة العمل","تثبيت نظام التشغيل","تثبيت البرامج الأساسية","إعداد الحسابات والصلاحيات","تكوين الشبكة","إعداد النسخ الاحتياطي","اختبار البيئة","توثيق الإعدادات","عرض المشروع"),
),
S("الشبكات الأساسية","فهم الشبكات وبروتوكولاتها",
U("ما هي الشبكة؟",
"تعريف الشبكة","LAN: الشبكة المحلية","WAN: الشبكة الواسعة","الإنترنت: شبكة الشبكات","فوائد الشبكات","طبولوجيا الشبكة","أنواع الشبكات","مشروع: ارسم شبكتك"),
U("أجهزة الشبكات",
"الراوتر Router","السويتش Switch","Access Point","المودم Modem","جدار الحماية Firewall","مكرر الإشارة Repeater","مقارنة الأجهزة","مشروع: تعرف على أجهزتك"),
U("الكيبلات والوسائط",
"Ethernet: كيبل نحاسي","الألياف البصرية Fiber","واي فاي WiFi","Bluetooth","مقارنة الوسائط","أدوات التوصيل","مشروع: اختر الوسيط المناسب"),
U("نموذج OSI",
"الطبقة 1: الفيزيائية","الطبقة 2: ربط البيانات","الطبقة 3: الشبكة","الطبقة 4: النقل","الطبقات 5-7","تطبيق عملي","مشروع: تتبع حزمة"),
U("بروتوكول TCP/IP",
"TCP: بروتوكول موثوق","UDP: بروتوكول سريع","المصافحة الثلاثية","المنافذ Ports","التطبيقات","مشروع: تحليل اتصال"),
U("عنونة IP",
"ما هو عنوان IP؟","IPv4: 32-bit","IPv6: 128-bit","العناوين العامة والخاصة","Subnet Mask","مشروع: خطط عناوين"),
U("إعداد شبكة منزلية",
"تخطيط الشبكة","توصيل الأجهزة","إعداد الراوتر","مشاركة الملفات","مشاركة الطابعة","مشروع: ابنِ شبكتك"),
U("أساسيات أمن الشبكات",
"جدار الحماية","WPA3","تغيير كلمة مرور الراوتر","تحديث firmware","شبكة الضيوف","مشروع: أمن شبكتك"),
U("مشروع: شبكة لمكتب صغير","تخطيط","توصيل","إعداد","أمن","اختبار","توثيق","عرض"),
),
S("الإنترنت والويب","فهم الإنترنت وبناء صفحات الويب",
U("كيف يعمل الإنترنت؟","بنية الإنترنت","مزود الخدمة ISP","خط المشترك الرقمي DSL","الألياف البصرية","مشروع: تتبع مسار"),
U("DNS","نظام أسماء النطاقات","خوادم DNS","سجلات DNS","تغيير DNS","مشروع: تحليل نطاق"),
U("HTTP و HTTPS","بروتوكول HTTP","HTTPS و SSL/TLS","رموز الحالة","الكوكيز","مشروع: فحص طلب"),
U("HTML","الوسوم الأساسية","العناوين والفقرات","الروابط والصور","القوائم والجداول","مشروع: صفحتك الأولى"),
U("CSS","الألوان والخطوط","الهوامش والحواف","Flexbox","Grid","مشروع: تنسيق صفحتك"),
U("استضافة المواقع","أنواع الاستضافة","حجز نطاق","رفع الملفات","cPanel","مشروع: انشر موقعك"),
U("أمان المتصفح","الشهادات الرقمية","التصفح الخاص","إدارة الكوكيز","كلمات المرور","مشروع: أمن متصفحك"),
U("البريد الإلكتروني","إعداد بريد","آداب المراسلة","تنظيم البريد","مرفقات","مشروع: حساب احترافي"),
U("مشروع: موقع تعريفي","تخطيط","HTML","CSS","استضافة","نشر","عرض"),
),
S("البرمجيات المكتبية والإنتاجية","إتقان حزمة البرامج المكتبية",
U("معالج النصوص","تنسيق المستندات","الجداول","الأنماط","مراجعة","مشروع: تقرير"),
U("الجداول الإلكترونية","الصيغ","الدوال","الرسوم البيانية","Pivot Tables","مشروع: تحليل"),
U("العروض التقديمية","تصميم الشرائح","الحركات","عرض البيانات","التقديم","مشروع: عرض"),
U("البريد والتنظيم","Outlook","التقويم","المهام","جهات الاتصال","مشروع: نظام تنظيم"),
U("أدوات التعاون","Teams","Slack","مشاركة الملفات","التعاون","مشروع: فريق"),
U("الاجتماعات الافتراضية","Zoom","آداب الاجتماع","مشاركة الشاشة","تسجيل","مشروع: اجتماع"),
U("تدوين الملاحظات","OneNote","Notion","تنظيم","مشاركة","مشروع: قاعدة معرفة"),
U("إدارة المهام","To-Do","Planner","أولويات","مواعيد","مشروع: إدارة وقت"),
U("مشروع: نظام إداري","تخطيط","بناء","اختبار","توثيق","عرض"),
),
S("مقدمة في البرمجة","كتابة أول برنامج وفهم المنطق البرمجي",
U("ما هي البرمجة؟","الخوارزميات","Pseudocode","Flowcharts","أول برنامج","مشروع: صف خوارزمية"),
U("المتغيرات والأنواع","المتغيرات","int, float","str","bool","مشروع: متغيرات"),
U("الجمل الشرطية","if","else","elif","تداخل","مشروع: قرارات"),
U("الحلقات","for","while","break","continue","مشروع: تكرار"),
U("الدوال","تعريف","معاملات","return","استدعاء","مشروع: دوال"),
U("القوائم والمصفوفات","إنشاء","فهرسة","تقطيع","دوال","مشروع: قوائم"),
U("معالجة الأخطاء","try/except","أنواع الأخطاء","finally","raise","مشروع: أخطاء"),
U("العمل مع الملفات","قراءة","كتابة","CSV","JSON","مشروع: ملفات"),
U("مشروع: برنامج إدارة","تخطيط","بناء","اختبار","توثيق","عرض"),
),
S("مشروع المستوى الأول","تطبيق جميع مهارات المستوى",
U("تخطيط المشروع","تحديد الهدف","نطاق العمل","الجدول الزمني","الموارد","خطة"),
U("تجهيز العتاد","اختيار المكونات","تجميع","اختبار","توثيق"),
U("تثبيت البرامج","نظام التشغيل","البرامج الأساسية","تحديثات","إعدادات"),
U("إعداد الشبكة","تخطيط","توصيل","تكوين","اختبار"),
U("بناء التطبيق","تصميم","برمجة","اختبار","تحسين"),
U("توثيق المشروع","دليل المستخدم","التوثيق التقني","رسومات","حفظ"),
U("اختبار النظام","خطة اختبار","تنفيذ","توثيق النتائج","إصلاح"),
U("العرض النهائي","تحضير العرض","تقديم","تغذية راجعة","تقييم"),
),
),

  L("المستوى الثاني: البرمجة وقواعد البيانات","إتقان Python, SQL, Flask, WordPress","apply",
  S("أساسيات Python","كتابة برامج منظمة وفعالة",
  U("المتغيرات والعمليات","المتغيرات وأنواع البيانات","العمليات الحسابية","العمليات المنطقية","التحويل بين الأنواع","F-strings","مدخلات المستخدم input()","التعليقات","مشروع: حاسبة"),
  U("الجمل الشرطية والحلقات","if, elif, else","تداخل الشروط","match/case","for مع range","while","break, continue","الحلقات المتداخلة","مشروع: لعبة تخمين"),
  U("القوائم والمجموعات","إنشاء القوائم","الفهرسة والتقطيع","append, remove, sort","List Comprehensions","Tuple","Set","Dict","مشروع: إدارة قائمة"),
  U("الدوال والمكتبات","def: تعريف","المعاملات","return","lambda","استيراد المكتبات","math, random","datetime","مشروع: مكتبة دوال"),
  U("العمل مع الملفات","open, read, write","قراءة CSV","كتابة CSV","JSON","معالجة الأخطاء","try/except","معالجة الملفات الكبيرة","مشروع: معالج بيانات"),
  U("البرمجة كائنية التوجه OOP","Class, Object","__init__, self","الخصائص والدوال","التغليف","الوراثة","تعدد الأشكال","Magic Methods","مشروع: نظام إدارة"),
  U("مكتبات Python المفيدة","os, sys","pathlib","requests","BeautifulSoup","smtplib","tkinter","pillow","مشروع: تطبيق عملي"),
  U("اختبار وتصحيح الكود","print debugging","pdb","logging","assert","unit test مع unittest","pytest","تغطية الاختبار","مشروع: اختبر كودك"),
  U("مشروع: تطبيق Python","تخطيط","تصميم","تطوير","اختبار","توثيق","نشر","عرض"),
  ),
  S("قواعد البيانات SQL","تصميم وإدارة قواعد البيانات",
  U("مقدمة قواعد البيانات","ما هي قاعدة البيانات؟","أنواع قواعد البيانات","SQL vs NoSQL","MySQL/PostgreSQL","مشروع: أول قاعدة"),
  U("إنشاء الجداول","CREATE TABLE","أنواع البيانات","PRIMARY KEY","FOREIGN KEY","Constraints","AUTO_INCREMENT","مشروع: صمم جدولاً"),
  U("إدخال واستعلام البيانات","INSERT INTO","SELECT","WHERE","ORDER BY","LIMIT","DISTINCT","مشروع: استعلامات"),
  U("تصفية وفرز متقدم","LIKE, IN, BETWEEN","AND, OR, NOT","NULL","GROUP BY","HAVING","وظائف التجميع","مشروع: تقارير"),
  U("الربط JOIN","INNER JOIN","LEFT JOIN","RIGHT JOIN","Self Join","Subqueries","UNION","مشروع: دمج جداول"),
  U("تعديل وحذف البيانات","UPDATE","DELETE","TRUNCATE","المعاملات Transactions","ROLLBACK","SAVEPOINT","مشروع: عمليات"),
  U("الفهارس والأداء","INDEX","EXPLAIN","تحسين الاستعلامات","أنواع الفهارس","Query Cache","مشروع: تحسين"),
  U("إدارة قواعد البيانات","النسخ الاحتياطي","استعادة","إنشاء مستخدمين","صلاحيات GRANT","استيراد/تصدير","مشروع: إدارة"),
  U("مشروع: قاعدة بيانات","تخطيط","تصميم","إنشاء","استعلامات","تحسين","توثيق","عرض"),
  ),
  S("تطوير الويب الخلفي","Flask و REST APIs",
  U("مقدمة Flask","تثبيت Flask","أول تطبيق","Routes","Debug Mode","مشروع: Hello World"),
  U("Routing والطلبات","GET, POST","Route Parameters","Query Strings","Redirect","مشروع: توجيه"),
  U("القوالب Jinja2","Template Inheritance","Variables","Loops","Conditions","Filters","مشروع: قوالب"),
  U("النماذج Forms","WTForms","CSRF","Validation","File Upload","مشروع: نموذج"),
  U("قواعد البيانات مع Flask","SQLAlchemy","Models","Migrations","CRUD","مشروع: مدونة"),
  U("المصادقة","Flask-Login","Registration","Login/Logout","Password Hashing","Session","مشروع: مصادقة"),
  U("REST API","JSON","Endpoints","Methods","Status Codes","Postman","مشروع: API"),
  U("نشر Flask","Gunicorn","Nginx","Environment Variables","Debug=False","مشروع: نشر"),
  U("مشروع: تطبيق ويب","تخطيط","Backend","قاعدة بيانات","API","Frontend","نشر","عرض"),
  ),
  S("تطوير الويب الأمامي","HTML, CSS, JavaScript",
  U("HTML5","الوسوم الأساسية","العناوين والفقرات","الروابط والصور","القوائم","الجداول","النماذج","مشروع: صفحة"),
  U("CSS3","المحددات","الألوان والخطوط","Box Model","Flexbox","Grid","Responsive","مشروع: تنسيق"),
  U("JavaScript","المتغيرات","الدوال","DOM","الأحداث","ES6","Fetch API","مشروع: تفاعل"),
  U("Bootstrap","Grid System","Components","Forms","Utilities","Icons","مشروع: Bootstrap"),
  U("jQuery و AJAX","Selectors","Events","Effects","AJAX","JSON","مشروع: ديناميكي"),
  U("تحسين الأداء","Minification","Lazy Loading","Caching","CDN","Page Speed","مشروع: تحسين"),
  U("أمان الويب","XSS","CSRF","SQL Injection","HTTPS","Headers","مشروع: أمان"),
  U("SEO","Meta Tags","Sitemap","Robots.txt","Schema.org","مشروع: SEO"),
  U("مشروع: موقع متكامل","تخطيط","تصميم","تطوير","أمان","SEO","نشر","عرض"),
  ),
  S("WordPress و CMS","بناء وإدارة مواقع بدون كود",
  U("تثبيت WordPress","متطلبات","تثبيت","لوحة التحكم","الإعدادات","مشروع: تثبيت"),
  U("إدارة المحتوى","المقالات","الصفحات","الوسوم","التصنيفات","القوائم","مشروع: محتوى"),
  U("القوالب Themes","تثبيت","تخصيص","Customizer","Child Themes","مشروع: قالب"),
  U("الإضافات Plugins","تثبيت","إعدادات","أهم الإضافات","التحديث","مشروع: إضافات"),
  U("WooCommerce","تثبيت","منتجات","سلة","دفع","شحن","مشروع: متجر"),
  U("SEO في WordPress","Yoast SEO","خرائط","روابط","Speed","مشروع: تحسين"),
  U("أمان WordPress","تحديثات","نسخ احتياطي","حماية","2FA","مشروع: أمان"),
  U("تخصيص متقدم","Custom Post Types","ACF","Hooks","Shortcodes","مشروع: تخصيص"),
  U("مشروع: موقع مؤسسة","تخطيط","بناء","محتوى","أمان","SEO","نشر"),
  ),
  S("Git والتحكم بالإصدارات","التعاون في تطوير البرمجيات",
  U("مقدمة Git","لماذا Git؟","تثبيت","git config","مشروع: أول repo"),
  U("الأساسيات","git init","git add","git commit","git status","git log","مشروع: تتبع"),
  U("الفروع Branches","git branch","git checkout","git merge","حل التعارضات","مشروع: تفرع"),
  U("GitHub","إنشاء repo","git push","git pull","git clone","README","مشروع: GitHub"),
  U("التعاون","Fork","Pull Request","Code Review","Issues","Projects","مشروع: تعاون"),
  U("Git المتقدم","git stash","git rebase","git cherry-pick","git bisect","مشروع: متقدم"),
  U("GitHub Actions","Workflows","CI/CD","Automation","Secrets","مشروع: Actions"),
  U("أفضل الممارسات","Commit Messages","Branching Strategy",".gitignore","Code Review","مشروع: ممارسات"),
  U("مشروع: فريق تطوير","تخطيط","Git Flow","تعاون","مراجعة","تسليم"),
  ),
  S("مشروع المستوى: تطبيق ويب","بناء تطبيق متكامل",
  U("تخطيط","متطلبات","تصميم","جدول","فريق"),
  U("قاعدة البيانات","تصميم","إنشاء","بذور","اختبار"),
  U("Backend","Flask","Routes","APIs","منطق"),
  U("Frontend","HTML","CSS","JS","متجاوب"),
  U("تكامل","دمج","اختبار","تحسين","إصلاح"),
  U("توثيق","API Docs","README","User Guide","تعليقات"),
  U("نشر","خادم","نطاق","SSL","مراقبة"),
  U("عرض","تحضير","تقديم","Demo","تقييم"),
  ),
  ),
  L("المستوى الثالث: الشبكات وأنظمة التشغيل","TCP/IP, إدارة الشبكات, Windows Server, Linux","apply",
  S("الشبكات المتقدمة","بروتوكولات, VLANs, Routing",
  U("TCP/IP بعمق","Three-way Handshake","Flow Control","Congestion Control","TCP vs UDP","Ports","Sockets","Wireshark","مشروع: تحليل حزم"),
  U("Subnetting و VLSM","Subnet Mask","CIDR","VLSM","حساب الشبكات","Subnet Calculator","تطبيقات","مشروع: تقسيم"),
  U("VLAN","802.1Q","Trunk","Access Port","VLAN Config","Inter-VLAN Routing","VTP","مشروع: VLANs"),
  U("STP و EtherChannel","Spanning Tree","Root Bridge","PortFast","EtherChannel","LACP","مشروع: STP"),
  U("Routing Protocols","Static Routing","RIP","OSPF","EIGRP","Admin Distance","مشروع: توجيه"),
  U("ACL","Standard ACL","Extended ACL","Wildcard Mask","Placement","تطبيقات","مشروع: ACL"),
  U("NAT و PAT","Static NAT","Dynamic NAT","PAT","Port Forwarding","تطبيقات","مشروع: NAT"),
  U("VPN","IPsec","SSL VPN","Site-to-Site","Remote Access","WireGuard","مشروع: VPN"),
  U("مشروع: شبكة مؤسسة","تخطيط","VLANs","Routing","ACL","NAT","VPN","عرض"),
  ),
  S("Windows Server","Active Directory, GPO, DNS",
  U("تثبيت Windows Server","Editions","Roles","Features","Server Core","مشروع: تثبيت"),
  U("Active Directory","Domain","OU","Users","Groups","Computers","مشروع: AD"),
  U("Group Policy","GPO Creation","Policy Settings","Preferences","Loopback","مشروع: GPO"),
  U("DNS في Windows","Zones","Records","Forwarders","Conditional Forwarding","مشروع: DNS"),
  U("DHCP","Scope","Reservation","Options","Failover","مشروع: DHCP"),
  U("File Server","Shares","Permissions","DFS","Quota","مشروع: ملفات"),
  U("Print Server","تثبيت","مشاركة","Drivers","Deployment","مشروع: طباعة"),
  U("النسخ الاحتياطي","Windows Server Backup","System State","Bare Metal","Schedule","مشروع: نسخ"),
  U("مشروع: Domain كامل","AD","DNS","DHCP","GPO","Shares","Backup","عرض"),
  ),
  S("Linux بعمق","إدارة خوادم Linux",
  U("توزيعات Linux","Ubuntu Server","CentOS/Rocky","Debian","اختيار التوزيعة","مشروع: تثبيت"),
  U("نظام الملفات","FHS","الأدلة الرئيسية","Mount","fstab","LVM","مشروع: تنظيم"),
  U("إدارة المستخدمين","useradd, usermod","passwd","groups","sudo","su","مشروع: مستخدمين"),
  U("الصلاحيات","chmod","chown","umask","ACL","SUID/SGID","مشروع: صلاحيات"),
  U("العمليات والخدمات","ps, top, htop","systemd","journalctl","kill","nice","مشروع: عمليات"),
  U("Bash Scripting","shebang","متغيرات","شروط","حلقات","دوال","مشروع: سكريبت"),
  U("Cron والجدولة","crontab","Anacron","at","Logging","مشروع: جدولة"),
  U("إدارة الحزم","apt, dpkg","yum, dnf","snap","تحديثات","مشروع: حزم"),
  U("مشروع: إدارة خادم","تثبيت","تكوين","أتمتة","مراقبة","توثيق","عرض"),
  ),
  S("خدمات الشبكة","DNS, DHCP, Web, Email",
  U("Bind DNS","تثبيت","Zones","Records","Master/Slave","DNSSEC","مشروع: DNS"),
  U("ISC DHCP","تثبيت","Scope","Static","Failover","مشروع: DHCP"),
  U("Apache/Nginx","Virtual Hosts","SSL","Reverse Proxy","Caching","مشروع: ويب"),
  U("Postfix/Dovecot","SMTP","IMAP","POP3","SSL","Anti-Spam","مشروع: بريد"),
  U("FTP/SFTP","vsftpd","SFTP","أمان","Chroot","مشروع: FTP"),
  U("Samba","File Sharing","Print Sharing","AD Integration","مشروع: Samba"),
  U("NFS","Exports","Mount","Permissions","Performance","مشروع: NFS"),
  U("مراقبة الخدمات","Monit","Nagios","Health Checks","Alerting","مشروع: مراقبة"),
  U("مشروع: خدمات شبكة","DNS","DHCP","Web","Email","FTP","عرض"),
  ),
  S("أمن الشبكات","جدران الحماية, IDS/IPS, أمن لاسلكي",
  U("جدران الحماية","iptables","ufw","firewalld","Stateful","NGFW","قواعد","مشروع: جدار"),
  U("IDS/IPS","Snort","Suricata","Signatures","Anomaly Detection","Deployment","مشروع: IDS"),
  U("أمن لاسلكي","WPA3","802.1X","RADIUS","Evil Twin","Rogue AP","مشروع: لاسلكي"),
  U("VPN وأمن الاتصالات","OpenVPN","WireGuard","StrongSwan","MFA","مشروع: VPN"),
  U("اختبار الاختراق","Nmap","Metasploit","Burp Suite","OWASP ZAP","Reporting","مشروع: Pentest"),
  U("تحليل السجلات","Syslog","SIEM","Log Analysis","Alerting","مشروع: سجلات"),
  U("الاستجابة للحوادث","خطة IR","Containment","Eradication","Recovery","Lessons","مشروع: IR"),
  U("Hardening","CIS Benchmarks","OS Hardening","Network Hardening","Audit","مشروع: Hardening"),
  U("مشروع: خطة أمنية","تقييم","تصميم","تنفيذ","اختبار","توثيق","عرض"),
  ),
  S("المحاكاة الافتراضية","Virtualization, Docker, الحاويات",
  U("VirtualBox","تثبيت","إنشاء VM","Snapshots","Networking","مشروع: VM"),
  U("VMware","ESXi","vSphere","vCenter","Features","مشروع: VMware"),
  U("Hyper-V","تثبيت","Virtual Switch","Checkpoints","مشروع: Hyper-V"),
  U("Docker","تثبيت","docker run","Dockerfile","docker-compose","مشروع: Docker"),
  U("Docker Hub","Images","Tags","Push/Pull","Registry","مشروع: Hub"),
  U("Docker Compose","Services","Networks","Volumes","Environment","مشروع: Compose"),
  U("مقارنة VMs و Containers","Isolation","Performance","Use Cases","مشروع: مقارنة"),
  U("حاويات في الإنتاج","Orchestration","Monitoring","Scaling","Backup","مشروع: إنتاج"),
  U("مشروع: بيئة افتراضية","تخطيط","VMs","حاويات","شبكات","اختبار","عرض"),
  ),
  S("مشروع المستوى: بنية تحتية","بناء وإدارة بنية لمؤسسة",
  U("تخطيط البنية","متطلبات","تصميم","سعة","ميزانية"),
  U("الشبكة","VLANs","Routing","ACL","NAT","اختبار"),
  U("الخوادم","Windows","Linux","تثبيت","تكوين"),
  U("الخدمات","DNS","DHCP","AD","Web","Email"),
  U("الأمن","جدار","IDS","VPN","Hardening","تدقيق"),
  U("المراقبة","Monitoring","Logging","Alerting","Dashboards"),
  U("التوثيق","مخططات","إجراءات","Runbooks","تسليم"),
  U("عرض","تحضير","تقديم","Demo","تقييم"),
  ),
  ),
  L("المستوى الرابع: إدارة الأنظمة والأمن","Cloud, أمن متقدم, DevOps","analyze",
  S("الحوسبة السحابية","AWS, Azure, النشر السحابي",
  U("مفاهيم السحابة","IaaS, PaaS, SaaS","Public, Private, Hybrid","Regions, AZ","مشروع: مفاهيم"),
  U("AWS EC2","Instances","AMIs","Security Groups","Key Pairs","مشروع: EC2"),
  U("AWS S3","Buckets","Objects","Permissions","Versioning","مشروع: S3"),
  U("AWS VPC","Subnets","Route Tables","NAT Gateway","VPN","مشروع: VPC"),
  U("AWS IAM","Users,Groups,Roles","Policies","MFA","مشروع: IAM"),
  U("Azure","VMs","Storage","VNet","Active Directory","مشروع: Azure"),
  U("إدارة التكاليف","Budget","Cost Explorer","Tags","Optimization","مشروع: تكاليف"),
  U("البنية ككود","CloudFormation","Terraform","ARM Templates","مشروع: IaC"),
  U("مشروع: نقل للسحابة","تخطيط","Migration","نشر","اختبار","مراقبة","عرض"),
  ),
  S("أمن المعلومات المتقدم","IAM, Encryption, Pentesting",
  U("إطار NIST","Identify","Protect","Detect","Respond","Recover","مشروع: NIST"),
  U("IAM","SSO","MFA","Federation","PAM","مشروع: IAM"),
  U("التشفير","Symmetric","Asymmetric","PKI","HSM","مشروع: تشفير"),
  U("أمن التطبيقات","OWASP Top 10","SAST","DAST","Secure Coding","مشروع: OWASP"),
  U("اختبار الاختراق","Recon","Exploitation","Post-Exploit","Report","مشروع: Pentest"),
  U("تحليل الثغرات","Nessus","OpenVAS","CVSS","Remediation","مشروع: ثغرات"),
  U("SOC و SIEM","SIEM","SOAR","Use Cases","Threat Hunting","مشروع: SOC"),
  U("Incident Response","NIST IR","SANS PICERL","Playbooks","Tabletop","مشروع: IR"),
  U("مشروع: تقييم أمني","Scoping","Testing","Analysis","Report","عرض"),
  ),
  S("إدارة قواعد البيانات","تحسين، نسخ احتياطي، أمان",
  U("تحسين الأداء","Slow Queries","Execution Plan","Indexing","Partitioning","مشروع: تحسين"),
  U("النسخ الاحتياطي","Full, Diff, Log","Strategy","Retention","Verification","مشروع: نسخ"),
  U("High Availability","Clustering","Always On","Replication","Failover","مشروع: HA"),
  U("أمان قواعد البيانات","Encryption","Auditing","Least Privilege","Injection","مشروع: أمان"),
  U("PostgreSQL","Install","Configuration","pgAdmin","Extensions","مشروع: PG"),
  U("MySQL/MariaDB","Install","Configuration","phpMyAdmin","Engines","مشروع: MySQL"),
  U("NoSQL","MongoDB","Redis","Use Cases","CRUD","مشروع: NoSQL"),
  U("ترحيل البيانات","Planning","ETL","Validation","Cutover","مشروع: ترحيل"),
  U("مشروع: إدارة قاعدة","تثبيت","تحسين","HA","أمان","مراقبة","عرض"),
  ),
  S("إدارة الخدمات السحابية","Azure AD, Office 365, Exchange",
  U("Microsoft 365","Plans","Admin Center","Users","Groups","مشروع: M365"),
  U("Exchange Online","Mailboxes","DLP","Anti-Spam","Rules","مشروع: Exchange"),
  U("SharePoint Online","Sites","Document Libraries","Permissions","مشروع: SharePoint"),
  U("Teams","Teams","Channels","Apps","Meetings","مشروع: Teams"),
  U("OneDrive","Sync","Sharing","Version History","Retention","مشروع: OneDrive"),
  U("Intune","MDM","Compliance","Conditional Access","مشروع: Intune"),
  U("Azure AD","Connect","SSO","Conditional Access","PIM","مشروع: AzureAD"),
  U("الترحيل لـ M365","Planning","Migration","Hybrid","Cutover","مشروع: ترحيل"),
  U("مشروع: M365 كامل","تخطيط","نشر","تكوين","تدريب","دعم","عرض"),
  ),
  S("DevOps و CI/CD","Jenkins, GitHub Actions, Docker",
  U("ثقافة DevOps","CALMS","Collaboration","Automation","Measurement","Sharing","مشروع: DevOps"),
  U("CI/CD Concepts","Continuous Integration","Continuous Delivery","Continuous Deployment","مشروع: CI/CD"),
  U("Jenkins","Install","Pipeline","Plugins","Agents","مشروع: Jenkins"),
  U("GitHub Actions","Workflows","Actions","Secrets","Matrix","مشروع: Actions"),
  U("GitLab CI",".gitlab-ci.yml","Runners","Stages","Environments","مشروع: GitLab"),
  U("Docker في CI/CD","Build Images","Registry","Deploy","Scan","مشروع: Docker"),
  U("Kubernetes","Pods","Services","Deployments","Ingress","مشروع: K8s"),
  U("Monitoring","Prometheus","Grafana","ELK Stack","Alerting","مشروع: مراقبة"),
  U("مشروع: Pipeline كامل","Code","Build","Test","Deploy","Monitor","عرض"),
  ),
  S("إدارة المشاريع التقنية","Agile, Scrum, Jira",
  U("منهجيات الإدارة","Waterfall","Agile","Scrum","Kanban","Lean","مشروع: منهجيات"),
  U("Scrum بعمق","Roles","Events","Artifacts","Sprint","مشروع: Scrum"),
  U("Jira","Projects","Boards","Backlog","Sprints","Reports","مشروع: Jira"),
  U("كتابة المتطلبات","User Stories","Acceptance Criteria","Epics","Gherkin","مشروع: متطلبات"),
  U("تقدير الجهد","Story Points","Planning Poker","Velocity","Burndown","مشروع: تقدير"),
  U("إدارة المخاطر","Risk Register","Probability","Impact","Mitigation","مشروع: مخاطر"),
  U("إدارة الفريق","Communication","Motivation","Conflict","Meetings","مشروع: فريق"),
  U("التسليم","Sprint Review","Retrospective","Release","Handover","مشروع: تسليم"),
  U("مشروع: إدارة مشروع","تخطيط","Sprints","تتبع","تسليم","Retro","عرض"),
  ),
  S("مشروع المستوى: حل تقني","بناء وتنفيذ حل متكامل",
  U("تخطيط","متطلبات","معمارية","ميزانية","جدول"),
  U("السحابة","نشر","تكوين","أتمتة","اختبار"),
  U("الأمن","تقييم","تنفيذ","تدقيق","توثيق"),
  U("CI/CD","Pipeline","Build","Test","Deploy"),
  U("إدارة","Agile","Sprints","تتبع","تقارير"),
  U("توثيق","معمارية","إجراءات","Runbooks","تسليم"),
  U("اختبار","Performance","Security","UAT","Sign-off"),
  U("عرض","تحضير","تقديم","Demo","تقييم"),
  ),
  ),
  L("المستوى الخامس: إدارة المشاريع والمشاريع المتكاملة","ITIL, قيادة, أمن مؤسسات, ريادة, BI","create",
  S("ITIL 4","إدارة خدمات تقنية المعلومات",
  U("مقدمة ITIL 4","SVS","الأبعاد","المبادئ","مشروع: ITIL"),
  U("الممارسات العامة","Service Desk","Incident","Problem","Change","مشروع: ممارسات"),
  U("إدارة الحوادث","تصنيف","أولوية","تصعيد","حل","تقارير","مشروع: حوادث"),
  U("إدارة المشكلات","Root Cause","Known Error","Workaround","KEDB","مشروع: مشكلات"),
  U("إدارة التغيير","Normal, Standard, Emergency","CAB","تقييم","مشروع: تغيير"),
  U("Service Desk","SPOC","Channels","Metrics","CSI","مشروع: مكتب خدمة"),
  U("SLA و SLM","Service Level","OLA","Contracts","Reports","مشروع: SLA"),
  U("التحسين المستمر","CSI Register","PDCA","Measurements","Feedback","مشروع: تحسين"),
  U("مشروع: تطبيق ITIL","Assessment","Roadmap","Implementation","Review","عرض"),
  ),
  S("قيادة الفرق التقنية","Leadership, Communication, Strategy",
  U("القيادة مقابل الإدارة","Vision","Influence","Empowerment","Accountability","مشروع: قيادة"),
  U("بناء الفريق","Hiring","Onboarding","Team Building","Culture","مشروع: فريق"),
  U("التفويض","Delegation Levels","Trust","Follow-up","Feedback","مشروع: تفويض"),
  U("التحفيز","Intrinsic, Extrinsic","Recognition","Growth","Autonomy","مشروع: تحفيز"),
  U("إدارة النزاعات","Types","Resolution","Mediation","Difficult Conversations","مشروع: نزاع"),
  U("الاجتماعات","Agenda","Facilitation","Minutes","Action Items","مشروع: اجتماع"),
  U("التواصل التقني","Audience","Simplify","Visuals","Storytelling","مشروع: تواصل"),
  U("التطوير المهني","Career Paths","Mentoring","Training","Certifications","مشروع: تطوير"),
  U("مشروع: خطة قيادة","Self-Assessment","Goals","Actions","Review","عرض"),
  ),
  S("هندسة النظم","Microservices, APIs, Architecture",
  U("أنماط المعمارية","Monolith","Microservices","SOA","Event-Driven","مشروع: أنماط"),
  U("API Design","REST","GraphQL","gRPC","Versioning","مشروع: API"),
  U("Message Queues","RabbitMQ","Kafka","Pub/Sub","Dead Letter","مشروع: MQ"),
  U("Caching","Redis","Memcached","CDN","Cache Strategies","مشروع: Cache"),
  U("قواعد البيانات الموزعة","Sharding","Replication","CAP Theorem","Consistency","مشروع: Distributed"),
  U("Circuit Breakers","Hystrix","Resilience4j","Bulkhead","Timeout","مشروع: Resilience"),
  U("Documentation","ADRs","C4 Model","Swagger","Arc42","مشروع: Docs"),
  U("Trade-offs","Scalability","Availability","Consistency","Cost","مشروع: Tradeoffs"),
  U("مشروع: تصميم نظام","Requirements","Architecture","Trade-offs","Documentation","عرض"),
  ),
  S("أمن المؤسسات","Compliance, BCP, DR, SOC",
  U("Compliance","ISO 27001","SOC 2","PCI-DSS","GDPR","مشروع: Compliance"),
  U("BCP و DR","BIA","RTO, RPO","Strategy","Testing","مشروع: BCP"),
  U("Third-Party Risk","Assessment","Due Diligence","Monitoring","مشروع: TPRM"),
  U("Security Awareness","Phishing Simulations","Training","Culture","Metrics","مشروع: Awareness"),
  U("SOC Operations","Tier 1-3","Playbooks","Metrics","Shift","مشروع: SOC"),
  U("Threat Intelligence","Sources","IOCs","TTPs","Sharing","مشروع: TI"),
  U("Digital Forensics","Chain of Custody","Imaging","Analysis","Report","مشروع: Forensics"),
  U("Purple Teaming","Red vs Blue","Adversary Emulation","Detection","مشروع: Purple"),
  U("مشروع: برنامج أمني","Assessment","Strategy","Implementation","Review","عرض"),
  ),
  S("ذكاء الأعمال BI","Power BI, تحليل البيانات, تقارير",
  U("مقدمة BI","ETL","Data Warehouse","Data Mart","OLAP","مشروع: BI"),
  U("Power BI Desktop","Get Data","Transform","Model","Visualize","مشروع: PBI"),
  U("DAX","CALCULATE","FILTER","Time Intelligence","Relationships","مشروع: DAX"),
  U("Power BI Service","Publish","Dashboards","Apps","Gateway","مشروع: Service"),
  U("SQL للتحليل","Window Functions","CTEs","Pivot","Rollup","مشروع: SQL"),
  U("Excel Power Tools","Power Query","Power Pivot","Power View","مشروع: Excel"),
  U("تصور البيانات","Chart Selection","Colors","Layout","Storytelling","مشروع: تصور"),
  U("مؤشرات الأداء KPIs","Leading, Lagging","Balanced Scorecard","Targets","مشروع: KPIs"),
  U("مشروع: Dashboard","Requirements","Data","Design","Publish","عرض"),
  ),
  S("ريادة الأعمال التقنية","Startups, Innovation, Business Models",
  U("توليد الأفكار","Problem Discovery","Ideation","Validation","MVP","مشروع: فكرة"),
  U("Business Model Canvas","Segments","Value Prop","Channels","Revenue","مشروع: BMC"),
  U("Lean Startup","Build-Measure-Learn","Pivot","Validated Learning","مشروع: Lean"),
  U("التمويل","Bootstrapping","Angels","VC","Grants","Crowdfunding","مشروع: تمويل"),
  U("Pitch Deck","Problem","Solution","Market","Traction","Team","مشروع: Pitch"),
  U("Legal","Registration","IP","Contracts","Tax","مشروع: Legal"),
  U("Go-to-Market","Channels","Pricing","Marketing","Sales","مشروع: GTM"),
  U("Growth","Metrics","AARRR","Scaling","Exit","مشروع: Growth"),
  U("مشروع: خطة عمل","Idea","BMC","Validation","Financials","Pitch","عرض"),
  ),
  S("المشروع الختامي","نظام تقني متكامل",
  U("اختيار المشروع","Problem","Stakeholders","Scope","Feasibility"),
  U("تخطيط","WBS","Schedule","Budget","Risks"),
  U("تصميم","Architecture","UI/UX","Database","APIs"),
  U("تطوير","Sprint 1","Sprint 2","Sprint 3","Integration"),
  U("اختبار","Functional","Performance","Security","UAT"),
  U("توثيق","Technical","User Manual","API Docs","Runbooks"),
  U("نشر","Go-Live","Training","Support","Monitoring"),
  U("عرض","Preparation","Presentation","Demo","Evaluation"),
  ),
  ),
]

MISTAKES = [
("Data Leakage","Scaler قبل التقسيم = اختبار يتسرب = دقة وهمية.","اقسم أولاً. scaler.fit(X_train). scaler.transform(X_test). Pipeline.","Pipeline يمنع Data Leakage تلقائياً.","critical"),
("Overfitting","دقة تدريب 99%، اختبار 65%. النموذج حفظ ولم يتعلم.","تبسيط، Regularization، CV، EarlyStopping.","افحص الفجوة بين train و test. Validation Curve.","critical"),
("عدم توحيد المقياس","متغير 1-1000 يسيطر على المسافات.","StandardScaler قبل K-Means,KNN,SVM,NN. Trees لا تحتاج.","كل نموذج يعتمد على المسافة يحتاج scaling.","major"),
("حلقات for مع Pandas","for على 100K: 5 ثوان. متجهة: 0.002 ثانية.","df['new'] = df['a'] + df['b']. apply() فقط.","إذا كتبت for مع Pandas، توقف.","minor"),
("عدم استخدام Pipeline","خطوات يدوية = نسيان = Data Leakage.","Pipeline([('scaler',Scaler()),('model',Model())]).","Pipeline صديقك. استخدمه دائماً.","major"),
("إهمال النسخ الاحتياطي","قرص صلب يفشل = فقدان كل البيانات.","قاعدة 3-2-1: ثلاث نسخ، وسيطين، نسخة خارج الموقع.","تكلفة النسخ الاحتياطي لا تقارن بتكلفة فقدان البيانات.","critical"),
("كلمات مرور ضعيفة","password123 = اختراق في ثوان.","كلمة مرور: 12+ حرف، أحرف كبيرة وصغيرة، أرقام، رموز.","استخدم مدير كلمات مرور. لا تكرر الكلمة بين الحسابات.","major"),
("عدم اختبار النسخ الاحتياطي","نسخ احتياطي موجود لكن استعادته لا تعمل.","اختبر استعادة البيانات شهرياً. وثق عملية الاستعادة.","النسخة غير المختبرة لا قيمة لها.","major"),
]

def mb(p,c):return[f"الآن أتقنتَ {p}، نرتقي إلى {c}.",f"في الدرس السابق فككنا {p}. اليوم نبني عليه بـ {c}.",f"بعد {p}، {c} يسد الفجوة التالية.",f"{p} كان الأساس. {c} هو الطابق التالي.",][h(p+c)%4]

def gl(uc,lt,sn):
 ls=[];pv="المفاهيم الأساسية"
 for li,t in enumerate(lt,1):
  nm=2+(h(f"{uc}_{li}")%2);lm=[{"mistake":f"{m[0]}\n{m[1]}","correction":m[2],"treatment":m[3],"severity":m[4]} for m in [MISTAKES[(h(f"{uc}_{li}_{mi}"))%len(MISTAKES)] for mi in range(nm)]]
  ls.append({"lesson_index":li,"name":t,"goal":f"فهم وتطبيق {t}","bridge_sentence":mb(pv,t),"prerequisite_lessons":[] if li==1 else [f"{uc}.{li-1}"],"enables_lessons":[] if li==len(lt) else [f"{uc}.{li+1}"],"final_check_question":f"اشرح {t} بكلماتك. خطوات تطبيقه؟ أشهر خطأ؟","session_complete_criterion":f"يشرح {t} ويطبقه عملياً","yemeni_examples":[f"تطبيق عملي: {t}."],"expected_duration_minutes":30,"estimated_gem_cost":90,"solution_outline":f"خطوات {t}:\n1. فهم الأساس\n2. تطبيق الكود\n3. التجربة\n4. تحليل النتائج\n5. توثيق","motivation_hook":f"{t} — مهارة أساسية في تقنية المعلومات.","learning_objectives":[{"statement":f"يفهم {t}","bloom_level":"understand"},{"statement":f"يطبق {t}","bloom_level":"apply"}],"glossary":[],"concepts":[{"name":t,"explanation":f"شرح وتطبيق عملي لـ {t} في سياق {sn}.","mastery_criterion":f"يشرح {t} ويطبقه","weight":1}],"common_mistakes":lm});pv=t
 return ls

def glab(uc,un,nl):
 return[{"lab_index":li,"title":f"معمل {un}: {'التشخيص' if li==1 else 'التطبيق'}","scenario":f"مشكلة في {un}. حللها.","completion_criterion":f"تحليل وحل","pedagogical_sequence":"diagnostic -> decision -> application -> analysis -> connection","prerequisite_lessons":[f"{uc}.{nl//2}"],"allowed_tools":["text","code"],"questions":[{"kind":"diagnostic","prompt":f"خطوات تشخيص مشكلة في {un}؟","rubric":"ذكر 4 خطوات منطقية مع شرح","solution_outline":"جمع وتحليل وتحديد واقتراح","points":1},{"kind":"decision","prompt":f"خياران لحل في {un}. معاييرك؟","rubric":"ذكر معيارين مع تبرير","solution_outline":"الدقة والسرعة والتعقيد","points":1},{"kind":"application","prompt":f"اكتب كوداً يطبق {un}.","rubric":"كود صحيح يعمل","solution_outline":"استيراد وتطبيق","points":2},{"kind":"analysis","prompt":f"كود لـ {un} فيه 3 أخطاء.","rubric":"3 أخطاء مع تصحيح","solution_outline":"تحليل وتصحيح","points":1},{"kind":"connection","prompt":f"اربط {un} بمهارات سابقة.","rubric":"رابطان مع فكرة","solution_outline":"الربط وخطة","points":1}]} for li in range(1,3)]

def ge(c,s,n=10):
 q=[("الخطوة الأولى في مشروع:",["فهم المشكلة","تطبيق حل","جمع بيانات","كتابة كود"],0,1,"بدون هدف، أي حل لا قيمة له."),("نظام التشغيل:",["يدير موارد الحاسوب","متصفح","محرر نصوص","قاعدة بيانات"],0,1,"يدير العتاد والبرامج."),("نظام DNS:",["يترجم الأسماء لعناوين","يشفر","يضغط","يخزن"],0,1,"يحول google.com لـ IP."),("جدار الحماية:",["يراقب الحركة","يسرع","يخزن","يترجم"],0,1,"يتحكم في حركة البيانات."),("ذاكرة RAM:",["متطايرة","دائمة","بطيئة","للقراءة فقط"],0,1,"تمسح عند إغلاق الجهاز."),("IP Address:",["عنوان فريد","سرعة","بروتوكول","كيبل"],0,1,"عنوان فريد لكل جهاز."),("SSD vs HDD:",["SSD أسرع","HDD أسرع","لا فرق","SSD أكبر"],0,1,"SSD بدون أجزاء متحركة."),("نظام Linux:",["مفتوح المصدر","مغلق","فقط للخوادم","مدفوع"],0,1,"مجاني ومفتوح المصدر.")]
 vv=[]
 for v in range(3):vv.append([{"question_index":qi+1,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {ch}" for ci,ch in enumerate(c)],"correct_index":ci,"explanation":e,"difficulty":d,"points":1,"time_limit_seconds":60+d*30} for qi,(p,c,ci,d,e) in enumerate([q[(h(f"{s}_{v}_{qi}"))%len(q)] for qi in range(n)])])
 return{"code":s,"scope":c,"variants":vv}

def gp():
 q=[(1,"وظيفة نظام التشغيل:",["إدارة الموارد","تصفح","تحرير","ألعاب"],0,1),(1,"الذاكرة المتطايرة:",["RAM","ROM","HDD","SSD"],0,1),(2,"HTML:",["هيكل الصفحة","لغة برمجة","قاعدة بيانات","نظام تشغيل"],0,1),(2,"عنوان IP:",["عنوان جهاز","سرعة","بروتوكول","كيبل"],0,1),(3,"بروتوكول TCP:",["موثوق","سريع فقط","غير موثوق","لاسلكي"],0,2),(3,"Subnet Mask:",["يقسم الشبكة","يسرع","يشفر","يخزن"],0,2),(4,"شبكة VPN:",["نفق آمن","فيروس","متصفح","نظام"],0,2),(4,"Active Directory:",["دليل مستخدمين","بروتوكول","لغة","جهاز"],0,2),(5,"ITIL:",["إدارة خدمات","برمجة","شبكات","تصميم"],0,3),(5,"DevOps:",["دمج تطوير وتشغيل","لغة","جهاز","بروتوكول"],0,3)]
 return[{"target_level_index":l,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {c}" for ci,c in enumerate(c)],"correct_index":ci,"difficulty":d,"explanation":f"مستوى {l}"} for l,p,c,ci,d in q]

def main():
 print(f"\n{'='*60}\n  uni-it - تقنية المعلومات\n{'='*60}\n")
 mt={"slug":"uni-it","name":"تقنية المعلومات","icon":"💻","desc":"منهج متكامل: من أساسيات الحاسوب إلى إدارة المشاريع التقنية.","scope":"professional_track","language":"ar","region":"YE","target_persona":"طالب يريد احتراف تقنية المعلومات.","teacher_tone":"عملية ومباشرة.","viz":["flowchart","network_diagram","architecture_diagram","data_table"],"tools":["text","code","image"],"glossary":[{"term":"IP Address","definition":"عنوان رقمي فريد لكل جهاز"}]}
 rl=[];au=[];asc=[]
 for li,(ln,lg,lb,ss) in enumerate(CURRICULUM):
  lv=li+1;rs=[]
  for si,(sn,sg,us) in enumerate(ss):
   sv=si+1;sc=f"{lv}.{sv}";asc.append(sc);ru=[]
   for ui,(un,lt) in enumerate(us):
    lt=[t for t in lt if t and len(t)>=3];uv=ui+1;uc=f"{sc}.{uv}";au.append(uc)
    ls=gl(uc,lt,sn);la=glab(uc,un,len(ls))
    pr=[f"{sc}.{ui}"] if ui>0 else[];en=[f"{sc}.{ui+2}"] if ui<len(us)-1 else[]
    g=f"إتقان {un}";g=g if len(g)>=10 else f"إتقان {un} بشكل متقن"
    ru.append({"unit_index":uv,"name":un,"goal":g,"prerequisite_units":pr,"enables_units":en,"key_concepts":[lt[0][:20]],"motivation_hook":f"وحدة {un} — خطوتك نحو الاحتراف.","learning_objectives":[{"statement":f"يتقن {un}","bloom_level":"apply"}],"lessons":ls,"labs":la,"exam":{"pass_threshold_percent":60,"points":10,"time_limit_minutes":30}})
    print(f"  {uc}: {un[:50]} ({len(lt)} دروس)")
   rs.append({"stage_index":sv,"name":sn,"goal":sg,"bloom_focus":lb,"units":ru,"exam":{"pass_threshold_percent":60,"points":20,"time_limit_minutes":45}})
  rl.append({"level_index":lv,"name":ln,"goal":lg,"bloom_focus":lb,"stages":rs,"exam":{"pass_threshold_percent":60,"points":50,"time_limit_minutes":90}})
 print("\n  بنوك الامتحانات...")
 ub={c:ge(c,"unit",10) for c in au}
 sb={c:ge(c,"stage",15) for c in asc}
 lb={str(i):ge(str(i),"level",20) for i in range(1,len(rl)+1)}
 fn={"schema_version":"v4.1","specialty":{**mt,"yemeni_examples":["تطبيق عملي"]},"levels":rl,"exam_banks":{"unit_banks":ub,"stage_banks":sb,"level_banks":lb},"placement_test_questions":gp(),"publish_notes":"uni-it — تسلسل منطقي"}
 fp=OUT/"final.json"
 with open(fp,'w',encoding='utf-8') as f:json.dump(fn,f,ensure_ascii=False,indent=2)
 sz=fp.stat().st_size/(1024*1024);tl=sum(1 for l in rl for s in l['stages'] for u in s['units'] for _ in u['lessons'])
 print(f"\n  ✅ {sz:.1f} MB | {len(rl)} مستويات | {tl} درس\n")
if __name__=="__main__":main()
