#!/usr/bin/env python3
"""uni-data-science — تسلسل منطقي حقيقي — 5 مستويات كاملة"""
import json; from pathlib import Path; import random
random.seed(42)
def h(s): return sum(ord(c)*(i+1) for i,c in enumerate(str(s)))
OUT = Path("out/uni-data-science"); OUT.mkdir(parents=True, exist_ok=True)
def U(n,*l): return (n,list(l))
def S(n,g,*u): return (n,g,list(u))
def L(n,g,b,*s): return (n,g,b,list(s))

C = [
L("المستوى الأول: Python وأساسيات البيانات","إتقان Python, NumPy, Pandas, Matplotlib","apply",
S("أساسيات Python لعلم البيانات","كتابة كود Python بطلاقة",
U("تشغيل Python وبيئة العمل","تثبيت Python و Jupyter","أول خلية: print وحسابات","التعليقات وتوثيق الكود","المتغيرات وأنواع البيانات","type(), len(), range()","استيراد المكتبات","pd.read_csv(): أول DataFrame","df.head(), df.info(), df.describe()","مشروع: استكشف بيانات"),
U("المتغيرات والعمليات","المتغيرات: تسمية وتخزين","int, float, str, bool","التحويل بين الأنواع","العمليات الحسابية","عوامل المقارنة","العوامل المنطقية","F-strings","مشروع: آلة حاسبة تحليل"),
U("القوائم List","إنشاء القوائم","الفهرسة والتقطيع","append, extend, remove, pop","sort, sorted","len, min, max, sum","List Comprehensions","القوائم المتداخلة","مشروع: تحليل قائمة أسعار"),
U("القواميس Dict","إنشاء القواميس","الوصول: d['key'] و get()","إضافة وتعديل وحذف","keys, values, items","Dict Comprehensions","Tuple و Set","متى Dict vs List؟","مشروع: محلل بيانات بسيط"),
U("الدوال Functions","def: تعريف الدالة","المعاملات Parameters","return: إرجاع القيم","وسائط افتراضية","lambda: دوال سريعة","docstring","Scope","مشروع: مكتبة دوال تحليل"),
U("الشروط ومعالجة الأخطاء","if elif else","الشروط المتداخلة","if مع in","try/except","التحقق من المدخلات","assert","تطبيق: تنظيف بشرط","مشروع: مدقق جودة"),
U("الحلقات والتكرار","for مع range()","for مع enumerate()","while: تكرار بشرط","break و continue","الحلقات المتداخلة","التكرار على DataFrame","List Comprehension بدل الحلقات","مشروع: تقرير إحصائي"),
U("الملفات والبيانات","قراءة ملفات نصية","كتابة الملفات","معالجة CSV يدوياً","JSON","Excel","os و pathlib","ترميز utf-8","مشروع: جامع بيانات"),
U("مشروع: نظام تحليل","تخطيط","جمع CSV","تنظيف","إحصاء","تقرير","تصدير","توثيق","عرض"),
),
S("NumPy: الحوسبة العددية","Arrays، عمليات متجهة، إحصاء",
U("مقدمة NumPy","مقارنة List vs NumPy","إنشاء: np.array()","zeros, ones, arange","linspace, eye","shape, dtype","لماذا NumPy أسرع؟","مشروع: قياس الأداء"),
U("الفهرسة والتقطيع","[start:stop:step]","2D: [row, col]","Boolean Masking","Fancy Indexing","تعديل عبر التقطيع","مشروع: استخراج بيانات"),
U("العمليات المتجهة","عنصر بعنصر: + - * /","np.sqrt(), np.log()","Broadcasting","np.where()","np.select()","Vectorization مع دوال","مشروع: تحويل حلقات"),
U("الدوال الإحصائية","mean, median, std","sum, min, max","axis=0, axis=1","percentile, quantile","corrcoef","histogram","مشروع: تقرير إحصائي"),
U("إعادة التشكيل","reshape()","-1: حساب تلقائي","flatten, ravel","transpose, .T","newaxis","stack, split","مشروع: تشكيل بيانات"),
U("Boolean Masking","arr[arr > threshold]","& و | للشروط","np.where()","np.extract()","np.any(), np.all()","تطبيق: تصفية شاذة","مشروع: تنظيف بـ Masking"),
U("الجبر الخطي مع NumPy","@ و np.dot()","linalg.inv()","linalg.det()","linalg.norm()","linalg.solve()","تطبيق: انحدار بـ NumPy","مشروع: PCA بسيط"),
U("توليد أرقام عشوائية","seed() للتكرار","rand, randn","randint, choice","shuffle","توليد بيانات وهمية","Monte Carlo بسيط","مشروع: محاكاة"),
U("مشروع: تحليل بـ NumPy","تخطيط","تحميل","تنظيف","إحصاء","كشف شواذ","تصدير","توثيق","عرض"),
),
S("Pandas: عمود تحليل البيانات","DataFrame, تنظيف, GroupBy, دمج",
U("مقدمة Pandas","Series و DataFrame","df.head, info, describe","shape, columns, index","إنشاء من dict و CSV","dtypes","df['col']","مشروع: أول DataFrame"),
U("الفهرسة والوصول","loc: بالاسم","iloc: بالموقع","at, iat","تحديد صفوف وأعمدة","df[df['col'] > val]","شروط مركبة: &","query()","مشروع: استعلامات"),
U("تصفية وفرز","df[df['col'] > val]","isin()","str.contains()","sort_values()","sort_index()","nlargest, nsmallest","مشروع: تصفية مبيعات"),
U("إضافة وتعديل الأعمدة","df['new'] = expr","assign()","rename()","drop()","astype()","apply()","map()","مشروع: تنظيف وإثراء"),
U("القيم المفقودة","isna().sum()","dropna()","fillna()","ffill","interpolate()","SimpleImputer","مشروع: تنظيف حقيقي"),
U("GroupBy: التجميع","groupby().mean()","agg(): دوال متعددة","transform()","filter()","pivot_table()","crosstab()","مشروع: تقارير مجمعة"),
U("دمج البيانات","merge(): دمج","left,right,inner,outer","concat(): تكديس","concat(axis=1): لصق","join(): فهرس","حل تعارضات","مشروع: دمج مصادر"),
U("السلاسل الزمنية","to_datetime()","date_range()","set_index(date)","resample()","rolling()","shift(), diff()","مشروع: تحليل زمني"),
U("مشروع: تحليل مبيعات","استيراد","تنظيف","تحليل","تجميعات","رسوم","رؤى","توثيق","عرض"),
),
S("Matplotlib: تصوير البيانات","رسوم بيانية احترافية",
U("أساسيات Matplotlib","plt.plot()","plt.scatter()","plt.bar()","عناوين ومحاور","figsize","savefig()","مشروع: أول رسم"),
U("تخصيص الرسوم","ألوان وأنماط","markers","linewidth, alpha","grid, legend","xlim, ylim","annotate()","مشروع: رسم احترافي"),
U("Subplots","plt.subplots()","مشاركة المحاور","tight_layout()","أحجام مختلفة","عناوين فرعية","مشروع: Dashboard"),
U("الرسوم الإحصائية","plt.hist()","plt.boxplot()","plt.pie() (بحذر)","bins, density","cumulative hist","مشروع: توزيعات"),
U("الرسوم الفئوية","bar chart مقارن","stacked bar","grouped bar","horizontal bar","مشروع: مقارنات"),
U("رسوم السلاسل الزمنية","plot() مع تاريخ","تنسيق محور التاريخ","نطاقات زمنية","trend lines","مشروع: تحليل زمني"),
U("حفظ وتصدير","savefig() بصيغ","dpi","bbox_inches","transparent","SVG","مشروع: تصدير"),
U("Pandas + Matplotlib","df.plot()","kind=line,bar,hist","subplots=True","تنسيق رسوم Pandas","مشروع: تحليل وتصوير"),
U("مشروع: Dashboard","تخطيط","جمع بيانات","رسوم متعددة","تنسيق","عرض"),
),
S("الإحصاء الوصفي","مقاييس النزعة والتشتت",
U("مقاييس النزعة","mean(), median(), mode()","متى المتوسط والوسيط؟","البيانات المنحرفة","تطبيق Pandas","مشروع: نزعة مركزية"),
U("مقاييس التشتت","std(), var()","range","IQR","percentile, quantile","معامل الاختلاف","مشروع: تشتت"),
U("التوزيعات التكرارية","value_counts()","bins, histogram","frequency tables","relative freq","cumulative","مشروع: توزيع"),
U("Boxplot والكشف عن الشواذ","مكونات boxplot","outliers","IQR method","مقارنة مجموعات","sns.boxplot()","مشروع: كشف شواذ"),
U("الارتباط Correlation","Pearson r","Spearman","df.corr()","sns.heatmap()","Correlation ≠ Causation","مشروع: ارتباطات"),
U("التوزيع الطبيعي","خصائص التوزيع","skewness","kurtosis","QQ Plot","Shapiro-Wilk","مشروع: فحص التوزيع"),
U("القيم الشاذة","Z-score method","IQR method","Isolation Forest","متى تحذف؟","تصور","مشروع: معالجة شواذ"),
U("جداول ملخصة","df.describe() بعمق","style.background_gradient()","pivot_table للعرض","groupby مع agg","مشروع: تقرير إحصائي"),
U("مشروع: تقرير إحصائي","تخطيط","جمع","تحليل","رسوم","توصيات","عرض"),
),
S("استيراد البيانات","CSV, JSON, APIs, SQL",
U("قراءة CSV","pd.read_csv()","sep, encoding","header, skiprows","na_values","to_csv()","مشروع: CSV"),
U("Excel و JSON","pd.read_excel()","sheet_name","pd.read_json()","orient","nested JSON","مشروع: Excel"),
U("APIs","requests.get()","JSON response","لـ DataFrame","API keys","rate limiting","مشروع: API"),
U("Web Scraping","requests + BS4","pd.read_html()","CSS selectors","أخلاقيات","مشروع: Scrape"),
U("SQL","pd.read_sql()","sqlite3","استعلامات","JOIN مع Pandas","مشروع: SQL"),
U("الملفات الكبيرة","chunksize","معالجة chunk","memory usage","dtype optimization","مشروع: ملف كبير"),
U("تنظيف المستورد","توحيد تنسيق","معالجة ترميز","إزالة مسافات","تواريخ بنسق مختلف","مشروع: تنظيف استيراد"),
U("دمج مصادر متعددة","merge","concat","حل تعارضات","مفتاح موحد","مشروع: دمج مصادر"),
U("مشروع: Data Pipeline","جمع من 3 مصادر","تنظيف","دمج","تحليل","تصدير","عرض"),
),
S("مشروع المستوى","تطبيق كل المهارات",
U("تخطيط المشروع","تحديد الأسئلة","بيانات","خطة","أدوات"),
U("جمع البيانات","CSV, Excel","دمج","جودة","توثيق"),
U("تنظيف وتحضير","مفقود","تكرار","أنواع","تنسيق"),
U("التحليل الاستكشافي","إحصائيات","توزيعات","علاقات","فرضيات"),
U("التحليل الإحصائي","اختبارات","ارتباطات","انحدار","استنتاجات"),
U("التصوير البياني","رسوم","Dashboard","تنسيق"),
U("كتابة التقرير","ملخص","منهجية","نتائج","توصيات"),
U("العرض النهائي","تقديم","قصة","رسوم","نتائج"),
),
),
L("المستوى الثاني: تحليل البيانات الاستكشافي","تنظيف متقدم, EDA, Seaborn, سلاسل زمنية","analyze",
S("تنظيف البيانات المتقدم","معالجة البيانات الواقعية",
U("القيم المفقودة","MCAR,MAR,MNAR","dropna vs fillna","interpolate","SimpleImputer","KNN Imputer","مقارنة","مشروع: تنظيف"),
U("التكرارات والشواذ","duplicated()","IQR method","Z-score","Isolation Forest","حذف أم إبقاء؟","مشروع: كشف شواذ"),
U("توحيد أنواع البيانات","astype()","to_numeric()","to_datetime()","category type","توحيد النصوص","مشروع: توحيد"),
U("توحيد الصيغ","تواريخ بنسق مختلف","عملات ورموز","وحدات قياس","regex للتنظيف","مشروع: صيغ"),
U("تصحيح غير المنطقي","قيم سالبة للعمر","تواريخ مستقبلية","خارج النطاق","التحقق","مشروع: تصحيح"),
U("التحقق من الصحة","assert","قيود الأعمال","فحص الاتساق","automated checks","مشروع: مدقق"),
U("تحويل المتغيرات","log, Box-Cox","Yeo-Johnson","PowerTransformer","Binning: pd.cut()","مشروع: تحويلات"),
U("ترميز الفئوية","OneHotEncoder","LabelEncoder","OrdinalEncoder","get_dummies()","مشروع: ترميز"),
U("مشروع: Pipeline تنظيف","تخطيط","تنفيذ","اختبار","توثيق","عرض"),
),
S("التحليل الاستكشافي EDA","استخلاص الرؤى",
U("Univariate","histograms, boxplots","مقاييس النزعة","مقاييس التشتت","value_counts","مشروع: أحادي"),
U("Bivariate","Scatter plots","Correlation","Contingency tables","groupby","مشروع: ثنائي"),
U("Multivariate","Pairplot","parallel coords","3D scatter","PCA viz","مشروع: متعدد"),
U("تحليل العلاقات","Correlation matrix","Heatmap","Partial correlation","Mutual Information","مشروع: ارتباط"),
U("تحليل التوزيعات","Histogram + KDE","QQ Plot","Statistical tests","Distribution fitting","مشروع: توزيع"),
U("تحليل الشرائح","groupby + describe","pivot_table","crosstab","comparison","مشروع: شرائح"),
U("أتمتة تقارير EDA","pandas-profiling","sweetviz","ydata-profiling","مشروع: تلقائي"),
U("توثيق EDA","كتابة التقارير","الرسوم الرئيسية","النتائج","التوصيات","مشروع: تقرير"),
U("مشروع: EDA كامل","بيانات","تحليل","رؤى","تقرير","عرض"),
),
S("Seaborn: تصوير متقدم","رسوم إحصائية",
U("مقدمة Seaborn","set_theme()","histplot, kdeplot","boxplot, violinplot","مشروع: أول رسم"),
U("Categorical Plots","barplot, countplot","stripplot, swarmplot","hue parameter","مشروع: فئوية"),
U("Relational Plots","scatterplot, lineplot","relplot","hue, size, style","FacetGrid","مشروع: علاقات"),
U("Distribution Plots","histplot, kdeplot","ecdfplot","rug plot","bins, bandwidth","مشروع: توزيعات"),
U("Heatmaps","sns.heatmap()","annot, fmt, cmap","correlation heatmap","clustermap","مشروع: Heatmap"),
U("Pairplot","sns.pairplot()","hue, diag_kind","PairGrid","corner plots","مشروع: Pairplot"),
U("Jointplot","sns.jointplot()","kind options","marginal dists","regression line","مشروع: Jointplot"),
U("تخصيص Seaborn","context, style","palettes","despine()","مع Matplotlib","مشروع: تنسيق"),
U("مشروع: Dashboard Seaborn","تخطيط","رسوم","تنسيق","رؤى","عرض"),
),
S("السلاسل الزمنية","تحليل عبر الزمن",
U("أساسيات","to_datetime()","set_index(date)","resample()","rolling()","shift,diff","مشروع: أول سلسلة"),
U("الاتجاه Trend","moving average","rolling mean","linear trend","polynomial","مشروع: اتجاه"),
U("الموسمية","seasonal_decompose()","STL","monthly/quarterly","seasonal subseries","مشروع: موسمية"),
U("Autocorrelation","autocorr plot","ACF, PACF","lag analysis","مشروع: ACF/PACF"),
U("التنبؤ البسيط","naive forecast","seasonal naive","mean forecast","drift","مشروع: تنبؤ"),
U("Exponential Smoothing","Simple","Holt","Holt-Winters","alpha,beta,gamma","مشروع: Smoothing"),
U("كشف anomalies","rolling stats","threshold","isolation forest","change point","مشروع: Anomalies"),
U("تصوير السلاسل","line plot","seasonal plot","lag plot","autocorr plot","مشروع: تصوير"),
U("مشروع: تحليل زمني","بيانات","تحلل","تنبؤ","تقرير","عرض"),
),
S("الإحصاء الاستدلالي","احتمالات واختبارات",
U("الاحتمالات","Normal, Binomial, Poisson","scipy.stats","PDF, CDF","random sampling","مشروع: توزيعات"),
U("نظرية المعاينة","CLT","sampling dist","standard error","sample size","مشروع: CLT"),
U("فترات الثقة","CI","z-interval, t-interval","margin of error","bootstrap CI","مشروع: CI"),
U("اختبار الفرضيات","H0, H1, p-value","Type I/II","alpha, beta","power analysis","مشروع: اختبار"),
U("t-test","One-sample","Two-sample","Paired","Welch's","مشروع: t-test"),
U("Chi-Square","independence","contingency","expected freq","Cramer's V","مشروع: ChiSquare"),
U("ANOVA","One-way","F-test","Tukey HSD","effect size","مشروع: ANOVA"),
U("Non-parametric","Mann-Whitney","Kruskal-Wallis","Wilcoxon","متى تستخدم؟","مشروع: NonParam"),
U("مشروع: تحليل استدلالي","بيانات","اختبارات","استنتاجات","تقرير","عرض"),
),
S("Plotly: رسوم تفاعلية","Interactive visualization",
U("Plotly Express","px.scatter()","px.line()","px.bar()","px.histogram()","hover data","مشروع: أول رسم"),
U("تخصيص Plotly","update_layout()","update_traces()","colors, themes","annotations","مشروع: تنسيق"),
U("رسوم متقدمة","px.scatter_3d()","px.density_heatmap()","px.treemap()","px.sunburst()","مشروع: متقدم"),
U("Dashboards","subplots","make_subplots()","linked views","dropdowns","مشروع: Dashboard"),
U("Geo-visualization","px.choropleth()","px.scatter_geo()","px.scatter_mapbox()","geoJSON","مشروع: خرائط"),
U("Animations","animation_frame","animated bubble","time series anim","مشروع: Animation"),
U("حفظ ومشاركة","write_html()","write_image()","kaleido","embedding","مشروع: نشر"),
U("Plotly vs Matplotlib","مقارنة","متى تستخدم؟","التكامل","مشروع: مقارنة"),
U("مشروع: Dashboard تفاعلي","تخطيط","بناء","تنسيق","نشر","عرض"),
),
S("مشروع المستوى: تحليل متكامل","تطبيق EDA كامل",
U("تخطيط","أسئلة","بيانات","خطة","أدوات"),
U("تنظيف","استيراد","تنظيف","توحيد","تحويلات"),
U("EDA","Uni,Bi,Multivariate","توزيعات","علاقات"),
U("تحليل إحصائي","اختبارات","CI","ارتباطات","انحدار"),
U("سلاسل زمنية","Trend","Seasonality","Anomalies","تنبؤ"),
U("تصوير متقدم","Seaborn","Plotly","تفاعلي","تنسيق"),
U("كتابة تقرير","ملخص","منهجية","نتائج","توصيات"),
U("عرض نهائي","تقديم","قصة","رؤى","توصيات"),
),
),
L("المستوى الثالث: التعلم الآلي","انحدار, تصنيف, Ensemble, Clustering","apply",
S("أساسيات التعلم الآلي","مفاهيم، تقييم، Scikit-learn",
U("ما هو تعلم الآلة؟","Supervised, Unsupervised","Reinforcement","سير العمل","Overfitting","مشروع: استكشاف"),
U("Scikit-learn API","Estimator API","fit, predict","train_test_split","cross_val_score","مشروع: أول نموذج"),
U("مقاييس التقييم","Regression: MSE,R²","Classification: Acc,Precision,Recall,F1","ROC,AUC","classification_report","مشروع: تقييم"),
U("Bias-Variance","Underfitting","Overfitting","Validation Curve","Learning Curve","مشروع: تشخيص"),
U("Cross-Validation","K-Fold","Stratified","Repeated","cross_validate","مشروع: CV"),
U("Grid Search","GridSearchCV","param_grid","best_params_","RandomizedSearchCV","مشروع: GridSearch"),
U("Pipelines","Pipeline()","ColumnTransformer","مع GridSearch","حفظ","مشروع: Pipeline"),
U("Data Leakage","Scaler قبل التقسيم","مستقبل","كيف تمنعه؟","Pipeline حماية","مشروع: كشف Leakage"),
U("مشروع: أول مشروع ML","بيانات","نموذج","تقييم","تحسين","عرض"),
),
S("الانحدار: التنبؤ بالقيم","Linear, Ridge, Lasso, Polynomial",
U("Linear Regression","y = wx + b","fit, predict","coef_, intercept_","R²","مشروع: انحدار"),
U("تقييم الانحدار","MSE, RMSE, MAE","Residual Analysis","QQ Plot","Heteroscedasticity","مشروع: تقييم"),
U("Ridge Regression","L2 Regularization","alpha","لماذا Ridge؟","CV لاختيار alpha","مشروع: Ridge"),
U("Lasso Regression","L1 Regularization","Feature Selection","alpha","مقارنة Ridge","مشروع: Lasso"),
U("Elastic Net","L1 + L2","l1_ratio","متى؟","مقارنة","مشروع: ElasticNet"),
U("Polynomial Regression","PolynomialFeatures","degree","خطر overfitting","مع Regularization","مشروع: Polynomial"),
U("افتراضات الانحدار","الخطية","استقلال","Homoscedasticity","Normality","مشروع: افتراضات"),
U("مقارنة نماذج","Linear vs Ridge vs Lasso","ElasticNet vs Polynomial","اختيار","مشروع: مقارنة"),
U("مشروع: توقع الأسعار","بيانات","هندسة","نماذج","تقييم","عرض"),
),
S("التصنيف: تمييز الفئات","Logistic, Trees, SVM, KNN",
U("Logistic Regression","Sigmoid","Decision Boundary","predict_proba","C parameter","مشروع: تصنيف"),
U("تقييم التصنيف","Confusion Matrix","Precision,Recall,F1","ROC,AUC","threshold","مشروع: تقييم"),
U("Decision Trees","Gini,Entropy","max_depth","min_samples","feature_importances_","مشروع: شجرة"),
U("Random Forest","n_estimators","Bootstrap","OOB Error","importance","مشروع: غابة"),
U("SVM","Linear SVM","Kernel: RBF","C, gamma","decision boundary","مشروع: SVM"),
U("KNN","المسافات","n_neighbors","scaling ضروري","weights","مشروع: KNN"),
U("مقارنة المصنفات","Logistic vs Tree vs Forest","SVM vs KNN","ROC comparison","مشروع: مقارنة"),
U("عدم التوازن","SMOTE","class_weight","sampling","metrics","مشروع: توازن"),
U("مشروع: تصنيف","بيانات","نماذج","مقارنة","أفضل","عرض"),
),
S("Ensemble Methods","Random Forest, Boosting, XGBoost",
U("Bagging","Bootstrap","Random Forest","متوازي","OOB","مشروع: Bagging"),
U("Boosting","AdaBoost","Gradient Boosting","متسلسل","lr","مشروع: Boosting"),
U("XGBoost","n_estimators,lr","max_depth","early_stopping","eval_set","مشروع: XGBoost"),
U("LightGBM","leaf-wise","categorical","GPU","مشروع: LightGBM"),
U("CatBoost","ordered boosting","categorical","text","مشروع: CatBoost"),
U("Stacking","base estimators","final estimator","cross_val_predict","مشروع: Stacking"),
U("ضبط Ensemble","GridSearchCV","Randomized","Optuna","Bayesian","مشروع: Tuning"),
U("SHAP: تفسير","Feature Importance","Permutation","SHAP values","summary_plot","مشروع: SHAP"),
U("مشروع: مسابقة Ensemble","بيانات","Ensemble","Tuning","تقديم","عرض"),
),
S("Clustering: غير المراقب","K-Means, DBSCAN, Hierarchical",
U("K-Means","خوارزمية","n_clusters","centroids","inertia","مشروع: KMeans"),
U("اختيار k","Elbow Method","Silhouette","Gap Statistic","Davies-Bouldin","مشروع: اختيار"),
U("DBSCAN","eps,min_samples","density","noise","أي شكل","مشروع: DBSCAN"),
U("Hierarchical","Agglomerative","Dendrogram","linkage","cutting","مشروع: Hierarchical"),
U("GMM","EM Algorithm","soft clustering","BIC,AIC","مشروع: GMM"),
U("تقييم التجميع","Silhouette","Calinski-Harabasz","Davies-Bouldin","visual","مشروع: تقييم"),
U("Anomaly Detection","Isolation Forest","One-Class SVM","LOF","contamination","مشروع: شواذ"),
U("تطبيقات","Customer Segmentation","Image Compression","Document Clustering","مشروع: تطبيق"),
U("مشروع: تقسيم العملاء","بيانات","تجميع","توصيف","رؤى","عرض"),
),
S("Feature Engineering","إنشاء واختيار الميزات",
U("إنشاء الميزات","Domain knowledge","ratios,diffs","date features","aggregations","مشروع: إنشاء"),
U("تحويل الميزات","log,sqrt,BoxCox","YeoJohnson","binning","polynomial","مشروع: تحويل"),
U("Filter Methods","Variance Threshold","Correlation","Mutual Info","Chi2","مشروع: Filter"),
U("Wrapper Methods","RFE","Forward Select","Backward Elim","Sequential","مشروع: Wrapper"),
U("Embedded Methods","Lasso(L1)","Tree Importance","Permutation","SHAP selection","مشروع: Embedded"),
U("PCA","explained_variance","n_components","scaling","components","مشروع: PCA"),
U("t-SNE و UMAP","visualization only","perplexity","n_neighbors","comparison","مشروع: tSNE"),
U("Featuretools","dfs()","entityset","deep synthesis","مشروع: Featuretools"),
U("مشروع: هندسة ميزات","بيانات","إنشاء","اختيار","تحويل","تقييم","عرض"),
),
S("مشروع المستوى: نموذج متكامل","تطبيق ML كامل",
U("تحديد المشكلة","هدف","بيانات","مقاييس","خطة"),
U("EDA","استكشاف","تصوير","فرضيات","رؤى"),
U("هندسة ميزات","إنشاء","اختيار","تحويل","تقييم"),
U("بناء Baselines","نموذج بسيط","تقييم","تحليل","خط أساس"),
U("تجربة نماذج","انحدار/تصنيف","Ensemble","مقارنة","اختيار"),
U("تحسين","GridSearch","ميزات جديدة","Stacking","أفضل"),
U("تقييم نهائي","تقرير","Feature Importance","تحليل","حدود"),
U("عرض","ملخص","نتائج","توصيات","دروس"),
),
),
L("المستوى الرابع: التعلم الآلي المتقدم","Boosting متقدم,SVM,PCA,Imbalanced,SHAP","evaluate",
S("Gradient Boosting المتقدم","XGBoost, LightGBM, CatBoost بعمق",
U("XGBoost بعمق","DMatrix","objective functions","custom metrics","GPU","مشروع: XGBoost عميق"),
U("LightGBM بعمق","leaf-wise","categorical","GPU","tuning","مشروع: LightGBM عميق"),
U("CatBoost بعمق","ordered boosting","text features","categorical","overfitting detector","مشروع: CatBoost عميق"),
U("مقارنة Boosting","XGB vs LGB vs Cat","benchmarks","متى تستخدم؟","مشروع: مقارنة"),
U("Early Stopping","eval_set,eval_metric","patience","best_iteration","prevention","مشروع: EarlyStopping"),
U("Feature Importance","gain,cover,weight","SHAP for Boosting","summary,dependence","مشروع: SHAP"),
U("Hyperparameter Optimization","Optuna","Hyperopt","Bayesian","pruning","مشروع: Optuna"),
U("Stacking متقدم","multiple base","CV predictions","meta-learner","مشروع: Stacking"),
U("مشروع: Boosting","بيانات","Tuning","تقييم","SHAP","عرض"),
),
S("SVM بعمق","Support Vector Machines",
U("SVM النظري","Maximal Margin","Support Vectors","Hinge Loss","Kernel Trick","مشروع: نظري"),
U("Linear SVM","LinearSVC","C parameter","soft vs hard","مشروع: Linear"),
U("Kernel SVM","RBF kernel","gamma","polynomial","sigmoid","مشروع: Kernel"),
U("SVR","epsilon","epsilon-tube","kernel SVR","مشروع: SVR"),
U("ضبط SVM","GridSearch C,gamma","validation curve","scaling","مشروع: Tuning"),
U("One-Class SVM","novelty detection","outlier detection","nu","مشروع: OneClass"),
U("SVM + Imbalanced","class_weight","SMOTE + SVM","decision_function","مشروع: Imbalanced"),
U("SVM vs غيرها","SVM vs RF","SVM vs Boosting","متى SVM؟","مشروع: مقارنة"),
U("مشروع: SVM","بيانات","معاملات","تقييم","عرض"),
),
S("تخفيف الأبعاد","PCA, t-SNE, UMAP",
U("PCA بعمق","eigenvalues","explained_variance","scree plot","biplot","مشروع: PCA عميق"),
U("اختيار المكونات","explained_variance_ratio","cumulative","elbow","cross-val","مشروع: اختيار"),
U("t-SNE","perplexity","exaggeration","lr","limitations","مشروع: tSNE"),
U("UMAP","n_neighbors","min_dist","metric","supervised","مشروع: UMAP"),
U("TruncatedSVD","sparse data","LSA","topic modeling","مشروع: TSVD"),
U("Factor Analysis","latent variables","loadings","rotation","مشروع: FA"),
U("تطبيقات","Noise reduction","Visualization","Preprocessing","Feature extraction","مشروع: تطبيق"),
U("مقارنة","PCA vs tSNE vs UMAP","linear vs nonlinear","cost","مشروع: مقارنة"),
U("مشروع: تخفيف أبعاد","بيانات عالية","PCA+tSNE","تصور","عرض"),
),
S("البيانات غير المتوازنة","SMOTE, Class Weights, Evaluation",
U("مشكلة عدم التوازن","impact","accuracy paradox","real-world","مشروع: تشخيص"),
U("Oversampling","RandomOverSampler","SMOTE","ADASYN","Borderline","مشروع: Oversample"),
U("Undersampling","RandomUnderSampler","TomekLinks","NearMiss","CNN","مشروع: Undersample"),
U("Class Weights","balanced","compute_class_weight","sklearn","custom","مشروع: Weights"),
U("Evaluation Metrics","PR Curve","F1,F2,F0.5","AUC-PR","Cohen's Kappa","مشروع: مقاييس"),
U("Threshold Tuning","decision_function","predict_proba","optimization","cost-sensitive","مشروع: Threshold"),
U("Ensemble for Imbalanced","BalancedRF","EasyEnsemble","RUSBoost","مشروع: Ensemble"),
U("مقارنة استراتيجيات","SMOTE vs Weight vs Ensemble","pipeline","مشروع: مقارنة"),
U("مشروع: تصنيف نادر","بيانات","استراتيجيات","تقييم","عرض"),
),
S("تفسير النماذج","SHAP, LIME, PDP",
U("لماذا التفسير؟","Trust,debug,fairness","regulations","business","مشروع: أهمية"),
U("SHAP","Shapley values","TreeExplainer","KernelExplainer","summary_plot","مشروع: SHAP"),
U("SHAP متقدم","dependence_plot","force_plot","waterfall","interaction","مشروع: SHAP متقدم"),
U("LIME","local surrogate","perturbation","explanation","limitations","مشروع: LIME"),
U("PDP","partial dependence","ICE plots","centered ICE","limitations","مشروع: PDP"),
U("Permutation Importance","model-agnostic","multiple runs","limitations","مشروع: Permutation"),
U("Global Surrogate","interpretable approx","tree surrogate","linear surrogate","مشروع: Surrogate"),
U("Interpretability for DL","Grad-CAM","Integrated Gradients","DeepLIFT","مشروع: DL Interpret"),
U("مشروع: تفسير نموذج","SHAP","PDP","LIME","تقرير","عرض"),
),
S("AutoML","أتمتة التعلم الآلي",
U("مقدمة AutoML","ما هو؟","متى؟","limitations","مشروع: مقدمة"),
U("TPOT","genetic programming","pipeline optimization","generations","مشروع: TPOT"),
U("AutoGluon","multi-layer stacking","tabular,text,image","fast","مشروع: AutoGluon"),
U("H2O AutoML","leaderboard","stacked ensembles","explainability","مشروع: H2O"),
U("PyCaret","low-code","compare_models()","blend_models()","مشروع: PyCaret"),
U("FLAML","Microsoft","low cost","search space","مشروع: FLAML"),
U("مقارنة","TPOT vs AutoGluon vs H2O vs PyCaret","benchmarks","مشروع: مقارنة"),
U("AutoML في الإنتاج","retraining","monitoring","limitations","مشروع: إنتاج"),
U("مشروع: AutoML","بيانات","أدوات","مقارنة","أفضل","عرض"),
),
S("مشروع المستوى: نظام عالي الدقة","تطبيق ML متقدم",
U("تحديد المشكلة","هدف","بيانات","مقاييس","خطة"),
U("هندسة متقدمة","إنشاء","اختيار","تخفيف","تقييم"),
U("نماذج متقدمة","XGBoost,LGB","SVM","Ensemble","Stacking"),
U("تحسين شامل","Optuna","CV","Selection","EarlyStopping"),
U("عدم التوازن","SMOTE,Weights","Evaluation","Threshold","استراتيجية"),
U("تفسير","SHAP,LIME","PDP","Importance","Fairness"),
U("تقييم نهائي","تقرير","تحليل","حدود","تحسينات"),
U("عرض","ملخص","نتائج","توصيات","دروس"),
),
),
L("المستوى الخامس: الإنتاج والتطبيقات المتقدمة","DL, NLP, MLOps, Big Data, نشر","create",
S("مقدمة التعلم العميق","Neural Networks, Keras, CNN",
U("ما هو DL؟","شبكات عصبية","لماذا الآن؟","GPU","تطبيقات","مشروع: مقدمة"),
U("Perceptron و MLP","perceptron","multi-layer","activation","forward pass","مشروع: Perceptron"),
U("Backpropagation","gradient","chain rule","weight update","loss","مشروع: Backprop"),
U("Keras Sequential","Dense layers","compile,fit","EarlyStopping","Checkpoint","مشروع: Keras"),
U("CNN","Conv2D,MaxPool","feature maps","Flatten,Dense","مشروع: CNN"),
U("Transfer Learning","VGG16,ResNet","include_top=False","fine-tuning","augmentation","مشروع: Transfer"),
U("Regularization DL","Dropout","BatchNorm","L1/L2","augmentation","مشروع: Regularization"),
U("Callbacks","EarlyStopping","ReduceLROnPlateau","TensorBoard","مشروع: Callbacks"),
U("مشروع: تصنيف صور","بيانات","CNN","تدريب","تقييم","عرض"),
),
S("NLP: معالجة النصوص","Text Preprocessing, Embeddings, Classification",
U("Text Preprocessing","tokenization","lower,punctuation","stop words","stemming","مشروع: تنظيف"),
U("TF-IDF","CountVectorizer","TfidfVectorizer","ngram_range","max_features","مشروع: TFIDF"),
U("Word Embeddings","Word2Vec,GloVe","embedding space","similarity","transfer","مشروع: Embeddings"),
U("Text Classification","Naive Bayes","Logistic+TFIDF","Deep Learning","مشروع: تصنيف"),
U("Sentiment Analysis","VADER","lexicon-based","ML-based","aspect-based","مشروع: مشاعر"),
U("Topic Modeling","LDA","coherence score","pyLDAvis","num topics","مشروع: مواضيع"),
U("NER","spaCy","entity types","training NER","مشروع: NER"),
U("Transformers: BERT","HuggingFace","pipeline","fine-tuning","tokenizer","مشروع: BERT"),
U("مشروع: تحليل نصوص","بيانات","معالجة","تصنيف","عرض"),
),
S("التنبؤ بالسلاسل الزمنية","ARIMA, Prophet, LSTM",
U("ARIMA Models","stationarity","differencing","ACF,PACF","order selection","مشروع: ARIMA"),
U("SARIMA و SARIMAX","seasonal ARIMA","exogenous","seasonal order","مشروع: SARIMA"),
U("Prophet","trend,seasonality","holidays","changepoints","uncertainty","مشروع: Prophet"),
U("LSTM للسلاسل","sequence prep","window size","LSTM architecture","مشروع: LSTM"),
U("مقارنة النماذج","ARIMA vs Prophet vs LSTM","accuracy","cost","مشروع: مقارنة"),
U("Multivariate Forecasting","multiple series","VAR,VARMAX","DL","مشروع: Multivariate"),
U("تقييم التنبؤ","MAE,RMSE,MAPE","residual analysis","backtesting","مشروع: تقييم"),
U("نشر نموذج التنبؤ","API","retraining schedule","drift monitoring","مشروع: نشر"),
U("مشروع: نظام تنبؤ","بيانات","نماذج","مقارنة","نشر","عرض"),
),
S("Big Data و Spark","معالجة البيانات الضخمة",
U("مقدمة Big Data","3Vs","MapReduce","Spark ecosystem","مشروع: مقدمة"),
U("PySpark Basics","SparkSession","DataFrame API","transform vs action","lazy","مشروع: PySpark"),
U("Spark SQL","SQL queries","DataFrame ops","UDFs","مشروع: SparkSQL"),
U("Spark MLlib","ML Pipeline","transformers,estimators","CV","مشروع: MLlib"),
U("Dask","lazy evaluation","parallel","Dask DataFrame","مشروع: Dask"),
U("Pandas vs Spark vs Dask","مقارنة","متى؟","memory vs disk","مشروع: مقارنة"),
U("ملفات ضخمة","partitioning","parquet","compression","chunked","مشروع: ضخم"),
U("Big Data سحابي","AWS EMR","Databricks","Dataproc","مشروع: سحابة"),
U("مشروع: بيانات ضخمة","بيانات","Spark/Dask","تحليل","عرض"),
),
S("MLOps: نشر النماذج","Flask, FastAPI, Docker, Cloud",
U("حفظ النماذج","pickle,joblib","ONNX","TF SavedModel","versioning","مشروع: حفظ"),
U("Flask API","@app.route","request.json","jsonify","errors","مشروع: Flask"),
U("FastAPI","Pydantic","auto docs","async","validation","مشروع: FastAPI"),
U("Docker","Dockerfile","build/run","compose","registry","مشروع: Docker"),
U("Cloud Deployment","SageMaker","Vertex AI","Azure ML","HF Spaces","مشروع: سحابة"),
U("CI/CD for ML","GitHub Actions","testing","auto deploy","registry","مشروع: CICD"),
U("Model Monitoring","data drift","concept drift","performance","alerts","مشروع: مراقبة"),
U("A/B Testing","traffic splitting","stat significance","shadow deploy","مشروع: AB"),
U("مشروع: نشر متكامل","نموذج","API","Docker","Cloud","عرض"),
),
S("أخلاقيات البيانات","Fairness, Privacy, GDPR",
U("Bias in ML","types","detection","mitigation","fairness metrics","مشروع: تحيز"),
U("Explainable AI","SHAP,LIME","model cards","transparency","مشروع: XAI"),
U("Privacy","differential privacy","federated learning","anonymization","مشروع: خصوصية"),
U("GDPR و AI Act","principles","right to explanation","compliance","assessment","مشروع: GDPR"),
U("Fairness Metrics","demographic parity","equal opportunity","equalized odds","calibration","مشروع: Fairness"),
U("Model Cards","purpose","training data","evaluation","limitations","مشروع: ModelCard"),
U("Adversarial Robustness","examples","FGSM,PGD","defenses","certification","مشروع: Robustness"),
U("Responsible AI","principles","governance","auditing","monitoring","مشروع: Responsible"),
U("مشروع: تدقيق أخلاقي","نموذج","bias","fairness","تقرير","عرض"),
),
S("المشروع الختامي","نظام بيانات متكامل",
U("تحديد المشكلة","هدف","بيانات","مقاييس","خطة"),
U("جمع وتحضير","مصادر","تنظيف","توحيد","EDA"),
U("هندسة ميزات","إنشاء","اختيار","تحويل","تقييم"),
U("بناء النموذج","خوارزمية","تدريب","تحسين","أفضل"),
U("تقييم","مقاييس","تحليل","حدود","تحسينات"),
U("بناء API","FastAPI","Pydantic","Docker","اختبار"),
U("نشر","Cloud","CI/CD","مراقبة","توثيق"),
U("عرض نهائي","قصة","نتائج","Demo","دروس"),
),
),
]

M = [
("Data Leakage","Scaler قبل التقسيم = اختبار يتسرب للتدريب = دقة وهمية.","اقسم أولاً. scaler.fit(X_train). scaler.transform(X_test). Pipeline.","لا تدع معلومات الاختبار تتسرب. Pipeline يمنع هذا تلقائياً.","critical"),
("Accuracy على غير متوازنة","95% فئة A. نموذج يتنبأ دائماً بـ A = 95% لكنه فاشل.","Precision, Recall, F1, confusion_matrix, classification_report.","قبل اختيار المقياس: ما الفئة الأهم؟ Accuracy مضللة.","major"),
("عدم توحيد المقياس","متغير 1-1000 يسيطر على المسافات = تجميع وتصنيف سيئ.","StandardScaler قبل K-Means, KNN, SVM, NN. Trees لا تحتاج.","كل نموذج يعتمد على المسافة أو gradient descent يحتاج scaling.","major"),
("Overfitting","دقة تدريب 99%، اختبار 65%. النموذج حفظ ولم يتعلم.","تبسيط، بيانات أكثر، Regularization، CV، EarlyStopping.","افحص الفجوة بين train و test دائماً. Validation Curve.","critical"),
("حلقات for مع Pandas","for على 100K صف: 5 ثوان. متجهة: 0.002 ثانية.","df['new'] = df['a'] + df['b']. apply() فقط للحالات الخاصة.","إذا كتبت for مع Pandas، توقف. هل هناك طريقة متجهة؟","minor"),
("نسيان fillna/dropna","mean() على عمود فيه NaN يعطي NaN.","df.isna().sum() فحص، df.fillna() أو df.dropna().","نظف بياناتك أولاً. تحليل على غير نظيف = نتائج غير موثوقة.","major"),
("عدم استخدام Pipeline","خطوات يدوية = نسيان = Data Leakage.","Pipeline([('scaler',Scaler()),('model',Model())]).","Pipeline صديقك. يحميك من نفسك. استخدمه دائماً.","major"),
("train_test_split بدون stratify","فئة نادرة 5% قد لا تظهر في training أو test.","stratify=y في train_test_split يحافظ على نسب الفئات.","دائماً استخدم stratify للتصنيف. يحافظ على توزيع متوازن.","major"),
]

def mb(p,c):return[
f"الآن أتقنتَ {p}، نرتقي إلى {c}.",
f"في الدرس السابق فككنا {p}. اليوم نبني عليه بـ {c}.",
f"بعد {p}، {c} يسد الفجوة التالية.",
f"{p} كان الأساس. {c} هو الطابق التالي.",
][h(p+c)%4]

def gl(uc,lt,sn):
 ls=[];pv="المفاهيم الأساسية"
 for li,t in enumerate(lt,1):
  nm=2+(h(f"{uc}_{li}")%2);lm=[{"mistake":f"{m[0]}\n{m[1]}","correction":m[2],"treatment":m[3],"severity":m[4]} for m in [M[(h(f"{uc}_{li}_{mi}"))%len(M)] for mi in range(nm)]]
  ls.append({"lesson_index":li,"name":t,"goal":f"فهم وتطبيق {t}","bridge_sentence":mb(pv,t),"prerequisite_lessons":[] if li==1 else [f"{uc}.{li-1}"],"enables_lessons":[] if li==len(lt) else [f"{uc}.{li+1}"],"final_check_question":f"اشرح {t} بكلماتك. خطوات تطبيقه؟ أشهر خطأ؟","session_complete_criterion":f"يشرح {t} ويكتب كوداً يطبقه","yemeni_examples":[f"تطبيق عملي: {t} في مشروع حقيقي."],"expected_duration_minutes":30,"estimated_gem_cost":90,"solution_outline":f"خطوات {t}:\n1. فهم الأساس\n2. استيراد المكتبات\n3. تطبيق الكود\n4. تحليل النتائج\n5. توثيق","motivation_hook":f"{t} - مهارة أساسية في علوم البيانات.","learning_objectives":[{"statement":f"يفهم {t}","bloom_level":"understand"},{"statement":f"يطبق {t}","bloom_level":"apply"}],"glossary":[],"concepts":[{"name":t,"explanation":f"شرح وتطبيق عملي لـ {t} في سياق {sn}.","mastery_criterion":f"يشرح {t} ويكتب كوداً","weight":1}],"common_mistakes":lm});pv=t
 return ls

def glab(uc,un,nl):
 return[{"lab_index":li,"title":f"معمل {un}: {'التشخيص' if li==1 else 'التطبيق'}","scenario":f"مشكلة في {un}. حللها وقدم حلاً عملياً.","completion_criterion":f"تحليل وحل لمشكلة في {un}","pedagogical_sequence":"diagnostic -> decision -> application -> analysis -> connection","prerequisite_lessons":[f"{uc}.{nl//2}"],"allowed_tools":["text","code"],"questions":[{"kind":"diagnostic","prompt":f"خطوات تشخيص مشكلة في {un}؟","rubric":"يجب ذكر 4 خطوات منطقية مع شرح موجز","solution_outline":"جمع المعلومات وتحليل الأعراض وتحديد السبب واقتراح الحل","points":1},{"kind":"decision","prompt":f"خياران لحل في {un}. معايير اختيارك؟","rubric":"يجب ذكر معيارين مع تبرير منطقي وواضح","solution_outline":"الدقة والسرعة والتعقيد وسهولة الصيانة","points":1},{"kind":"application","prompt":f"اكتب كوداً يطبق {un} على بيانات حقيقية.","rubric":"كود صحيح يعمل وينتج نتائج دقيقة","solution_outline":"استيراد المكتبات وتحميل البيانات وتطبيق المنهجية","points":2},{"kind":"analysis","prompt":f"كود لـ {un} فيه 3 أخطاء. اكتشفها وصححها.","rubric":"يكتشف 3 أخطاء مع شرح وتصحيح لكل منها","solution_outline":"تحليل الأخطاء الثلاثة وتصحيح كل منها مع شرح","points":1},{"kind":"connection","prompt":f"اربط {un} بمهارات سابقة. اقترح مشروعاً.","rubric":"يذكر رابطين مع فكرة مشروع متكامل","solution_outline":"الربط بالمهارات السابقة وخطة مشروع متكامل","points":1}]} for li in range(1,3)]

def ge(c,s,n=10):
 q=[("الخطوة الأولى في ML:",["فهم المشكلة","أحدث خوارزمية","جمع بيانات","كتابة كود"],0,1,"بدون هدف، أفضل خوارزمية لا تعطي نتيجة."),("Supervised vs Unsupervised:",["المراقب يحتاج تسميات","لا فرق","المراقب أسرع","غير المراقب أدق"],0,1,"Supervised بتسميات، Unsupervised بدونها."),("Overfitting:",["النموذج يحفظ ولا يعمم","بسيط جداً","سريع","قليل بيانات"],0,2,"أداء تدريب ممتاز، فشل على بيانات جديدة."),("Cross-Validation:",["تقييم موثوق","تسريع","زيادة بيانات","تغيير خوارزمية"],0,2,"يقسم لـ k أجزاء ويتأكد من ثبات الأداء."),("ReLU:",["ReLU","Sigmoid","Softmax","Linear"],0,2,"تحل Vanishing Gradient."),("Dropout:",["منع Overfitting","تسريع","تكبير","تغيير تنشيط"],0,2,"يعطل عشوائياً عصبونات."),("df.describe():",["إحصائيات وصفية","حذف فارغات","رسم","تغيير أسماء"],0,1,"تعرض count,mean,std,min,25%,50%,75%,max."),("Data Leakage:",["تسرب الاختبار للتدريب","فقدان بيانات","تسرب ذاكرة","توقف تدريب"],0,2,"أخطر خطأ: معلومات الاختبار تتسرب."),("Scaler:",["توحيد مقياس المتغيرات","زيادة بيانات","تسريع","تغيير نوع"],0,1,"يوحد لـ mean=0, std=1."),("train_test_split:",["تقسيم لتدريب واختبار","تسريع","زيادة","تغيير نوع"],0,2,"يضمن تقييماً غير متحيز.")]
 vv=[]
 for v in range(3):vv.append([{"question_index":qi+1,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {ch}" for ci,ch in enumerate(c)],"correct_index":ci,"explanation":e,"difficulty":d,"points":1,"time_limit_seconds":60+d*30} for qi,(p,c,ci,d,e) in enumerate([q[(h(f"{s}_{v}_{qi}"))%len(q)] for qi in range(n)])])
 return{"code":s,"scope":c,"variants":vv}

def gp():
 q=[(1,"print(type(3.14)):",["<class 'float'>","<class 'int'>","<class 'str'>","<class 'bool'>"],0,1),(1,"قائمة مربعات زوجية:",["[x**2 for x in range(10) if x%2==0]","list(range(even))","[x for x in range(10) if x/2==0]","[x for x in even(10)]"],0,1),(2,"df.describe():",["إحصائيات وصفية","حذف فارغات","رسم","تغيير أسماء"],0,1),(2,"np.mean():",["المتوسط الحسابي","np.average()","np.median()","np.sum()/len()"],0,1),(3,"تصنيف ثنائي:",["Logistic Regression","Linear Regression","K-Means","PCA"],0,2),(3,"train_test_split:",["تقسيم لتدريب واختبار","تسريع","زيادة","تغيير نوع"],0,2),(4,"Gradient Boosting:",["نماذج متسلسلة تصحح","شبكات عصبية","K-Means","مكتبة رسم"],0,2),(4,"وظيفة PCA في تعلم الآلة:",["تقليل أبعاد","زيادة دقة","تنظيف بيانات","تسريع فقط"],0,2),(5,"MLOps:",["تشغيل نماذج ML","خوارزميات","لغة","قاعدة بيانات"],0,3),(5,"Docker:",["تغليف ونشر","تدريب","تحليل","رسم"],0,3)]
 return[{"target_level_index":l,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {c}" for ci,c in enumerate(c)],"correct_index":ci,"difficulty":d,"explanation":f"مستوى {l}"} for l,p,c,ci,d in q]

def main():
 print(f"\n{'='*60}\n  uni-data-science - تسلسل منطقي\n{'='*60}\n")
 mt={"slug":"uni-data-science","name":"علوم البيانات","icon":"📊","desc":"منهج متكامل: من Python إلى التعلم العميق. تسلسل منطقي حقيقي.","scope":"professional_track","language":"ar","region":"YE","target_persona":"طالب يريد احتراف علوم البيانات.","teacher_tone":"عملية ومباشرة.","viz":["python_trace","flowchart","scatter_plot","line_chart","bar_chart","heatmap","data_table"],"tools":["text","code","image"],"glossary":[{"term":"DataFrame","definition":"هيكل بيانات ثنائي الأبعاد"}]}
 rl=[];au=[];asc=[]
 for li,(ln,lg,lb,ss) in enumerate(C):
  lv=li+1;rs=[]
  for si,(sn,sg,us) in enumerate(ss):
   sv=si+1;sc=f"{lv}.{sv}";asc.append(sc);ru=[]
   for ui,(un,lt) in enumerate(us):
    lt=[t for t in lt if t and len(t)>=3];uv=ui+1;uc=f"{sc}.{uv}";au.append(uc)
    ls=gl(uc,lt,sn);la=glab(uc,un,len(ls))
    pr=[f"{sc}.{ui}"] if ui>0 else[];en=[f"{sc}.{ui+2}"] if ui<len(us)-1 else[]
    g=f"إتقان {un}";g=g if len(g)>=10 else f"إتقان {un} بشكل متقن واحترافي"
    ru.append({"unit_index":uv,"name":un,"goal":g,"prerequisite_units":pr,"enables_units":en,"key_concepts":[lt[0][:20]],"motivation_hook":f"وحدة {un} - خطوتك نحو الاحتراف.","learning_objectives":[{"statement":f"يتقن {un}","bloom_level":"apply"}],"lessons":ls,"labs":la,"exam":{"pass_threshold_percent":60,"points":10,"time_limit_minutes":30}})
    print(f"  {uc}: {un[:50]} ({len(lt)} دروس)")
   rs.append({"stage_index":sv,"name":sn,"goal":sg,"bloom_focus":lb,"units":ru,"exam":{"pass_threshold_percent":60,"points":20,"time_limit_minutes":45}})
  rl.append({"level_index":lv,"name":ln,"goal":lg,"bloom_focus":lb,"stages":rs,"exam":{"pass_threshold_percent":60,"points":50,"time_limit_minutes":90}})
 print("\n  بنوك الامتحانات...")
 ub={c:ge(c,"unit",10) for c in au}
 sb={c:ge(c,"stage",15) for c in asc}
 lb={str(i):ge(str(i),"level",20) for i in range(1,len(rl)+1)}
 fn={"schema_version":"v4.1","specialty":{**mt,"yemeni_examples":["تطبيق عملي"]},"levels":rl,"exam_banks":{"unit_banks":ub,"stage_banks":sb,"level_banks":lb},"placement_test_questions":gp(),"publish_notes":"uni-data-science - تسلسل منطقي"}
 fp=OUT/"final.json"
 with open(fp,'w',encoding='utf-8') as f:json.dump(fn,f,ensure_ascii=False,indent=2)
 sz=fp.stat().st_size/(1024*1024);tl=sum(1 for l in rl for s in l['stages'] for u in s['units'] for _ in u['lessons'])
 print(f"\n  ✅ {sz:.1f} MB | {len(rl)} مستويات | {tl} درس\n")
if __name__=="__main__":main()
