#!/usr/bin/env python3
"""uni-ai v4 — تسلسل منطقي — كل وحدة لها دروسها الخاصة"""
import json; from pathlib import Path; import random
random.seed(42)
def h(s): return sum(ord(c)*(i+1) for i,c in enumerate(str(s)))
OUT = Path("out/uni-ai"); OUT.mkdir(parents=True, exist_ok=True)

def U(name, *lessons): return (name, list(lessons))
def S(name, goal, *units): return (name, goal, list(units))
def L(name, goal, bloom, *stages): return (name, goal, bloom, list(stages))

CURRICULUM = [
    L("المستوى الأول: Python والتفكير البرمجي","إتقان Python، هياكل البيانات، الخوارزميات، NumPy، Pandas","apply",
        S("أساسيات Python: من الصفر لأول برنامج","كتابة كود Python بطلاقة",
            U("تشغيل أول برنامج: print و comments والمفسر","تثبيت Python وتشغيل أول أمر","دالة print(): عرض النتائج","التعليقات: توثيق الكود","المتغيرات: تخزين القيم في الذاكرة","أنواع البيانات: int, float, str, bool","العمليات الحسابية الأساسية","دالة input(): قراءة مدخلات المستخدم","الأخطاء البسيطة وقراءة Traceback","هيكل برنامج Python كامل","مشروع: آلة حاسبة بسيطة"),
            U("المتغيرات والأنواع: int, float, str, bool","المتغيرات: تسمية وتخزين","النوع int: الأعداد الصحيحة","النوع float: الكسور العشرية","النوع str: النصوص والسلاسل","النوع bool: القيم المنطقية","التحويل بين الأنواع","دالة type(): اكتشف نوع أي قيمة","نطاق المتغيرات Scope","أفضل ممارسات التسمية","مشروع: مدقق أنواع البيانات"),
            U("العمليات الحسابية والمنطقية","الجمع والطرح والضرب","القسمة: / مقابل // مقابل %","الأس ** وأولوية العمليات","عوامل المقارنة: ==, !=, <, >","العوامل المنطقية: and, or, not","أولوية العمليات الكاملة","التعبيرات المركبة","قيم Truthy و Falsy","العمليات على النصوص: + و *","مشروع: حاسبة علمية"),
            U("الشروط واتخاذ القرار: if, elif, else","if: الشرط الأول","else: المسار البديل","elif: تعدد المسارات","الشروط المتداخلة Nested if","if مع in: فحص الانتماء","match/case: البديل الحديث","التعبير الشرطي المختصر","التحقق من صحة المدخلات","أخطاء شائعة في الشروط","مشروع: لعبة تخمين الرقم"),
            U("الحلقات: for, while, break, continue","for مع range(): التكرار المنظم","for مع القوائم والمجموعات","while: التكرار بشرط","break: الخروج الفوري من الحلقة","continue: تخطي الدورة الحالية","الحلقات المتداخلة","enumerate(): الفهرس مع القيمة","الحلقة اللانهائية وخطورتها","متى for ومتى while؟","مشروع: جدول الضرب"),
            U("القوائم List: الإضافة، الحذف، الفهرسة","إنشاء القوائم بطرق مختلفة","الفهرسة: الوصول بالموقع","التقطيع Slicing","الإضافة: append(), insert()","الحذف: remove(), pop()","الترتيب: sort(), reverse()","len(), min(), max(), sum()","القوائم المتداخلة Nested Lists","نسخ القوائم: = مقابل copy()","مشروع: إدارة قائمة مهام"),
            U("القواميس Dict: المفاتيح والقيم","إنشاء القواميس","الوصول: d['key']","get(): الوصول الآمن","إضافة وتعديل العناصر","حذف العناصر: del, pop()","keys(), values(), items()","تحديث ودمج القواميس","Dict Comprehensions","متى Dict ومتى List؟","مشروع: دفتر هاتف"),
            U("الدوال Functions: التعريف والاستدعاء","def: تعريف الدالة","المعاملات Parameters","return: إرجاع القيم","وسائط افتراضية","وسائط مفتاحية **kwargs","lambda: الدوال السريعة","توثيق الدوال docstring","نطاق المتغيرات في الدوال","إعادة الاستخدام ومبدأ DRY","مشروع: مكتبة دوال رياضية"),
            U("مشروع: آلة حاسبة علمية","تخطيط المشروع","بناء القائمة الرئيسية","تنفيذ العمليات الأساسية","إضافة الدوال العلمية","معالجة الأخطاء","حفظ العمليات السابقة","تحسين واجهة المستخدم","اختبار شامل","توثيق الكود","العرض النهائي"),
        ),
        S("هياكل البيانات: تنظيم المعلومات","List, Tuple, Set, Dict",
            U("List Comprehensions","الصيغة الأساسية: [expr for x in list]","إضافة شرط التصفية","Nested Comprehensions","List Comp مع دوال","مقارنة السرعة مع for","Dict Comprehensions","Set Comprehensions","Generator Expressions","متى تستخدم comprehension؟","مشروع: تحويل البيانات"),
            U("التقطيع Slicing","الصيغة [start:stop]","[start:stop:step] مع الخطوة","تقطيع القوائم","تقطيع النصوص","القيم السالبة","نسخ بالتقطيع: lst[:]","التقطيع مع NumPy","تعديل شرائح","تطبيقات عملية","مشروع: استخراج الأنماط"),
            U("Tuple: البيانات الثابتة","ما هو Tuple؟","مقارنة مع List","تفريغ Unpacking","Tuple كـ مفتاح في Dict","دوال Tuple","namedtuple","Tuple كقيمة راجعة","متى تستخدم Tuple؟","التحويل بين Tuple و List","مشروع: نظام إحداثيات"),
            U("Set: المجموعات وإزالة التكرار","إنشاء Set","إزالة التكرار تلقائياً","add(), remove(), discard()","الاتحاد union: |","التقاطع intersection: &","الفرق difference: -","الفرق المتماثل: ^","فحص المجموعات الفرعية","لماذا Set أسرع من List؟","مشروع: إزالة التكرارات"),
            U("Dict Comprehensions","الصيغة الأساسية","شرط في Dict Comp","تحويل قائمتين لقاموس","تصفية القواميس","حساب تكرارات العناصر","دمج القواميس","Dict Comp مع zip()","تطبيقات عملية","أداء Dict Comp","مشروع: تحليل ترددات الكلمات"),
            U("فرز وتصفية البيانات: sorted و filter","sorted(): الترتيب الأساسي","المعامل key","reverse=True","filter(): تصفية العناصر","lambda مع sorted و filter","itemgetter و attrgetter","ترتيب مخصص متعدد المستويات","تصفية متعددة المراحل","أداء الفرز والتصفية","مشروع: ترتيب وتصنيف البيانات"),
            U("Lambda: الدوال السريعة","صيغة lambda","lambda مع map()","lambda مع filter()","lambda مع sorted()","lambda مع List Comprehensions","متى lambda ومتى def؟","قيود lambda","lambda متعددة المعاملات","استخدامات عملية","مشروع: معالجة نصوص"),
            U("قياس الأداء: Big O","Big O: لماذا يهم؟","List بحث: O(n)","Set بحث: O(1)","Dict بحث: O(1)","timeit: قياس الزمن","%timeit في Jupyter","مقارنة عملية","متى تضحي بالسرعة؟","أداء العمليات المختلفة","مشروع: تحسين أداء كود"),
            U("مشروع: نظام إدارة مكتبة","تخطيط هيكل البيانات","إضافة كتب جديدة","البحث عن كتاب","استعارة وإرجاع","قائمة المستعيرين","تقارير إحصائية","حفظ البيانات لملف","تحميل البيانات","اختبار شامل","العرض النهائي"),
        ),
        S("البرمجة الكائنية OOP","Classes, Inheritance, Polymorphism",
            U("Classes و Objects","ما هو الكلاس Class؟","إنشاء أول كلاس","إنشاء كائن Object","الخصائص Attributes","self: الإشارة للكائن","متى تحتاج OOP؟","الكلاسات المضمنة","OOP في Python","مشروع: كلاس الطالب"),
            U("Constructor __init__","__init__: الباني","تهيئة الخصائص","معاملات الباني","قيم افتراضية","التحقق من المدخلات","باني متعدد: @classmethod","باني النسخ","الباني والوراثة","مشروع: كلاس المنتج"),
            U("التغليف Encapsulation","public attributes","_protected بالعرف","__private: name mangling","getters: @property","setters: @x.setter","deleters","لماذا التغليف؟","مقارنة بلغات أخرى","مشروع: كلاس الحساب البنكي"),
            U("الوراثة Inheritance","class Child(Parent):","super().__init__()","تجاوز methods","إضافة خصائص جديدة","isinstance() و issubclass()","Multiple Inheritance","MRO: ترتيب البحث","Mixins","مشروع: التسلسل الهرمي"),
            U("تعدد الأشكال Polymorphism","نفس الواجهة، سلوك مختلف","Duck Typing","method overriding","operator overloading","__str__ و __repr__","len() و __len__","التجريد: abstractmethod","فوائد polymorphism","مشروع: نظام الدفع"),
            U("Property و Magic Methods","@property","@x.setter","@x.deleter","__str__: تمثيل مقروء","__repr__: تمثيل دقيق","__eq__: مقارنة","__lt__: ترتيب","__add__: جمع","مشروع: كلاس المتجه"),
            U("الكلاسات المجردة ABC","from abc import ABC, abstractmethod","لماذا ABC؟","تعريف abstractmethod","لا يمكن إنشاء ABC مباشرة","الوراثة من ABC","تطبيق متعدد","ABCMeta","مقارنة مع Interfaces","مشروع: هيكل الألعاب"),
            U("Composition مقابل Inheritance","Composition: has-a","Inheritance: is-a","مقارنة المرونة","متى Composition؟","متى Inheritance؟","تطبيق Composition","دمج الاثنين","تفضيل Composition","مشروع: نظام المركبة"),
            U("مشروع: محاكاة نظام بنكي","تخطيط الكلاسات","كلاس الحساب","كلاس العميل","كلاس المعاملة","نظام الفوائد","التقارير","معالجة الأخطاء","اختبار النظام","العرض النهائي"),
        ),
        S("الخوارزميات: التفكير المنظم","تحليل المشكلات، Big O",
            U("ما هي الخوارزمية؟","تعريف الخوارزمية","خصائص الخوارزمية الجيدة","أمثلة من الحياة اليومية","الخوارزمية في البرمجة","لماذا نتعلم الخوارزميات؟","Pseudocode","Flowcharts","تحليل المدخلات والمخرجات","مشروع: صف خوارزمية"),
            U("تحليل التعقيد Big O","O(1): ثابت","O(log n): لوغاريتمي","O(n): خطي","O(n log n): خطي لوغاريتمي","O(n²): تربيعي","كيف تحسب Big O؟","أفضل وأسوأ حالة","مقارنة التعقيدات","مشروع: تحليل دوال"),
            U("البحث الخطي والثنائي","Linear Search: O(n)","Binary Search: O(log n)","شرط Binary Search: بيانات مرتبة","متى تستخدم أياً منهما؟","bisect في Python","مقارنة الأداء العملي","Binary Search على مليون عنصر","تطبيقات البحث","مشروع: مقارنة السرعة"),
            U("خوارزميات الترتيب البسيطة","Bubble Sort: O(n²)","Selection Sort: O(n²)","Insertion Sort: O(n²)","لماذا نتعلمها؟","مقارنة الثلاثة","أداء Insertion على بيانات شبه مرتبة","استقرارية الترتيب","مشروع: ترتيب قائمة",""),
            U("خوارزميات الترتيب المتقدمة","Merge Sort: divide/conquer","Quick Sort: pivot","تعقيد O(n log n)","مقارنة مع O(n²)","استقرارية Merge Sort","أسوأ حالة Quick Sort","متى تختار أياً منهما؟","مشروع: مقارنة الأداء",""),
            U("التكرار الذاتي Recursion","Base Case و Recursive Case","أمثلة: factorial, fibonacci","Stack Overflow","Recursion Tree","Tail Recursion","Recursion vs Iteration","متى تستخدم recursion؟","مشروع: رسم شجرة",""),
            U("البرمجة الديناميكية DP","Memoization: Top-down","Tabulation: Bottom-up","Fibonacci بـ DP","Longest Common Subsequence","Knapsack Problem","Edit Distance","متى DP؟","مشروع: أطول سلسلة",""),
            U("Greedy و Backtracking","Greedy: الأفضل محلياً","Backtracking: جرب وتراجع","N-Queens Problem","Sudoku Solver","Graph Coloring","الفرق بينهما","تطبيقات","مشروع: حل متاهة",""),
            U("مشروع: حل متاهة بـ BFS","تمثيل المتاهة","BFS: بحث العرض أولاً","تتبع المسار","أقصر طريق","اختبار وتحسين","تطبيقات BFS","مقارنة مع DFS","توثيق","عرض"),
        ),
        S("NumPy: الحوسبة العددية","Arrays، العمليات المتجهة",
            U("لماذا NumPy؟","مقارنة السرعة مع قوائم Python","تخزين متجاور","عمليات بـ C","متى NumPy؟","متى قوائم Python؟","تثبيت NumPy","استيراد NumPy","مشروع: قياس الأداء"),
            U("إنشاء المصفوفات","np.array()","np.zeros(), np.ones()","np.arange(), np.linspace()","np.eye()","np.random.rand()","shape و dtype","ndim","مشروع: مصفوفات متنوعة"),
            U("الفهرسة والتقطيع","الفهرسة من 0","التقطيع [start:stop]","التقطيع مع step","Boolean Masking","Fancy Indexing","التقطيع في 2D","التقطيع في 3D","مشروع: استخراج البيانات"),
            U("العمليات المتجهة","عمليات عنصر بعنصر","broadcasting","دوال ufunc","لماذا هي أسرع؟","حلقات vs متجهات","تطبيقات","مشروع: تحويل حلقات"),
            U("الدوال الإحصائية","mean, median, std","sum, min, max","axis=0, axis=1","percentile, quantile","corrcoef","تطبيقات","مشروع: تقرير إحصائي"),
            U("Boolean Masking","arr[arr > threshold]","شروط مركبة: & و |","np.where()","np.select()","تطبيقات","مشروع: تصفية بيانات"),
            U("إعادة التشكيل","reshape()","-1: حساب تلقائي","flatten(), ravel()","transpose (.T)","np.newaxis","تطبيقات","مشروع: معالجة الصور"),
            U("الدمج والتقسيم","concatenate","vstack, hstack","split, array_split","متى تدمج؟","تطبيقات","مشروع: دمج مجموعات"),
            U("مشروع: تحليل إحصائي","تخطيط التحليل","حسابات إحصائية","تصفية وتنظيف","استخلاص النتائج","توثيق وعرض"),
        ),
        S("Pandas: تحليل البيانات","DataFrame، تنظيف، GroupBy",
            U("DataFrame و Series","ما هو DataFrame؟","ما هو Series؟","df.head(), df.info()","df.describe()","df.shape, df.columns","مشروع: أول DataFrame"),
            U("قراءة وكتابة البيانات","pd.read_csv()","pd.read_excel()","pd.read_json()","df.to_csv()","encoding","مشروع: استيراد بيانات"),
            U("الفهرسة: loc و iloc","loc: بالاسم","iloc: بالرقم","at و iat","تحديد صفوف وأعمدة","مشروع: استعلامات"),
            U("تصفية البيانات","df[df['col'] > val]","شروط مركبة: &","query()","str.contains()","مشروع: تصفية متقدمة"),
            U("إضافة وتعديل الأعمدة","df['new'] = ...","df['col'] *= 2","rename()","drop()","مشروع: تنظيف أعمدة"),
            U("القيم المفقودة","isna().sum()","dropna()","fillna()","interpolate()","مشروع: إكمال البيانات"),
            U("GroupBy: التجميع","groupby().mean()","agg(): دوال متعددة","transform()","filter()","مشروع: تقارير مجمعة"),
            U("دمج البيانات","merge()","concat()","join()","مقارنة how","مشروع: دمج جداول"),
            U("مشروع: تحليل بيانات مبيعات","استيراد وتنظيف","تحليل إحصائي","تجميع وتقارير","رسوم بيانية","عرض النتائج"),
        ),
        S("مشروع المستوى: نظام تحليل بيانات","تطبيق كل مهارات Python, NumPy, Pandas",
            U("تحديد المشكلة والأسئلة","ماذا نحلل؟","الأسئلة البحثية","جمع البيانات","خطة المشروع"),
            U("تنظيف وتحضير البيانات","استيراد البيانات","معالجة المفقود","إزالة التكرار","تنسيق الأعمدة"),
            U("التحليل الاستكشافي EDA","إحصائيات وصفية","توزيعات","العلاقات بين المتغيرات","اكتشاف الأنماط"),
            U("الحسابات الإحصائية","المتوسط والوسيط","الانحراف المعياري","الارتباطات","اختبار الفرضيات"),
            U("التصوير البياني","رسوم توزيعية","رسوم علائقية","رسوم تجميعية","تنسيق احترافي"),
            U("استخلاص النتائج","ماذا تخبرنا البيانات؟","الأنماط المكتشفة","العلاقات المؤكدة","المفاجآت"),
            U("كتابة التقرير النهائي","الملخص التنفيذي","المنهجية","النتائج","التوصيات"),
            U("العرض النهائي","تصميم العرض","سرد القصة","رسوم توضيحية","تقديم أمام لجنة"),
        ),
    ),

    L("المستوى الثاني: الرياضيات والإحصاء","الجبر الخطي، التفاضل، الاحتمالات، التصوير","understand",
        S("الجبر الخطي: لغة تعلم الآلة","متجهات، مصفوفات، عمليات خطية",
            U("المتجهات","ما هو المتجه؟","جمع وطرح المتجهات","الضرب القياسي Dot Product","طول المتجه","الزاوية بين متجهين","الاستقلال الخطي","المتجهات في NumPy","مشروع: عمليات المتجهات"),
            U("المصفوفات","ما هي المصفوفة؟","الجمع والطرح","ضرب المصفوفات @","المعكوس: np.linalg.inv()","المحدد Determinant","المصفوفة المنقولة .T","المصفوفات في NumPy","مشروع: عمليات المصفوفات"),
            U("ضرب المصفوفات في الشبكات العصبية","لماذا الضرب مهم؟","طبقة كثيفة = X @ W + b","الأبعاد","Forward Pass حسابي","تأثير الأوزان","الانحياز bias","مثال: شبكة من طبقتين","تصور العمليات","مشروع: Forward Pass يدوي"),
            U("المحددات والمعكوس","المحدد det(A)","معنى det=0: شاذة","المعكوس A⁻¹","حل Ax=b بـ inv","التكلفة O(n³)","بدائل inv","التطبيقات في ML","مشروع: حل معادلات"),
            U("القيم الذاتية والمتجهات الذاتية","Av = λv","np.linalg.eig()","المعنى الهندسي","أساس PCA","القيم الذاتية = أهمية","المتجهات الذاتية = اتجاهات","التطبيقات","مشروع: PCA يدوي"),
            U("SVD: تحليل القيمة المنفردة","A = U Σ V^T","np.linalg.svd()","أساس PCA","أساس التوصيات","ضغط الصور","اختيار k","التطبيقات العملية","مشروع: ضغط صورة"),
            U("معايير المصفوفات Norms","L2 norm (Frobenius)","L1 norm","np.linalg.norm()","استخدامات norms","Regularization","مقارنة المعايير","تطبيقات","مشروع: حساب norms"),
            U("حل أنظمة المعادلات الخطية","Ax = b","np.linalg.solve()","np.linalg.lstsq()","التطبيق في الانحدار","الحل المباشر vs التقريبي","مقارنة التكلفة","التطبيقات","مشروع: انحدار خطي يدوي"),
            U("مشروع: PCA من الصفر","تجميع البيانات","توسيط البيانات","حساب SVD","اختيار المكونات","تحويل البيانات","تصور النتائج","تفسير النتائج","توثيق","عرض"),
        ),
        S("التفاضل والتكامل","المشتقات، التدرج، Gradient Descent",
            U("المشتقة","ما هي المشتقة؟","ميل المماس","حساب المشتقة","قواعد الاشتقاق","المشتقات العليا","المشتقة في Python","التطبيقات","مشروع: حساب المشتقة عددياً"),
            U("Chain Rule","مشتقة f(g(x))","أمثلة بسيطة","لماذا Chain Rule مهم؟","تطبيق في الشبكات","التدرج عبر الطبقات","تصور Chain Rule","التطبيقات","مشروع: تتبع chain rule"),
            U("المشتقات الجزئية","∂f/∂x","∂f/∂y","التدوين","حساب المشتقات","التطبيقات","مشروع: مشتقات دالة ثنائية"),
            U("التدرج Gradient","∇f = [∂f/∂x, ∂f/∂y]","معنى التدرج","اتجاه التدرج","عكس التدرج","حجم التدرج","التطبيقات في ML","مشروع: رسم التدرج"),
            U("Gradient Descent","w = w - lr × ∇loss","تهيئة عشوائية","حجم الخطوة = lr","معايير التوقف","Batch vs Mini-Batch","التطبيقات","مشروع: GD"),
            U("مقارنة Optimizers","SGD","Momentum","RMSprop","Adam","مقارنة المسارات","متى تختار أياً منها؟","مشروع: مقارنة"),
            U("دوال التكلفة","MSE للانحدار","Binary Cross-Entropy","Categorical Cross-Entropy","لماذا هذه الدوال؟","المشتقات","مشروع: رسم دوال"),
            U("معدل التعلم","lr كبير: تذبذب","lr صغير: بطء","lr الأمثل","Learning Rate Schedules","ReduceLROnPlateau","مشروع: تجربة lr"),
            U("مشروع: تدريب انحدار خطي","توليد بيانات","دالة التكلفة","Gradient Descent","مراقبة التقارب","تقييم","تصور","توثيق","عرض"),
        ),
        S("الاحتمالات والإحصاء","التوزيعات، الاختبارات، الارتباط",
            U("الاحتمالات الأساسية","P(A) = حالات مواتية ÷ كلية","0 ≤ P ≤ 1","الأحداث المتنافية","الأحداث المستقلة","قواعد الاحتمال","التطبيقات","مشروع: حسابات"),
            U("نظرية Bayes","P(A|B)","Bayes: P(A|B) = P(B|A)P(A)/P(B)","أمثلة طبية","Naive Bayes","P(A|B) ≠ P(B|A)","مشروع: مصنف Bayes"),
            U("التوزيع الطبيعي","منحنى الجرس","μ, σ","68-95-99.7","Standard Normal","التطبيقات","مشروع: توليد توزيع"),
            U("التوزيعات الأخرى","Binomial","Poisson","Uniform","Exponential","scipy.stats","مشروع: مقارنة"),
            U("اختبار الفرضيات","H0, H1","p-value","α = 0.05","Type I/II Error","التطبيقات","مشروع: اختبار t"),
            U("فترات الثقة","X̄ ± z*(σ/√n)","مستوى الثقة 95%","تأثير حجم العينة","Bootstrap CI","مشروع: حساب CI"),
            U("الارتباط","Pearson r","Spearman","Correlation ≠ Causation","df.corr()","مشروع: مصفوفة ارتباط"),
            U("تحليل المتبقيات","Residual = y - ŷ","أنماط المتبقيات","Heteroscedasticity","QQ Plot","مشروع: تحليل"),
            U("مشروع: تحليل إحصائي","فرضية","جمع بيانات","إحصائيات","اختبارات","استنتاجات","توثيق","عرض"),
        ),
        S("تصوير البيانات","Matplotlib, Seaborn",
            U("Matplotlib الأساسي","أول رسم","plt.plot()","plt.scatter()","plt.bar()","عناوين ومحاور","مشروع: رسم"),
            U("تخصيص الرسوم","figsize","ألوان وأنماط","markers","grid, legend","مشروع: تنسيق"),
            U("Subplots","plt.subplots()","شبكة رسوم","tight_layout()","مشروع: Dashboard"),
            U("Histograms و Boxplots","plt.hist()","bins","plt.boxplot()","outliers","مشروع: توزيعات"),
            U("Seaborn","sns.histplot()","sns.boxplot()","sns.barplot()","sns.scatterplot()","مشروع: رسوم"),
            U("Heatmaps و Pairplots","sns.heatmap()","correlation matrix","sns.pairplot()","مشروع: علاقات"),
            U("حفظ وتصدير","savefig()","dpi","png, pdf, svg","bbox_inches","مشروع: تصدير"),
            U("سرد القصص بالبيانات","كل رسم يجيب سؤال","تسلسل الرسوم","الألوان بذكاء","إزالة الفوضى","مشروع: قصة"),
            U("مشروع: Dashboard","تخطيط","6 رسوم","تنسيق","استخلاص","عرض"),
        ),
        S("تنظيف وتحضير البيانات","80% من وقت عالم البيانات",
            U("القيم المفقودة","MCAR, MAR, MNAR","dropna()","fillna()","interpolate()","مشروع: معالجة"),
            U("القيم الشاذة","IQR method","Z-score","Isolation Forest","Boxplot","مشروع: كشف"),
            U("توحيد المقياس","StandardScaler","MinMaxScaler","RobustScaler","متى تحتاج؟","مشروع: مقارنة"),
            U("ترميز المتغيرات","OneHotEncoder","LabelEncoder","OrdinalEncoder","Target Encoding","مشروع: ترميز"),
            U("تحويل المتغيرات","log transform","Box-Cox","Yeo-Johnson","PowerTransformer","مشروع: تحويلات"),
            U("Binning","pd.cut()","KBinsDiscretizer","لماذا binning؟","مشروع: تجميع"),
            U("Train/Test Split","train_test_split()","test_size, stratify","random_state","التقسيم الثلاثي","مشروع: تقسيم"),
            U("Data Leakage","Scaler قبل التقسيم","ميزات من المستقبل","Pipeline يمنعه","مشروع: كشف"),
            U("مشروع: Pipeline معالجة","تخطيط","تنظيف","تحويل","تقسيم","حفظ","توثيق"),
        ),
        S("هندسة الميزات","إنشاء واختيار أفضل الميزات",
            U("إنشاء الميزات","الجمع والنسب","التفاعلات","Domain Knowledge","من التاريخ","مشروع: ميزات"),
            U("Filter Methods","Variance Threshold","Correlation","Mutual Information","Chi-squared","مشروع: Filter"),
            U("Wrapper Methods","RFE","Forward Selection","Backward Elimination","مشروع: RFE"),
            U("Embedded Methods","Lasso: L1","Tree Importance","Permutation Importance","مشروع: Embedded"),
            U("PCA","explained_variance_ratio_","n_components","scaling","المكونات","مشروع: PCA"),
            U("t-SNE و UMAP","للتصور فقط","perplexity","n_neighbors","مشروع: تصور"),
            U("Polynomial Features","degree","تفاعلات","خطر overfitting","مشروع: Polynomial"),
            U("Featuretools","dfs()","entityset","توليد تلقائي","مشروع: أتمتة"),
            U("مشروع: Kaggle","فهم البيانات","هندسة ميزات","بناء نموذج","تحسين","تقديم"),
        ),
        S("مشروع المستوى: من البيانات لنموذج","دورة حياة مشروع علم البيانات",
            U("فهم المشكلة","تحديد الهدف","أسئلة","مقاييس","خطة"),
            U("جمع واستكشاف","مصادر","استيراد","EDA أولي","جودة"),
            U("تنظيف ومعالجة","مفقود","شواذ","متغيرات","توحيد"),
            U("التحليل الاستكشافي","توزيعات","علاقات","أنماط","فرضيات"),
            U("هندسة الميزات","إنشاء","اختيار","تحويلات","تقييم"),
            U("بناء Baseline","نموذج بسيط","تقييم أولي","تحليل أخطاء","خط أساس"),
            U("تحسين النموذج","تجربة نماذج","ضبط","مقارنة","اختيار الأفضل"),
            U("تقييم نهائي","اختبار test set","تقرير","تحليل أخطاء","حدود"),
            U("عرض النتائج","ملخص تنفيذي","منهجية","نتائج","توصيات"),
        ),
    ),
    L("المستوى الثالث: التعلم الآلي","بناء نماذج تنبؤية حقيقية","apply",
        S("أساسيات التعلم الآلي","Scikit-learn, التقييم, CV",
            U("ما هو تعلم الآلة؟","Supervised, Unsupervised","Reinforcement","سير العمل","التطبيقات","مشروع: استكشف"),
            U("Scikit-learn API","Estimator, fit, predict","Transformer, fit_transform","توحيد الواجهة","مشروع: أول fit/predict"),
            U("مقاييس التقييم","MSE, MAE, R² للانحدار","Accuracy, Precision, Recall, F1 للتصنيف","ROC-AUC","classification_report","مشروع: تقييم"),
            U("Bias-Variance Tradeoff","Bias: Underfitting","Variance: Overfitting","التوازن","Learning Curve","مشروع: تشخيص"),
            U("Cross-Validation","K-Fold","StratifiedKFold","cross_val_score","النتائج: mean ± std","مشروع: CV"),
            U("Grid Search","GridSearchCV","param_grid","best_params_","RandomizedSearchCV","مشروع: GridSearch"),
            U("Pipelines","Pipeline()","ColumnTransformer","مع GridSearchCV","حفظ pipeline","مشروع: Pipeline"),
            U("حفظ وتحميل النماذج","pickle, joblib","احفظ preprocessing","إصدارات","مشروع: حفظ"),
            U("مشروع: أول نموذج ML","بيانات","نموذج","تقييم","تحسين","عرض"),
        ),
        S("الانحدار: التنبؤ بالقيم","Linear, Ridge, Lasso, Polynomial",
            U("Linear Regression","y = wx + b","model.fit()","model.coef_","R²","مشروع: انحدار"),
            U("تقييم الانحدار","MSE, RMSE, MAE","Residual Plot","R² و Adjusted R²","مشروع: تقييم"),
            U("Ridge Regression","L2 Regularization","alpha","لماذا Ridge؟","مشروع: Ridge"),
            U("Lasso Regression","L1 Regularization","Feature Selection","alpha","مشروع: Lasso"),
            U("Elastic Net","L1 + L2","l1_ratio","متى Elastic Net؟","مشروع: ElasticNet"),
            U("Polynomial Regression","PolynomialFeatures","درجة كثير الحدود","خطر overfitting","مشروع: منحنيات"),
            U("تحليل المتبقيات","Residuals","أنماط","Heteroscedasticity","مشروع: تحليل"),
            U("مقارنة الانحدار","Linear vs Ridge vs Lasso","Elastic Net vs Polynomial","أيها تختار؟","مشروع: مقارنة"),
            U("مشروع: توقع الأسعار","بيانات","هندسة","نماذج","تقييم","عرض"),
        ),
        S("التصنيف: تمييز الفئات","Logistic, Trees, KNN, Bayes",
            U("Logistic Regression","Sigmoid","Decision Boundary","predict_proba","مشروع: تصنيف"),
            U("تقييم التصنيف","Confusion Matrix","ROC, AUC","Precision-Recall","مشروع: تقييم"),
            U("Decision Trees","Gini, Entropy","max_depth","pruning","مشروع: شجرة"),
            U("Random Forest","n_estimators","Bagging","feature_importances_","مشروع: غابة"),
            U("K-Nearest Neighbors","المسافات","k","scaling ضروري","مشروع: KNN"),
            U("Naive Bayes","Bayes Theorem","GaussianNB","للنصوص","مشروع: Bayes"),
            U("مقارنة المصنفات","Logistic vs Tree vs KNN","متى تختار؟","مشروع: مقارنة"),
            U("عدم توازن الفئات","SMOTE","class_weight","F1 > Accuracy","مشروع: توازن"),
            U("مشروع: البريد العشوائي","نصوص","TF-IDF","مصنف","تقييم","عرض"),
        ),
        S("Ensemble Methods","Random Forest, XGBoost, Stacking",
            U("Bagging","Bootstrap","Random Forest","تجميع متواز","مشروع: Bagging"),
            U("Boosting","AdaBoost","Gradient Boosting","تجميع متسلسل","مشروع: Boosting"),
            U("XGBoost","n_estimators, lr","early_stopping","GPU","مشروع: XGBoost"),
            U("LightGBM","leaf-wise","أسرع","categorical","مشروع: LightGBM"),
            U("CatBoost","ordered boosting","للفئوية","مشروع: CatBoost"),
            U("Stacking","base models + meta","cross_val_predict","مشروع: Stacking"),
            U("ضبط المعاملات","GridSearch","RandomizedSearch","Optuna","مشروع: Tuning"),
            U("تفسير النماذج","Feature Importance","SHAP","LIME","مشروع: تفسير"),
            U("مشروع: مسابقة تصنيف","بيانات","Ensemble","تحسين","تقديم"),
        ),
        S("التعلم غير المراقب","K-Means, DBSCAN, Anomaly",
            U("K-Means","خوارزمية","n_clusters","Elbow Method","مشروع: K-Means"),
            U("اختيار k","Elbow","Silhouette Score","Gap Statistic","مشروع: اختيار"),
            U("DBSCAN","eps, min_samples","ضوضاء","أي شكل","مشروع: DBSCAN"),
            U("Hierarchical","Dendrogram","Agglomerative","linkage","مشروع: شجرة"),
            U("GMM","EM Algorithm","تجميع ناعم","مشروع: GMM"),
            U("تقييم التجميع","Silhouette","Davies-Bouldin","Calinski-Harabasz","مشروع: تقييم"),
            U("Anomaly Detection","Isolation Forest","One-Class SVM","LOF","مشروع: شواذ"),
            U("تطبيقات","Customer Segmentation","Image Compression","Document Clustering","مشروع: تطبيق"),
            U("مشروع: تقسيم العملاء","بيانات","تجميع","توصيف","عرض"),
        ),
        S("اختيار النموذج وضبط المعاملات","GridSearch, Pipelines, Optuna",
            U("GridSearchCV","param_grid","cv","best_params_","مشروع: GridSearch"),
            U("RandomizedSearchCV","param_distributions","n_iter","مشروع: Randomized"),
            U("Validation Curve","train vs validation","تشخيص","مشروع: منحنيات"),
            U("Learning Curve","train sizes","هل تحتاج بيانات أكثر؟","مشروع: تعلم"),
            U("Optuna","study.optimize","Bayesian","مشروع: Optuna"),
            U("ColumnTransformer","numeric vs categorical","remainder","مشروع: CT"),
            U("FeatureUnion","توازي","دمج","مشروع: FU"),
            U("اختيار النموذج النهائي","قارن validation","اختبر test مرة واحدة","مشروع: اختيار"),
            U("مشروع: Pipeline متكامل","Raw data","للتنبؤ","GridSearch","عرض"),
        ),
        S("مشروع المستوى: مسابقة Kaggle","حل مشكلة حقيقية",
            U("اختيار المشكلة","استكشاف","فهم البيانات","المقياس","خطة"),
            U("تحليل البيانات","EDA","تصوير","فرضيات","رؤى"),
            U("هندسة الميزات","إنشاء","اختيار","تحويل","تقييم"),
            U("بناء Baselines","نموذج بسيط","أول تقديم","تحليل","تحسين"),
            U("تجربة نماذج","Models","Ensemble","مقارنة","اختيار"),
            U("تحسين","Tuning","ميزات","Stacking","أفضل نتيجة"),
            U("تقديم نهائي","predictions","تقرير","منهجية","نتائج"),
            U("عرض","ملخص","ما نجح","ما فشل","دروس"),
        ),
    ),
    L("المستوى الرابع: التعلم العميق","TensorFlow/Keras, CNN, RNN, Transfer","apply",
        S("TensorFlow و Keras","Tensors, Sequential, Functional",
            U("تثبيت TensorFlow","pip install","tf.config","GPU","مشروع: تثبيت"),
            U("Tensors","scalar, vector, matrix","shape, dtype","tf.constant()","مشروع: Tensors"),
            U("Sequential API","model = Sequential()","Dense","input_shape","مشروع: أول شبكة"),
            U("Functional API","Input, Model","شبكات متفرعة","skip connections","مشروع: Functional"),
            U("Compile","optimizer, loss, metrics","adam","مشروع: Compile"),
            U("Fit","epochs, batch_size","validation_split","History","مشروع: تدريب"),
            U("Callbacks","EarlyStopping","ModelCheckpoint","ReduceLROnPlateau","مشروع: Callbacks"),
            U("حفظ وتحميل","model.save()","load_model","الأوزان","مشروع: حفظ"),
            U("مشروع: MNIST","بيانات","شبكة","تدريب","تقييم","عرض"),
        ),
        S("تدريب الشبكات العميقة","BatchNorm, Dropout, Transfer",
            U("Batch Normalization","BatchNormalization()","لماذا؟","قبل activation","مشروع: BatchNorm"),
            U("Dropout","Dropout(0.2)","في التدريب فقط","يمنع overfitting","مشروع: Dropout"),
            U("Regularization","kernel_regularizer=l2()","L1, L2","activity_regularizer","مشروع: Reg"),
            U("Learning Rate Schedules","ExponentialDecay","CosineDecay","ReduceLROnPlateau","مشروع: Schedules"),
            U("Data Augmentation","RandomFlip, RandomRotation","ImageDataGenerator","مشروع: Aug"),
            U("Transfer Learning","base_model.trainable=False","include_top=False","VGG16, ResNet","مشروع: Transfer"),
            U("Fine-Tuning","فك تجميد جزئي","lr منخفض","طبقات عليا","مشروع: FineTune"),
            U("TensorBoard","log_dir","مراقبة","رسم بياني","مشروع: TB"),
            U("مشروع: تصنيف صور","Transfer","FineTune","تقييم","عرض"),
        ),
        S("CNN: الشبكات الالتفافية","Convolution, Pooling, معماريات",
            U("Convolution","مرشحات","Conv2D","feature maps","مشروع: Conv"),
            U("Pooling","MaxPooling2D","AveragePooling2D","GlobalAverage","مشروع: Pool"),
            U("معماريات CNN","LeNet, AlexNet","VGG16","ResNet","مشروع: معماريات"),
            U("ResNet","Skip Connections","ResNet50","لماذا تعمل؟","مشروع: ResNet"),
            U("تصنيف الصور","ImageDataGenerator","class_mode","target_size","مشروع: تصنيف"),
            U("Object Detection","YOLO","SSD","Faster R-CNN","مشروع: Detection"),
            U("Image Segmentation","U-Net","Semantic","Instance","مشروع: Segment"),
            U("Data Augmentation للصور","RandomFlip","RandomRotation","RandomZoom","مشروع: Aug"),
            U("مشروع: مصنف صور","جمع بيانات","CNN","تدريب","نشر"),
        ),
        S("RNN/LSTM","RNN, LSTM, GRU, السلاسل",
            U("RNN Basics","hidden state","recurrence","Vanishing Gradient","مشروع: RNN"),
            U("LSTM","Forget, Input, Output Gates","cell state","return_sequences","مشروع: LSTM"),
            U("GRU","بوابتان","أسرع","مقارنة","مشروع: GRU"),
            U("Bidirectional","Bidirectional()","للأمام والخلف","مشروع: BiRNN"),
            U("Time Series","نوافذ زمنية","scale","تقسيم زمني","مشروع: تنبؤ"),
            U("Seq2Seq","Encoder-Decoder","Teacher Forcing","مشروع: Seq2Seq"),
            U("Attention","Attention()","يركز على المهم","Multi-Head","مشروع: Attn"),
            U("Embedding","Embedding(vocab, dim)","mask_zero","مشروع: Embed"),
            U("مشروع: تنبؤ حرارة","بيانات","LSTM","تدريب","تقييم","عرض"),
        ),
        S("النماذج التوليدية","Autoencoders, VAE, GAN",
            U("Autoencoders","Encoder + Decoder","reconstruction loss","مشروع: AE"),
            U("VAE","Reparameterization Trick","KL Divergence","توليد","مشروع: VAE"),
            U("GAN","Generator vs Discriminator","Minimax Game","مشروع: GAN"),
            U("DCGAN","Conv2DTranspose","BatchNorm","صور","مشروع: DCGAN"),
            U("Conditional GAN","label conditioning","تحكم","مشروع: cGAN"),
            U("Style Transfer","Content Loss","Style Loss","VGG19","مشروع: Style"),
            U("صعوبات GAN","Mode Collapse","عدم استقرار","WGAN","مشروع: تشخيص"),
            U("VAE vs GAN","VAE: مستقر، blurry","GAN: غير مستقر، حاد","اختيار","مشروع: مقارنة"),
            U("مشروع: GAN للأرقام","MNIST","DCGAN","تدريب","توليد","عرض"),
        ),
        S("نشر النماذج","Flask, FastAPI, Docker",
            U("حفظ النماذج","model.save()","SavedModel","TF Lite","مشروع: حفظ"),
            U("Flask API","@app.route","request.json","jsonify","مشروع: Flask"),
            U("FastAPI","@app.post","Pydantic","Swagger","مشروع: FastAPI"),
            U("Docker","Dockerfile","build, run","مشروع: Docker"),
            U("نشر سحابي","SageMaker","Vertex AI","HuggingFace","مشروع: نشر"),
            U("TF Serving","tensorflow_model_server","REST/gRPC","batching","مشروع: Serving"),
            U("مراقبة النموذج","Data Drift","Concept Drift","تنبيهات","مشروع: مراقبة"),
            U("CI/CD","GitHub Actions","اختبارات تلقائية","مشروع: CI/CD"),
            U("مشروع: نشر API","نموذج","FastAPI","Docker","عرض"),
        ),
        S("مشروع المستوى: نظام DL","بناء وتدريب ونشر",
            U("تحديد المشكلة","ماذا نبني؟","بيانات","معمارية","خطة"),
            U("جمع وتحضير","بيانات","تنظيف","تقسيم","تنسيق"),
            U("بناء النموذج","اختيار معمارية","كود","Compile","اختبار"),
            U("تدريب وتحسين","fit","callbacks","tuning","تحسين"),
            U("تقييم وتحليل","مقاييس","أخطاء","تحسينات","تحليل"),
            U("تحسين النموذج","معالجة أخطاء","معمارية أفضل","بيانات أكثر","ضبط"),
            U("بناء API","FastAPI","POST /predict","توثيق","اختبار"),
            U("نشر","Docker","Cloud","مراقبة","عرض"),
        ),
    ),
    L("المستوى الخامس: التطبيقات المتقدمة","NLP, Transformers, RL, MLOps","create",
        S("NLP","Tokenization, TF-IDF, Embeddings",
            U("Text Preprocessing","lower, strip","tokenize","stop words","stemming","مشروع: تنظيف"),
            U("TF-IDF","TfidfVectorizer","ngram_range","max_features","مشروع: TF-IDF"),
            U("Word Embeddings","Word2Vec, GloVe","المتشابهات متقاربة","king-man+woman","مشروع: Embed"),
            U("Sentiment Analysis","VADER, TextBlob","تصنيف","مشروع: مشاعر"),
            U("Text Classification","Naive Bayes, SVM","Deep Learning","مشروع: تصنيف"),
            U("NER","spaCy, stanza","استخراج الكيانات","مشروع: NER"),
            U("Topic Modeling","LDA","coherence score","pyLDAvis","مشروع: مواضيع"),
            U("Seq2Seq","ترجمة","تلخيص","Beam Search","مشروع: Seq2Seq"),
            U("مشروع: مصنف أخبار","نصوص","معالجة","تصنيف","عرض"),
        ),
        S("Transformers","BERT, GPT, Fine-Tuning",
            U("Self-Attention","Q, K, V","scaled dot-product","O(n²)","مشروع: Attn"),
            U("Multi-Head Attention","8 heads","زوايا مختلفة","دمج","مشروع: MultiHead"),
            U("Positional Encoding","sin/cos","أو learned","مشروع: Encoding"),
            U("BERT","bidirectional","[CLS]","Masked LM","مشروع: BERT"),
            U("GPT","autoregressive","يتنبأ بالكلمة التالية","GPT-3/4","مشروع: GPT"),
            U("Fine-Tuning","HuggingFace Trainer","TrainingArguments","مشروع: FT"),
            U("Hugging Face","pipeline()","AutoModel","Model Hub","مشروع: HF"),
            U("حدود Transformers","O(n²)","max_length","Longformer","مشروع: حدود"),
            U("مشروع: BERT تحليل","بيانات","FineTune","تقييم","عرض"),
        ),
        S("الرؤية المتقدمة","YOLO, Segmentation, Tracking",
            U("Faster R-CNN","RPN","Two-Stage","مشروع: RCNN"),
            U("YOLO","You Only Look Once","real-time","YOLOv8","مشروع: YOLO"),
            U("Segmentation","U-Net","DeepLab","Panoptic","مشروع: Segment"),
            U("Object Tracking","SORT","DeepSORT","Kalman Filter","مشروع: Track"),
            U("Pose Estimation","MediaPipe","OpenPose","مشروع: Pose"),
            U("Face Recognition","FaceNet","dlib","أخلاقيات","مشروع: Face"),
            U("Vision Transformers","ViT","patches","DeiT","مشروع: ViT"),
            U("Augmentation متقدمة","Cutout, MixUp","CutMix, Mosaic","مشروع: Aug"),
            U("مشروع: عداد مركبات","فيديو","YOLO + SORT","تحليل","عرض"),
        ),
        S("Reinforcement Learning","Q-Learning, DQN, Policy Gradients",
            U("أساسيات RL","Agent, Environment","State, Action","Gym","مشروع: CartPole"),
            U("MDP","Markov Property","Transition","Gamma","مشروع: MDP"),
            U("Q-Learning","Q-Table","ε-greedy","Off-Policy","مشروع: QL"),
            U("DQN","Experience Replay","Target Network","مشروع: DQN"),
            U("Policy Gradients","REINFORCE","Actor-Critic","Advantage","مشروع: PG"),
            U("A2C, PPO","stable-baselines3","PPO الأكثر استخداماً","مشروع: PPO"),
            U("OpenAI Gym","env.reset()","env.step()","wrappers","مشروع: Gym"),
            U("تحديات RL","Sample Efficiency","Reward Design","Sim-to-Real","مشروع: تحديات"),
            U("مشروع: Agent CartPole","تدريب","تقييم","تحسين","عرض"),
        ),
        S("MLOps","Pipelines, Tracking, Monitoring",
            U("ML Pipelines","أتمتة","Kubeflow","مشروع: Pipeline"),
            U("Experiment Tracking","MLflow","W&B","سجل كل شيء","مشروع: Track"),
            U("Model Registry","إدارة الإصدارات","مشروع: Registry"),
            U("Feature Store","مركزي","Feast","reuse","مشروع: FS"),
            U("Continuous Training","إعادة تدريب","triggers","مشروع: CT"),
            U("Model Monitoring","Drift","تنبيهات","مشروع: Monitor"),
            U("Shadow Deployment","اختبار بلا مخاطرة","مشروع: Shadow"),
            U("Kubeflow","منصة MLOps","Kubernetes","مشروع: KF"),
            U("مشروع: Pipeline كامل","بيانات","تدريب","نشر","مراقبة","عرض"),
        ),
        S("أخلاقيات AI","Fairness, XAI, Privacy",
            U("التحيز Bias","أسبابه","أمثلة","كشفه","مشروع: كشف"),
            U("Fairness Metrics","Demographic Parity","Equal Opportunity","مشروع: Fairness"),
            U("Explainable AI","SHAP","LIME","Partial Dependence","مشروع: XAI"),
            U("Privacy","Differential Privacy","Federated Learning","مشروع: Privacy"),
            U("Model Cards","توثيق","استخدام مقصود","قيود","مشروع: Card"),
            U("Adversarial Attacks","FGSM","PGD","دفاعات","مشروع: Attack"),
            U("Robustness","Adversarial Training","Certified","مشروع: Robust"),
            U("التنظيم","GDPR","EU AI Act","مشروع: تنظيم"),
            U("مشروع: تدقيق أخلاقي","نموذج","فحص bias","تفسير","تقرير","عرض"),
        ),
        S("المشروع الختامي","تطبيق جميع مهارات التخصص",
            U("اختيار المشكلة","مشكلة حقيقية","بيانات","تأثير","خطة"),
            U("تخطيط","معمارية","تقنيات","جدول","فريق"),
            U("جمع وتحضير","مصادر","تنظيف","تنسيق","EDA"),
            U("بناء النموذج","خوارزمية","تنفيذ","تدريب","نتائج"),
            U("تحسين","Tuning","تجارب","مقارنة","الأفضل"),
            U("تقييم","مقاييس","اختبار","تحليل","حدود"),
            U("بناء واجهة","تطبيق/API","UX","اختبار","تحسين"),
            U("نشر","Docker","Cloud","CI/CD","مراقبة"),
            U("عرض نهائي","توثيق","عرض تقديمي","Demo","تسليم"),
        ),
    ),
]

MISTAKES = [
    ("Data Leakage","Scaler قبل التقسيم = معلومات الاختبار تتسرب = دقة وهمية.","اقسم أولاً. scaler.fit(X_train). scaler.transform(X_test). Pipeline.","لا تدع أي معلومات من الاختبار تتسرب — تقييمك يصبح بلا قيمة.","critical"),
    ("Accuracy على بيانات غير متوازنة","95% فئة A، نموذج يتنبأ دائماً بـ A = 95% Accuracy. لكنه فاشل.","Precision, Recall, F1, confusion_matrix, classification_report.","قبل اختيار المقياس: ما الفئة الأهم؟ Accuracy مضللة.","major"),
    ("عدم توحيد المقياس","متغير 1-1000 يسيطر على المسافات = تجميع سيئ.","StandardScaler قبل النماذج الحساسة للمسافة. Trees لا تحتاج.","كل نموذج يعتمد على المسافات أو gradient descent يحتاج scaling.","major"),
    ("Overfitting","دقة تدريب 99%، اختبار 65%. النموذج حفظ ولم يتعلم.","تبسيط، بيانات أكثر، Regularization، Cross-Validation، EarlyStopping.","تخيل طالباً يحفظ الإجابات دون فهم. افحص الفجوة دائماً.","critical"),
    ("Learning Rate غير مناسب","lr صغير = بطيء. lr كبير = تذبذب.","ابدأ بـ 0.001 لـ Adam. Learning Rate Scheduler. ارسم loss.","loss ينخفض بسلاسة = جيد. يتأرجح = كبير. ينخفض ببطء = صغير.","major"),
    ("نسيان Early Stopping","100 عصر و val_loss يتزايد من epoch 20 = Overfitting.","EarlyStopping(patience=5, restore_best_weights=True).","إذا توقف تحسن validation لـ 5 عصور، توقف.","major"),
    ("حلقات for مع Pandas","for على 100K صف: 5 ثوان. متجهة: 0.002 ثانية.","df['new'] = df['a'] + df['b']. apply() للحالات الخاصة.","إذا كتبت for مع Pandas، توقف. هل هناك طريقة متجهة؟","minor"),
    ("عدم استخدام Pipeline","خطوات يدوية = نسيان = Data Leakage.","Pipeline([('scaler',Scaler()),('model',Model())]).","Pipeline صديقك — يحميك من نفسك. استخدمه دائماً.","major"),
]

def make_bridge(prev, curr):
    return [
        f"الأن وقد أتقنتَ {prev}، نرتقي إلى {curr}.",
        f"في الدرس السابق فككنا {prev}. اليوم نبني عليه ونتعلم {curr}.",
        f"بعد {prev}، {curr} يسد الفجوة التالية في معرفتك.",
        f"{prev} كان الأساس. اليوم {curr} هو الطابق التالي.",
    ][h(prev+curr)%4]

def generate_lessons(unit_code, lesson_titles, stage_name, slug):
    lessons = []; prev = "المفاهيم الأساسية"
    for li, title in enumerate(lesson_titles, 1):
        nm = 2+(h(f"{unit_code}_{li}")%2)
        lm = [{"mistake":f"{m[0]}\n{m[1]}","correction":m[2],"treatment":m[3],"severity":m[4]} for m in [MISTAKES[(h(f"{unit_code}_{li}_{mi}"))%len(MISTAKES)] for mi in range(nm)]]
        lessons.append({
            "lesson_index":li, "name":title,
            "goal":f"فهم وتطبيق {title} عملياً",
            "bridge_sentence":make_bridge(prev, title),
            "prerequisite_lessons":[] if li==1 else [f"{unit_code}.{li-1}"],
            "enables_lessons":[] if li==len(lesson_titles) else [f"{unit_code}.{li+1}"],
            "final_check_question":f"اشرح {title} بكلماتك. ما الخطوات العملية لتطبيقه؟",
            "session_complete_criterion":f"يشرح الطالب {title} ويطبقه عملياً",
            "yemeni_examples":[f"تطبيق عملي: {title} في مشروع حقيقي."],
            "expected_duration_minutes":30,"estimated_gem_cost":90,
            "solution_outline":f"خطوات {title}:\n1. فهم الأساس\n2. كتابة الكود\n3. التجربة\n4. التحليل\n5. التوثيق",
            "motivation_hook":f"{title} - مهارة أساسية في رحلة احتراف الذكاء الاصطناعي.",
            "learning_objectives":[{"statement":f"يفهم {title}","bloom_level":"understand"},{"statement":f"يطبق {title}","bloom_level":"apply"}],
            "glossary":[],"concepts":[{"name":title,"explanation":f"شرح وتطبيق عملي لـ {title}.","mastery_criterion":f"يشرح {title} ويطبقه","weight":1}],
            "common_mistakes":lm
        }); prev = title
    return lessons

def generate_labs(unit_code, unit_name, n_lessons, slug):
    return [{"lab_index":li,"title":f"معمل {unit_name}: {'التشخيص' if li==1 else 'التطبيق'}",
        "scenario":f"مشكلة تقنية في {unit_name}. حللها وقدم حلاً عملياً.","completion_criterion":f"تحليل وحل",
        "pedagogical_sequence":"diagnostic -> decision -> application -> analysis -> connection",
        "prerequisite_lessons":[f"{unit_code}.{n_lessons//2}"],"allowed_tools":["text","code"],
        "questions":[
            {"kind":"diagnostic","prompt":f"خطوات تشخيص مشكلة في {unit_name}؟","rubric":"يجب ذكر 4 خطوات منطقية","solution_outline":"جمع المعلومات ثم تحليلها ثم تحديد السبب ثم اقتراح الحل","points":1},
            {"kind":"decision","prompt":f"خياران لحل في {unit_name}. معاييرك؟","rubric":"يجب ذكر معيارين مع تبرير","solution_outline":"الدقة والسرعة والتعقيد","points":1},
            {"kind":"application","prompt":f"اكتب كوداً لـ {unit_name}.","rubric":"كود صحيح يعمل وينتج نتائج","solution_outline":"استيراد المكتبات ثم تطبيق النموذج ثم تقييم النتائج","points":2},
            {"kind":"analysis","prompt":f"كود لـ {unit_name} فيه 3 أخطاء.","rubric":"يكتشف 3 أخطاء مع شرح","solution_outline":"تحليل الأخطاء الثلاثة وتصحيح كل منها","points":1},
            {"kind":"connection","prompt":f"اربط {unit_name} بمهارات سابقة.","rubric":"يذكر رابطين مع فكرة","solution_outline":"ربط بالمهارات السابقة وخطة مشروع","points":1}]} for li in range(1,3)]

def gen_exam(code, scope, n=10):
    qs = [
        ("الخطوة الأولى في مشروع ML:",["فهم المشكلة","تطبيق خوارزمية","جمع بيانات","كتابة كود"],0,1,"بدون هدف واضح، أفضل خوارزمية لن تعطي نتيجة."),
        ("الفرق بين Supervised و Unsupervised:",["المراقب يحتاج تسميات","لا فرق","المراقب أسرع","غير المراقب أدق"],0,1,"المراقب يستخدم بيانات معنونة."),
        ("ما هو Overfitting؟",["النموذج يحفظ ولا يعمم","بسيط جداً","سريع","قليل البيانات"],0,2,"أداء ممتاز على التدريب، فشل على البيانات الجديدة."),
        ("الغرض من Cross-Validation:",["تقييم موثوق","تسريع","زيادة بيانات","تغيير خوارزمية"],0,2,"يقسم لـ k أجزاء ويتأكد من ثبات الأداء."),
        ("دالة التنشيط الأكثر استخداماً:",["ReLU","Sigmoid","Softmax","Linear"],0,2,"ReLU تحل Vanishing Gradient."),
        ("ما وظيفة Dropout؟",["منع Overfitting","تسريع","تكبير","تغيير تنشيط"],0,2,"يعطل عشوائياً عصبونات لمنع الاعتماد المفرط."),
        ("نموذج للتصنيف الثنائي:",["Logistic Regression","Linear Regression","K-Means","PCA"],0,2,"يستخدم Sigmoid للاحتمالات بين 0 و 1."),
        ("ما هو Data Leakage؟",["تسرب معلومات الاختبار","فقدان بيانات","تسرب ذاكرة","توقف تدريب"],0,2,"تسرب معلومات من الاختبار = تقييم وهمي."),
    ]
    variants = []
    for v in range(3):
        vq = [{"question_index":qi+1,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {ch}" for ci,ch in enumerate(c)],"correct_index":ci,"explanation":e,"difficulty":d,"points":1,"time_limit_seconds":60+d*30} for qi,(p,c,ci,d,e) in enumerate([qs[(h(f"{code}_{v}_{qi}"))%len(qs)] for qi in range(n)])]
        variants.append(vq)
    return {"code":code,"scope":scope,"variants":variants}

def gen_placement():
    qs = [
        (1,"مخرج print(type(3.14)):",["<class 'float'>","<class 'int'>","<class 'str'>","<class 'bool'>"],0,1),
        (2,"وظيفة df.describe():",["إحصائيات وصفية","حذف فارغات","رسم","تغيير أسماء"],0,1),
        (3,"نموذج للتصنيف الثنائي:",["Logistic Regression","Linear Regression","K-Means","PCA"],0,2),
        (4,"وظيفة Conv2D:",["عملية الالتفاف","تسطيح","Dropout","تغيير تنشيط"],0,2),
        (5,"ما هي MLOps؟",["تشغيل نماذج ML","نوع خوارزميات","لغة برمجة","قاعدة بيانات"],0,3),
        (1,"إنشاء قائمة بالأعداد الزوجية:",["[x for x in range(10) if x%2==0]","list(range(even))","[x for x in range(10) if x/2==0]","[x for x in even(10)]"],0,1),
        (2,"معامل عدد النقاط linspace:",["الثالث","الأول","الثاني","لا يوجد"],0,1),
        (3,"الغرض من train_test_split:",["تقسيم البيانات","تسريع","زيادة","تغيير نوع"],0,2),
        (4,"فائدة Transfer Learning:",["نموذج مدرب مسبقاً","نقل بيانات","تغيير لغة","تحويل صيغة"],0,2),
        (5,"Transformer في:",["BERT و GPT","CNN فقط","K-Means","Linear Regression"],0,3),
    ]
    return [{"target_level_index":l,"kind":"mcq","prompt":p,"choices":[f"{chr(1571+ci)})\u200f {c}" for ci,c in enumerate(c)],"correct_index":ci,"difficulty":d,"explanation":f"مستوى {l}"} for l,p,c,ci,d in qs]

def main():
    print(f"\n{'='*60}\n  uni-ai v4 - تسلسل منطقي\n{'='*60}\n")
    meta = {"slug":"uni-ai","name":"الذكاء الاصطناعي","icon":"🤖",
        "desc":"منهج متكامل: من Python والرياضيات إلى الشبكات العميقة ونشر النماذج. تسلسل منطقي حقيقي.",
        "scope":"professional_track","language":"ar","region":"YE",
        "target_persona":"طالب يمتلك أساسيات البرمجة ويريد التخصص في الذكاء الاصطناعي.",
        "teacher_tone":"مباشرة وعملية: نشرح كل مفهوم بخطوات واضحة وننتقل فوراً للكود.",
        "viz":["python_trace","flowchart","scatter_plot","line_chart","bar_chart","heatmap","tree_diagram"],
        "tools":["text","code","image"],
        "glossary":[{"term":"Gradient Descent","definition":"خوارزمية تحسين"}]}
    result_levels = []; all_uc = []; all_sc = []
    for li, (lname, lgoal, lbloom, stages) in enumerate(CURRICULUM):
        lv = li+1; rstages = []
        for si, (sname, sgoal, units) in enumerate(stages):
            sv = si+1; sc = f"{lv}.{sv}"; all_sc.append(sc); runits = []
            for ui, (uname, lesson_titles) in enumerate(units):
                lesson_titles = [t for t in lesson_titles if t and len(t) >= 3]
                uv = ui+1; uc = f"{sc}.{uv}"; all_uc.append(uc)
                lessons = generate_lessons(uc, lesson_titles, sname, "uni-ai")
                labs = generate_labs(uc, uname, len(lessons), "uni-ai")
                prereq = [f"{sc}.{ui}"] if ui>0 else []
                enables = [f"{sc}.{ui+2}"] if ui<len(units)-1 else []
                runits.append({"unit_index":uv,"name":uname,"goal":f"إتقان {uname}" if len(f"إتقان {uname}") >= 10 else f"إتقان {uname} بشكل متقن","prerequisite_units":prereq,"enables_units":enables,"key_concepts":[lesson_titles[0][:20]],"motivation_hook":f"وحدة {uname} - خطوتك نحو الاحتراف.","learning_objectives":[{"statement":f"يتقن {uname}","bloom_level":"apply"}],"lessons":lessons,"labs":labs,"exam":{"pass_threshold_percent":60,"points":10,"time_limit_minutes":30}})
                print(f"  {uc}: {uname[:50]} ({len(lesson_titles)} دروس)")
            rstages.append({"stage_index":sv,"name":sname,"goal":sgoal,"bloom_focus":lbloom,"units":runits,"exam":{"pass_threshold_percent":60,"points":20,"time_limit_minutes":45}})
        result_levels.append({"level_index":lv,"name":lname,"goal":lgoal,"bloom_focus":lbloom,"stages":rstages,"exam":{"pass_threshold_percent":60,"points":50,"time_limit_minutes":90}})
    print("\n  توليد بنوك الامتحانات...")
    ub = {c:gen_exam(c,"unit",10) for c in all_uc}
    sb = {c:gen_exam(c,"stage",15) for c in all_sc}
    lb = {str(i):gen_exam(str(i),"level",20) for i in range(1,6)}
    final = {"schema_version":"v4.1","specialty":{**meta,"yemeni_examples":["تطبيق عملي"]},"levels":result_levels,"exam_banks":{"unit_banks":ub,"stage_banks":sb,"level_banks":lb},"placement_test_questions":gen_placement(),"publish_notes":"uni-ai v4 - تسلسل منطقي حقيقي لكل وحدة"}
    fp = OUT/"final.json"
    with open(fp,'w',encoding='utf-8') as f: json.dump(final,f,ensure_ascii=False,indent=2)
    sz = fp.stat().st_size/(1024*1024)
    tl = sum(1 for l in result_levels for s in l['stages'] for u in s['units'] for _ in u['lessons'])
    print(f"\n  ✅ {sz:.1f} MB | {len(result_levels)} مستويات | {tl} درس\n")

if __name__ == "__main__":
    main()

C = [
L("المستوى الأول: Python وأساسيات تحليل البيانات","إتقان Python, NumPy, Pandas, Matplotlib للتحليل","apply",

# ── المرحلة 1: أساسيات Python لعلم البيانات ──
S("أساسيات Python لعلم البيانات","كتابة كود Python بطلاقة لتحليل البيانات",

# الوحدة 1.1.1
U("تشغيل Python وبيئة العمل",
"تثبيت Python و Jupyter Notebook على جهازك","تشغيل أول خلية: print('Hello, Data Science!')","العمليات الحسابية الأساسية: + - * /","أنواع البيانات: int, float, str, bool","التعليقات: كتابة كود يشرح نفسه","المتغيرات: تخزين القيم واسترجاعها","دوال أساسية: type(), len(), range(), input()","استيراد المكتبات: import pandas as pd","قراءة أول ملف CSV: pd.read_csv() ومعاينة البيانات","مشروع: استكشف مجموعة بيانات من اختيارك"),
# الوحدة 1.1.2
U("المتغيرات والعمليات الأساسية",
"المتغيرات: قواعد التسمية وأفضل الممارسات","النوع int: الأعداد الصحيحة والعمليات عليها","النوع float: الكسور العشرية والقسمة في Python 3","النوع str: النصوص والسلاسل — التقطيع والتلاعب","النوع bool: القيم المنطقية واستخدامها في الشروط","التحويل بين الأنواع: int(), str(), float(), bool()","العمليات الحسابية: + - * / // % ** بعمق","عوامل المقارنة: == != < > <= >=","العوامل المنطقية: and or not — بناء شروط معقدة","مشروع: آلة حاسبة لتحليل بيانات"),
# الوحدة 1.1.3
U("القوائم List في علم البيانات",
"إنشاء القوائم: [] و list() و range()","الفهرسة من الصفر: الوصول لأي عنصر في القائمة","التقطيع Slicing: استخراج أجزاء [start:stop:step]","إضافة عناصر: append(), extend(), insert()","حذف عناصر: remove(), pop(), del","ترتيب القوائم: sort(), sorted(), reverse()","دوال مفيدة: len(), min(), max(), sum(), count()","List Comprehensions: بناء قوائم جديدة بسطر واحد","القوائم المتداخلة: تمثيل بيانات جدولية","مشروع: تحليل قائمة أسعار منتجات"),
# الوحدة 1.1.4
U("القواميس Dict وهياكل البيانات",
"إنشاء القواميس: {} و dict() — المفتاح والقيمة","الوصول للقيم: d['key'] و d.get('key', default)","إضافة وتعديل وحذف العناصر في القاموس","التكرار على القواميس: keys(), values(), items()","Dict Comprehensions: بناء القواميس باختصار","Tuple: البيانات الثابتة غير القابلة للتغيير","Set: المجموعات وإزالة التكرار والعمليات","مقارنة الهياكل: List vs Dict vs Tuple vs Set","تحويل DataFrame لـ Dict والعكس","مشروع: بناء محلل بيانات بسيط بقواميس"),
# الوحدة 1.1.5
U("الدوال Functions في Python",
"تعريف الدالة: def — لماذا نحتاج الدوال؟","المعاملات Parameters: إدخال البيانات للدالة","return: إرجاع النتائج من الدالة","الوسائط الافتراضية: قيم افتراضية للمعاملات","وسائط متعددة: *args و **kwargs","lambda: كتابة دوال سريعة في سطر واحد","توثيق الدوال: docstrings","نطاق المتغيرات Scope: محلي وعام","إعادة الاستخدام: مبدأ DRY وتنظيم الكود","مشروع: مكتبة دوال لتنظيف وتحليل البيانات"),
# الوحدة 1.1.6
U("الجمل الشرطية ومعالجة الأخطاء",
"if و else: أول قرار في برنامجك","elif: تعدد المسارات — أكثر من خيارين","الشروط المتداخلة: if داخل if","if مع in: فحص انتماء عنصر لمجموعة","التعبير الشرطي المختصر: x if condition else y","try/except: التعامل مع الأخطاء","أنواع الأخطاء: TypeError, ValueError, KeyError","finally: كود ينفذ دائماً","raise: رمي الأخطاء للتحقق من المدخلات","مشروع: مدقق جودة بيانات"),
# الوحدة 1.1.7
U("الحلقات والتكرار في Python",
"for مع range(): التكرار المنظم بعدد محدد","for مع القوائم: التكرار على كل عنصر","enumerate(): الحصول على الفهرس والقيمة معاً","while: التكرار بشرط","break: الخروج الفوري من الحلقة","continue: تخطي الدورة الحالية","الحلقات المتداخلة: for داخل for","List Comprehension مقابل الحلقة","التكرار على DataFrame: iterrows(), itertuples()","مشروع: تقرير إحصائي من ملف CSV"),
# الوحدة 1.1.8
U("العمل مع الملفات والبيانات",
"فتح الملفات: open() مع 'r', 'w', 'a'","قراءة ملف كامل: read() و readlines()","كتابة الملفات: كتابة النتائج والتحليلات","معالجة CSV يدوياً: csv.reader()","معالجة JSON: json.load() و json.dump()","معالجة Excel: openpyxl","مسارات الملفات: os.path و pathlib","ترميز الملفات: utf-8 والنصوص العربية","الملفات الكبيرة: القراءة سطراً سطراً","مشروع: جامع بيانات آلي من مصادر متعددة"),
# الوحدة 1.1.9
U("مشروع: نظام تحليل بيانات متكامل",
"تخطيط المشروع: تحديد الأهداف ونطاق العمل","جمع البيانات: استيراد من CSV و Excel و JSON","استكشاف البيانات: df.head(), info(), describe()","تنظيف البيانات: التعامل مع القيم المفقودة","تحليل إحصائي: المتوسطات والوسيط والانحراف","التجميع: groupby لحساب إحصائيات حسب الفئات","إنشاء تقرير: كتابة النتائج في ملف منظم","تصدير النتائج: حفظ البيانات المعالجة","توثيق الكود: شرح كل خطوة","العرض النهائي: تقديم المشروع مع النتائج"),
),

# ── المرحلة 2: NumPy — الحوسبة العددية ──
S("NumPy: الحوسبة العددية فائقة السرعة","المصفوفات، العمليات المتجهة، الإحصاء",
U("مقدمة NumPy: لماذا هي أسرع 50 مرة؟",
"ما هو NumPy؟ المكتبة الأساسية للحوسبة العلمية","مقارنة الأداء: قوائم Python مقابل NumPy","تثبيت واستيراد: import numpy as np","إنشاء المصفوفات: np.array() من القوائم","المصفوفات الجاهزة: zeros(), ones(), arange()","linspace(): نقاط متساوية في مدى","eye(): مصفوفة الوحدة","shape, dtype, ndim","التخزين المتجاور: لماذا NumPy أسرع؟","مشروع: قياس أداء List مقابل NumPy"),
U("الفهرسة والتقطيع في NumPy",
"الفهرسة من 0: الوصول للعناصر","التقطيع [start:stop:step]","المصفوفات ثنائية الأبعاد: [row, col]","التقطيع في 2D: [:,0] للأعمدة","Boolean Masking: arr[arr > threshold]","Fancy Indexing: تحديد بقائمة مؤشرات","تعديل القيم عبر الفهرسة","الفرق بين view و copy","الفهرسة السالبة","مشروع: استخراج وتعديل بيانات"),
U("العمليات المتجهة Vectorized",
"عمليات عنصر بعنصر: + - * / **","الدوال الرياضية: sqrt(), log(), exp()","Broadcasting: بين أبعاد مختلفة","قواعد Broadcasting","np.where(): if-else على المصفوفة","np.select(): شروط متعددة","Vectorization مقابل الحلقات","كتابة دوال متجهة: np.vectorize()","تجنب الحلقات في NumPy","مشروع: تحويل حلقات لمتجهات"),
U("الدوال الإحصائية في NumPy",
"المتوسط: np.mean()","الوسيط: np.median()","الانحراف المعياري: np.std()","المجاميع: sum(), min(), max()","المحاور: axis=0 و axis=1","المئينات: percentile(), quantile()","الارتباط: np.corrcoef()","التوزيع: np.histogram()","القيم الفريدة: np.unique()","مشروع: تقرير إحصائي كامل"),
U("إعادة تشكيل المصفوفات",
"reshape(): تغيير الشكل","-1: حساب تلقائي للبعد","flatten() و ravel(): تسطيح","transpose() و .T: تبديل","np.newaxis: إضافة بعد","stack: vstack, hstack, dstack","split: تقسيم المصفوفات","concatenate: دمج","تطبيق: معالجة بيانات الصور","مشروع: تشكيل بيانات متعددة الأبعاد"),
U("Boolean Masking والتصفية",
"arr[arr > threshold]: أساسيات","شروط مركبة: & و |","~: النفي","np.where(): استبدال شرطي","np.extract(): استخراج بالشرط","np.any() و np.all()","Masking مع NaN","Masking متعدد الأبعاد","تطبيق: تصفية قيم شاذة","مشروع: تنظيف بيانات بـ Masking"),
U("الجبر الخطي مع NumPy",
"ضرب المصفوفات: @ و np.dot()","inv(): معكوس المصفوفة","det(): المحدد","norm(): المعيار","solve(): حل المعادلات","eig(): القيم والمتجهات الذاتية","svd(): تحليل القيمة المنفردة","تطبيق: حل الانحدار الخطي","تطبيق: PCA بسيط بـ SVD","مشروع: انحدار خطي من الصفر"),
U("توليد الأرقام العشوائية",
"seed(): تثبيت العشوائية","rand(): توزيع منتظم","randn(): توزيع طبيعي","randint(): أعداد صحيحة","choice(): اختيار عشوائي","shuffle(): خلط","توليد بيانات وهمية","محاكاة Monte Carlo بسيطة","تطبيق: bootstrap sampling","مشروع: محاكاة بيانات"),
U("مشروع: تحليل بيانات بـ NumPy",
"تخطيط التحليل","تحميل البيانات كمصفوفات","تنظيف: إزالة NaN والشواذ","حسابات إحصائية شاملة","تحليل الارتباطات","كشف القيم المتطرفة","تطبيع البيانات يدوياً","تصدير النتائج","توثيق","عرض"),
),
),
],
